### ISSUE TITLE
Got an exception when bind app to "http://*:port"

### ISSUE THREAD

**Issue by ISTAnsver** [CoreWCF/CoreWCF#100]
When I try to bind Kestrel app to url "http://*:port" I've got next exception:

System.UriFormatException:` "Invalid URI: The hostname could not be parsed."
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at CoreWCF.Channels.ServiceModelHttpMiddleware.BuildBranch(IApplicationBuilder app, IServiceBuilder serviceBuilder, IDispatcherBuilder dispatcherBuilder) in C:\CS\CloudSmetaSolutionCore\CoreWcfProjects\CoreWCF.Http\src\CoreWCF\Channels\ServiceModelHttpMiddleware.cs:line 37
   at CoreWCF.Channels.ServiceModelHttpMiddleware..ctor(RequestDelegate next, IApplicationBuilder app, IServiceBuilder serviceBuilder, IDispatcherBuilder dispatcherBuilder) in C:\CS\CloudSmetaSolutionCore\CoreWcfProjects\CoreWCF.Http\src\CoreWCF\Channels\ServiceModelHttpMiddleware.cs:line 23

**Comment by mconnew** [comment]
Is this a format which ASP.NET Core supports? Or are you copying the convention from WCF on .NET Framework where we support something similar (I think with a +)?

**Comment by ISTAnsver** [comment]
It's the format which ASP.NET Core supports.

**Comment by 0x53A** [comment]
One easy way to test this:

Do not use ``UseUrls`` in code.

1) Doesn't work: ``set ASPNETCORE_URLS=http://+:80``

```
Application startup exception: System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at CoreWCF.Channels.ServiceModelHttpMiddleware.BuildBranch(IApplicationBuilder app, IServiceBuilder serviceBuilder, IDispatcherBuilder dispatcherBuilder)
   at CoreWCF.Channels.ServiceModelHttpMiddleware..ctor(RequestDelegate next, IApplicationBuilder app, IServiceBuilder serviceBuilder, IDispatcherBuilder dispatcherBuilder)
```

2) works: ``set ASPNETCORE_URLS=http://0.0.0.0:80``

----------


The official docker image sets ``ASPNETCORE_URLS=http://+:80``: https://hub.docker.com/r/microsoft/aspnetcore/
