### ISSUE TITLE
What need to know if use CoreWCF with reverse proxy?

### ISSUE THREAD

**Issue by ISTAnsver** [CoreWCF/CoreWCF#101]
I have some problem when use traefik with CoreWCF. I also try to use traefik with ASP.NET Core and it works fine. They work parallel. ASP.NET Core works. CoreWCF doesn't work.

I already looked at issue in traefik repo (containous/traefik#3237). But configuring traefik doesn't help.

I've got next logs on traefik side:
`traefik_reverse-proxy.1.x9n3o282ax36@dm-node1    | time="2020-02-12T11:39:35Z" level=debug msg="'502 Bad Gateway' caused by: EOF"`

The application says:
```
cloud-service_transport.1.vfgenw539lcb@dm-node2    | info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
cloud-service_transport.1.vfgenw539lcb@dm-node2    |       Request starting HTTP/1.1 POST http://transport.local/Transport/StroySoft.SmetaCloud.Transport.TransportContract.svc text/xml 190
cloud-service_transport.1.vfgenw539lcb@dm-node2    |
cloud-service_transport.1.vfgenw539lcb@dm-node2    | ===== START REQUEST HEADERS =====
cloud-service_transport.1.vfgenw539lcb@dm-node2    | Cache-Control: no-cache
cloud-service_transport.1.vfgenw539lcb@dm-node2    | Content-Type: text/xml
cloud-service_transport.1.vfgenw539lcb@dm-node2    | Accept: */*
cloud-service_transport.1.vfgenw539lcb@dm-node2    | Accept-Encoding: gzip, deflate, br
cloud-service_transport.1.vfgenw539lcb@dm-node2    | Host: transport.local
cloud-service_transport.1.vfgenw539lcb@dm-node2    | User-Agent: PostmanRuntime/7.22.0
cloud-service_transport.1.vfgenw539lcb@dm-node2    | Content-Length: 190
cloud-service_transport.1.vfgenw539lcb@dm-node2    | Postman-Token: 34793746-406c-4e89-bb4a-e5236644df20
cloud-service_transport.1.vfgenw539lcb@dm-node2    | Soapaction: stroysoft:smetacloud:transport/ITransportContract/Echo
cloud-service_transport.1.vfgenw539lcb@dm-node2    | X-Forwarded-For: 10.0.0.2
cloud-service_transport.1.vfgenw539lcb@dm-node2    | X-Forwarded-Host: transport.local
cloud-service_transport.1.vfgenw539lcb@dm-node2    | X-Forwarded-Port: 80
cloud-service_transport.1.vfgenw539lcb@dm-node2    | X-Forwarded-Proto: http
cloud-service_transport.1.vfgenw539lcb@dm-node2    | X-Forwarded-Server: d7d5651d5acb
cloud-service_transport.1.vfgenw539lcb@dm-node2    | X-Real-Ip: 10.0.0.2
cloud-service_transport.1.vfgenw539lcb@dm-node2    | ===== END REQUEST HEADERS =====
cloud-service_transport.1.vfgenw539lcb@dm-node2    |
cloud-service_transport.1.vfgenw539lcb@dm-node2    | ===== START REQUEST BODY =====
cloud-service_transport.1.vfgenw539lcb@dm-node2    | <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
cloud-service_transport.1.vfgenw539lcb@dm-node2    |  <soapenv:Body>
cloud-service_transport.1.vfgenw539lcb@dm-node2    |  <Echo xmlns="stroysoft:smetacloud:transport">
cloud-service_transport.1.vfgenw539lcb@dm-node2    |  </Echo>
cloud-service_transport.1.vfgenw539lcb@dm-node2    |  </soapenv:Body>
cloud-service_transport.1.vfgenw539lcb@dm-node2    | </soapenv:Envelope>
cloud-service_transport.1.vfgenw539lcb@dm-node2    | ===== END REQUEST BODY =====
cloud-service_transport.1.vfgenw539lcb@dm-node2    |
cloud-service_transport.1.vfgenw539lcb@dm-node2    | info: Microsoft.AspNetCore.Server.Kestrel[34]
cloud-service_transport.1.vfgenw539lcb@dm-node2    |       Connection id "0HLTFMGVONIE6", Request id "0HLTFMGVONIE6:00000001": the application aborted the connection.
cloud-service_transport.1.vfgenw539lcb@dm-node2    | info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
cloud-service_transport.1.vfgenw539lcb@dm-node2    |       Request finished in 327.7999ms 0
cloud-service_transport.1.vfgenw539lcb@dm-node2    | warn: Microsoft.AspNetCore.Server.Kestrel[0]
cloud-service_transport.1.vfgenw539lcb@dm-node2    |       Connection processing ended abnormally.
cloud-service_transport.1.vfgenw539lcb@dm-node2    | Microsoft.AspNetCore.Connections.ConnectionAbortedException: The connection was aborted by the application.
cloud-service_transport.1.vfgenw539lcb@dm-node2    |    at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
cloud-service_transport.1.vfgenw539lcb@dm-node2    |    at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
cloud-service_transport.1.vfgenw539lcb@dm-node2    |    at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
cloud-service_transport.1.vfgenw539lcb@dm-node2    |    at System.IO.Pipelines.Pipe.DefaultPipeReader.ReadAsync(CancellationToken cancellationToken)
cloud-service_transport.1.vfgenw539lcb@dm-node2    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.BeginRead(ValueTask`1& awaitable)
cloud-service_transport.1.vfgenw539lcb@dm-node2    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
cloud-service_transport.1.vfgenw539lcb@dm-node2    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
```
Some logs have writen by my middleware which I add when try to debug it.
Direct requests without reverse-proxy finishes normally and I get a response with status 200:
```
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
    <s:Body>
        <EchoResponse xmlns="stroysoft:smetacloud:transport">
            <EchoResult>Echo transport: </EchoResult>
        </EchoResponse>
    </s:Body>
</s:Envelope>
```
With reverse proxy I get a response with status 502:
`Bad Gateway`

If need more information only say and I'll try to get it for you.

**Comment by ISTAnsver** [comment]
Ok. I have investigated the middleware initialization in `UseServiceModel` and remarked that `tbe`variable of type `HttpTransportBindingElement` have property `KeepAliveEnabled` is setted to `false`. It is strange because in the constructor of `HttpTransportBindingElement` `KeepAliveEnabled` is setting to `true` from the constant. As I know that problem with traefik is bound with keep alive.

**Comment by ISTAnsver** [comment]
I try to user nginx for requests proxing. Connection header that server has got from nginx is setted to close. With nginx it works fine. When I start to use next pipeline traefik -> nginx -> CoreWCF Application. All start to work.
Now application logs looks like this:
```
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | Hosting environment: Production
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | Content root path: /transport
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | Now listening on: http://0.0.0.0:8030
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | Application started. Press Ctrl+C to shut down.
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    |       Request starting HTTP/1.0 POST http://transport:8030/Transport/StroySoft.SmetaCloud.Transport.TransportContract.svc text/xml 190
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    |
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | ===== START REQUEST HEADERS =====
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | Cache-Control: no-cache
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | Connection: close
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | Content-Type: text/xml
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | Accept: */*
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | Accept-Encoding: gzip, deflate, br
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | Host: transport:8030
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | User-Agent: PostmanRuntime/7.22.0
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | Content-Length: 190
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | Postman-Token: 7fbce24d-2193-4719-a945-ccc86839967d
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | Soapaction: stroysoft:smetacloud:transport/ITransportContract/Echo
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | X-Forwarded-For: 10.0.0.2
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | X-Forwarded-Host: transport.local
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | X-Forwarded-Port: 80
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | X-Forwarded-Proto: http
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | X-Forwarded-Server: b33ef393223a
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | X-Real-Ip: 10.0.0.2
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | ===== END REQUEST HEADERS =====
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    |
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | ===== START REQUEST BODY =====
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    |  <soapenv:Body>
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    |  <Echo xmlns="stroysoft:smetacloud:transport">
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    |  </Echo>
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    |  </soapenv:Body>
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | </soapenv:Envelope>
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | ===== END REQUEST BODY =====
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    |
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    |       Request finished in 588.9027ms 200 text/xml; charset=utf-8
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    |
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | ===== START REQUEST HEADERS =====
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | Cache-Control: no-cache
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | Connection: close
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | Content-Type: text/xml
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | Accept: */*
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | Accept-Encoding: gzip, deflate, br
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | Host: transport:8030
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | User-Agent: PostmanRuntime/7.22.0
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | Content-Length: 190
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | Postman-Token: ae721a53-bd35-4fcb-8ad5-449d6a53f402
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    |       Request starting HTTP/1.0 POST http://transport:8030/Transport/StroySoft.SmetaCloud.Transport.TransportContract.svc text/xml 190
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | Soapaction: stroysoft:smetacloud:transport/ITransportContract/Echo
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | X-Forwarded-For: 10.0.0.2
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | X-Forwarded-Host: transport.local
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | X-Forwarded-Port: 80
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | X-Forwarded-Proto: http
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | X-Forwarded-Server: b33ef393223a
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | X-Real-Ip: 10.0.0.2
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | ===== END REQUEST HEADERS =====
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    |
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | ===== START REQUEST BODY =====
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    |  <soapenv:Body>
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    |  <Echo xmlns="stroysoft:smetacloud:transport">
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    |  </Echo>
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    |  </soapenv:Body>
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | </soapenv:Envelope>
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | ===== END REQUEST BODY =====
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    |
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    | info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
cloud-service_transport.1.j9rt3bzv80c2@dm-node1    |       Request finished in 3.8404ms 200 text/xml; charset=utf-8
```
Know I sure that promblem with keep-alive.

**Comment by mconnew** [comment]
Are you saying that CoreWCF is ignoring the HttpTransportBindingElement.KeepAliveEnabled property? Or that the default value is incorrect? It should be true by default but it's possible I missed setting that default somewhere.

**Comment by ISTAnsver** [comment]
I say that default value incorrect after the initialization in middleware. You can check it in the method `UseServiceModel` with debugger. When `tbe` variable initializes it has `KeepAlivaEnabled` be set `false`. I think that something similar can be with other properties.

**Comment by mconnew** [comment]
This should be fixed in the latest build. I didn't add any specific tests for that (I need to). Can you verify this is now working for you.

**Comment by ISTAnsver** [comment]
Hello! Sorry for so long time I've dissapeared. I'll try it and give you feedback.

**Comment by ISTAnsver** [comment]
I can't get access to that project and I can't set up an environment and test it at home. I think I should close the issue. Right now I can't reproduce and test this. Sorry.

**Comment by alfonsovgs** [comment]
Hi @ISTAnsver 👋 

I'm using  azure gateway but i have a similar error. Were you able to solve it?

```
{\"ClassName\":\"System.ServiceModel.ProtocolException\",\"Message\":\"The remote server returned an unexpected response: (502) Bad Gateway.\",\"Data\":null,\"InnerException\":{\"ClassName\":\"[System.Net](http://system.net/).WebException\",\"Message\":\"The remote server returned an error: (502) Bad Gateway.\",\"Data\":null,\"InnerException\":null,\"HelpURL\":null,\"StackTraceString\":\"   at [System.Net](http://system.net/).HttpWebRequest.GetResponse()\\r\\n

```
