### ISSUE TITLE
WSDL generation fails with "The named node is from a different document context"

### ISSUE THREAD

**Issue by dennis-yemelyanov** [CoreWCF/CoreWCF#1036]
When WSDL generation is run concurrently from multiple threads, it can fail with the following exception:

```
System.ArgumentException: The named node is from a different document context.
   at System.Xml.XmlAttributeCollection.Append(XmlAttribute node)
   at CoreWCF.Description.SoapHelper.CreateSoapFaultBinding(String name, WsdlEndpointConversionContext endpointContext, FaultBinding wsdlFaultBinding, Boolean isEncoded)
   at CoreWCF.Description.MessageContractExporter.MessageBindingExporter.ExportMessageBinding(OperationDescription operation, Type messageContractExporterType)
   at CoreWCF.Description.MessageContractExporter.ExportMessageBinding(WsdlExporter exporter, WsdlEndpointConversionContext endpointContext, Type messageContractExporterType, OperationDescription operation)
   at CoreWCF.Description.DataContractSerializerOperationBehavior.CoreWCF.Description.IWsdlExportExtension.ExportEndpoint(WsdlExporter exporter, WsdlEndpointConversionContext endpointContext)
   at CoreWCF.Description.WsdlExporter.CallExtension(WsdlEndpointConversionContext endpointContext, IWsdlExportExtension extension)
   --- End of inner ExceptionDetail stack trace ---
   at CoreWCF.Description.ServiceMetadataBehavior.MetadataExtensionInitializer.GenerateMetadata()
   at CoreWCF.Description.ServiceMetadataExtension.EnsureInitialized()
   at CoreWCF.Description.ServiceMetadataExtension.HttpGetImpl.InitializationData.InitializeFrom(ServiceMetadataExtension extension)
   at CoreWCF.Description.ServiceMetadataExtension.HttpGetImpl.GetInitData()
   at CoreWCF.Description.ServiceMetadataExtension.HttpGetImpl.TryHandleMetadataRequestAsync(HttpContext requestContext, IQueryCollection queries)
   at CoreWCF.Description.ServiceMetadataExtension.HttpGetImpl.ProcessHttpRequest(HttpContext requestContext)
* Connection #0 to host localhost left intact
   at CoreWCF.Description.ServiceMetadataExtension.HttpGetImpl.HandleRequest(HttpContext httpContext)
```

This seems to be because `XmlDocument` creation in https://github.com/CoreWCF/CoreWCF/blob/453d91f0b0595c71747cd962b0c916660b0580dc/src/CoreWCF.Primitives/src/CoreWCF/Description/SoapHelper.cs#L23 is not synchronized, so different calls to it from `SoapHelper` may end up getting different instances of `XmlDocument` due to race condition, causing the exception when trying to manipulate some XML nodes and attributes.

Additionally, once the exception is hit once, all subsequent calls to generate WSDL also seem to fail with the same exception until the service is restarted. Although I'm not sure what the reason for that would be, maybe some caching or something else.

**Comment by MaceWindu** [comment]
Any plans to fix it? It is quite serious one. E.g. we could have up to ~100 services in single application and we don't control when clients (many of them) will request WSDL and break application.
