### ISSUE TITLE
CoreWCF closes the response body stream out-of-order before any wrapping middlewares can access it

### ISSUE THREAD

**Issue by mzabsky** [CoreWCF/CoreWCF#1039]
Consider this trivial middleware which follows the usual ASP .Net Core pattern of reading/modifying the response body:
```
        public async Task Invoke(HttpContext context)
        {
            Console.WriteLine("Processing request");

            var originalBodyStream = context.Response.Body;
            
            using var responseBody = new MemoryStream();

            context.Response.Body = responseBody;

            await this.next(context).ConfigureAwait(false);
            
            Console.WriteLine("Processing response: " + Encoding.UTF8.GetString(responseBody.ToArray()));

            responseBody.Seek(0, SeekOrigin.Begin);
            await responseBody.CopyToAsync(originalBodyStream);

            context.Response.Body = originalBodyStream;
        }
```
This middleware is registered to run BEFORE CoreWCF:
```
        app.UseMiddleware<ResponseLoggingMiddleware>();
        app.UseServiceModel(builder =>
```
Expected result would be that CoreWCF would write its response into the MemoryStream and then this middleware would get to access that stream, copy it into the real response body stream and finally let Kestrel deliver the reply to the client.

This is not what happens - by the time the `await this.next(context)` line completes, the responseBody stream is already closed by CoreWCF and any operation on it fails:
```
      System.ObjectDisposedException: Cannot access a closed Stream.
         at System.IO.MemoryStream.Seek(Int64 offset, SeekOrigin loc)
         at CoreWcfTest.ResponseLoggingMiddleware.Invoke(HttpContext context) in C:\Users\matej.zabsky\source\repos\CoreWcfTest\CoreWcfTest\TestMiddleware.cs:line 47
```
The stream gets closed at the following call stack:
```
MyMemoryStream.Close() at C:\Users\matej.zabsky\source\repos\CoreWcfTest\CoreWcfTest\TestMiddleware.cs:line 16
HttpOutput.CloseAsync()
HttpRequestContext.<OnCloseAsync>d__19.MoveNext()
AsyncMethodBuilderCore.Start<CoreWCF.Channels.HttpRequestContext.<OnCloseAsync>d__19>()
AsyncTaskMethodBuilder.Start<CoreWCF.Channels.HttpRequestContext.<OnCloseAsync>d__19>()
HttpRequestContext.OnCloseAsync()
HttpRequestContext.AspNetCoreHttpContext.OnCloseAsync()
RequestContextBase.<CloseAsync>d__29.MoveNext()
AsyncMethodBuilderCore.Start<CoreWCF.Channels.RequestContextBase.<CloseAsync>d__29>()
AsyncTaskMethodBuilder.Start<CoreWCF.Channels.RequestContextBase.<CloseAsync>d__29>()
RequestContextBase.CloseAsync()
RequestContextBase.CloseAsync()
MessageRpc.<DisposeRequestContextAsync>d__55.MoveNext()
AsyncMethodBuilderCore.Start<CoreWCF.Dispatcher.MessageRpc.<DisposeRequestContextAsync>d__55>()
AsyncTaskMethodBuilder.Start<CoreWCF.Dispatcher.MessageRpc.<DisposeRequestContextAsync>d__55>()
MessageRpc.DisposeRequestContextAsync()
MessageRpc.<CloseRequestContextAsync>d__54.MoveNext()
AsyncMethodBuilderCore.Start<CoreWCF.Dispatcher.MessageRpc.<CloseRequestContextAsync>d__54>()
AsyncTaskMethodBuilder.Start<CoreWCF.Dispatcher.MessageRpc.<CloseRequestContextAsync>d__54>()
MessageRpc.CloseRequestContextAsync()
ImmutableDispatchRuntime.<ProcessMessageCleanupAsync>d__66.MoveNext()
AsyncMethodBuilderCore.Start<CoreWCF.Dispatcher.ImmutableDispatchRuntime.<ProcessMessageCleanupAsync>d__66>()
AsyncTaskMethodBuilder.Start<CoreWCF.Dispatcher.ImmutableDispatchRuntime.<ProcessMessageCleanupAsync>d__66>()
ImmutableDispatchRuntime.ProcessMessageCleanupAsync()
ImmutableDispatchRuntime.<ProcessError>d__65.MoveNext()
AsyncMethodBuilderCore.Start<CoreWCF.Dispatcher.ImmutableDispatchRuntime.<ProcessError>d__65>()
AsyncTaskMethodBuilder.Start<CoreWCF.Dispatcher.ImmutableDispatchRuntime.<ProcessError>d__65>()
ImmutableDispatchRuntime.ProcessError()
ImmutableDispatchRuntime.<ProcessMessageAsync>d__64.MoveNext()
AsyncTaskMethodBuilder<MessageRpc>.AsyncStateMachineBox<ImmutableDispatchRuntime.<ProcessMessageAsync>d__64>.ExecutionContextCallback()
ExecutionContext.RunFromThreadPoolDispatchLoop()
AsyncTaskMethodBuilder<MessageRpc>.AsyncStateMachineBox<ImmutableDispatchRuntime.<ProcessMessageAsync>d__64>.MoveNext()
AsyncTaskMethodBuilder<MessageRpc>.AsyncStateMachineBox<ImmutableDispatchRuntime.<ProcessMessageAsync>d__64>.ExecuteFromThreadPool()
ThreadPoolWorkQueue.Dispatch()
PortableThreadPool.WorkerThread.WorkerThreadStart()
Thread.StartCallback()
[Native to Managed Transition]
```
There is a simple (but a *bit* sketchy) workaround for this issue - instead of using MemoryStream, use the following "hacked" class which simply discards the Close:
```
    public class MyMemoryStream : MemoryStream
    {
        public override void Close()
        {
            // base.Close();
        }
    }
```
Despite this workaround, the behavior does limit compatibility and composability with other middlewares, and does prevent the use of recyclable memory streams (at least the Microsoft ones).

Reproduction repository can be found [here](https://github.com/mzabsky/CoreWCFTest). Simply run the console app to see the error happen. Comment `base.Close();` in MyMemoryStream to see everything work correctly.

Observed with both with .Net 6 and 7 and CoreWCF 4.10, on Windows 11.

**Comment by mconnew** [comment]
Try this instead:
```c#
        public async Task Invoke(HttpContext context)
        {
            Console.WriteLine("Processing request");

            var originalBodyStream = context.Response.Body;
            
            using var responseBody = new MemoryStream();

            context.Response.Body = responseBody;

            await this.next(context).ConfigureAwait(false);
            
            if (responseBody.TryGetBuffer(out ArraySegment<byte> buffer))
            {
                Console.WriteLine("Processing response: " + Encoding.UTF8.GetString(buffer.Array, buffer.Offset, buffer.Count));
            }

            // There's an implicit cast operator on ReadOnlyMemory for an ArraySegment
            await responseBody.WriteAsync(buffer); 
            context.Response.Body = originalBodyStream;
        }
```

**Comment by mzabsky** [comment]
Assuming the WriteAsync line is supposed to be:
```await originalBodyStream.WriteAsync(buffer); ```
it does work, and it seems like a better solution than overriding the Close method (and it does enable memory stream pooling).

I do have to still wonder though, if this is the correct behavior? Looking at the internal implementation of MemoryStream, the only difference between these two approaches is that TryGetBuffer checks the "is exposable" flag while the CopyToAsync method checks the "is open" flag (to me it seems odd that one checks the "is open" flag while the other does not - but that is not the subject of this issue). This essentially circumvents the CanRead check the CopyToAsync method of the base Stream does.

**Comment by mconnew** [comment]
You're right, I was writing code blind in a comment box and didn't go near a compiler so referenced the wrong variable. You need to remember that the code which is closing the Stream isn't written specifically for Http, it's written for NetTcp, WebSockets etc. Some of those implementations need the stream closed to know that there's no more content coming. With a simple Http request, asp.net core is informed the request has completed because the Task from the middleware Invoke method completes. But for things like WebSockets, that's not the case. For WebSockets, we abstract the WebSocket with a Stream implementation and when we close the Stream, it tells the implementation to call WebSocket.SendAsync with the endOfMessage argument set to true. The code doing the write to the Stream knows nothing about the transport.  

The only solution we could do is to wrap the stream ourselves with a Stream which no-ops on Close(). That would mean an extra layer in the call stack for every write, and everyone would pay that cost for the few who want the stream to not be closed. When there's the option to change the behavior in your own code, I prefer to not do extra work for everyone else to accommodate something which can be worked around by those who need it.  

As for pooling the MemoryStream object, there's a few things you can do. The constructor your using starts with a small array allocated, and when it hits the limit, it allocates a new array with the size being the smallest power of 2 that is bigger than what's needed, and copies the data over. You aren't seeing a problem because WCF allocates its own array for the response body and writes to the stream in a single write. This way the MemoryStream can do a single allocation, copy over nothing (as it starts empty) and you're not taking a hit. But for some applications you might have some performance problems with the copy on grow. If you know the upper limit on response size (ie you know it will always be no more than 2MB), you can pool byte arrays and use the constructor on MemoryStream where you provide the byte array. You also pass exposable as true, and you can pool the byte array by calling GetBuffer (or use the reference from the ArraySegment returned from TryGetBuffer). So you would pool the underlying buffers and not the MemoryStream objects. The only downside to that is the MemoryStream can't hold any more than the size of the buffer as it can't grow when you provide the buffer.

**Comment by mconnew** [comment]
I'm going to close this issue as I believe you have a working solution now.
