### ISSUE TITLE
Exception thrown in UserNameValidator using CustomBinding returns CommunicationException

### ISSUE THREAD

**Issue by jeanrp** [CoreWCF/CoreWCF#1070]
When trying to throw a MessageSecurityException or FaultException in the Server in a CustomUserNameValidator with CustomBinding and HttpsTransport set on it,  the client is receiving a CommunicationException with the following message: "The underlying connection was closed: The connection was closed unexpectedly."

The minimal reproducible example is here: https://github.com/jeanrp/CoreWCF-MRE-FaultException

Remote Stack Trace: 

```
Server stack trace: 
   at System.ServiceModel.Channels.HttpChannelUtilities.ProcessGetResponseWebException(WebException webException, HttpWebRequest request, HttpAbortReason abortReason)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.SecurityChannelFactory`1.SecurityRequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
```

**Comment by mconnew** [comment]
What's the urgency on this fix? Can you wait a month for release? Once it's merged, there will be a build with this available in the dev nuget feed. Would you be able to use that until the next servicing release?

**Comment by jeanrp** [comment]
We got a workaround for now. We basically created an AuthenticationService and we're returning true/false from there and then we do subsequent requests after that request. It shouldn't be very urgent. We were basically returning the exception in the UserNameValidator when the authentication failed and catching in the client with WCF. The workaround should work fine for now. Thanks for looking into it.
