### ISSUE TITLE
cross framework service and client

### ISSUE THREAD

**Issue by ssmsam12345** [CoreWCF/CoreWCF#1079]
We have existing WCF service project and WPF client project both targeting .NET Framework 4.7.1. We have a dll project that has common classes, DTOs, Interfaces and other functionalities shared across both client and service and is being referred by both.

We are trying to migrate WCF Service to CoreWCF. 
1. I have migrated the common dll project to netstandard2.0 
2. referring this by WPF client and CoreWCF Service
3. I am getting below exception when i try to create ChannelFactory at client side.
**System.InvalidOperationException: Attempted to get contract type for IBackendAdministrationService, but that type is not a ServiceContract, nor does it inherit a ServiceContract.
   at System.ServiceModel.Description.ServiceReflector.GetContractTypeAndAttribute(Type interfaceType, ServiceContractAttribute& contractAttribute)**

So, I tried to bring it down to sample examples just to make sure it works. I downloaded samples from CoreWCF repo (net core server)
and created a test .net framework client and getting the similar exception :  

System.InvalidOperationException
  HResult=0x80131509
  Message=Attempted to get contract type for IService, but that type is not a ServiceContract, nor does it inherit a ServiceContract.
  Source=System.Private.ServiceModel
  StackTrace:
   at System.ServiceModel.Description.ServiceReflector.GetContractTypeAndAttribute(Type interfaceType, ServiceContractAttribute& contractAttribute)
   at System.ServiceModel.Description.TypeLoader.LoadContractDescriptionHelper(Type contractType, Type serviceType, Object serviceImplementation)
   at System.ServiceModel.ChannelFactory`1.CreateDescription()
   at System.ServiceModel.ChannelFactory.InitializeEndpoint(Binding binding, EndpointAddress address)
   at System.ServiceModel.ChannelFactory`1..ctor(Binding binding, EndpointAddress remoteAddress)

So, My question is, Can we just port the existing wcf service to coreWCF and still let the customers (existing wpf client) to access the CoreWCF service? 

We are using 

<basicHttpBinding>
        <binding ...... transferMode="Streamed">
          <readerQuotas ..... />
          <security mode="TransportWithMessageCredential">
            <message clientCredentialType="UserName" />
          </security>
        </binding>
      </basicHttpBinding>

**Comment by g7ed6e** [comment]
@ssmsam12345 I guess you took a dependency to CoreWCF in the common project which lead to client side code complaining. CoreWCF does support having service and DTO decorated with ServiceContract and DataContract attributes from System.ServiceModel namespace too. Can you try to install System.ServiceModel.Primitives nuget package in the common assembly ?

**Comment by ssmsam12345** [comment]
Hi @g7ed6e 
Yes you are right. I was using CoreWCF.Primitives nuget package in the common dll.

Great!!!! I am here reading your comment after watching the video **https://youtu.be/dom2O19fGAo?t=566** . 
Now I got the sample projects working. 

Service project (.NET6.0) **-->** netstandard2.0 common dll (contracts, DTO, etc) **<--** Client Project (.net framework 4.8)


Now ,coming on to our existing WCF project, the common dll project also has database layer and also user authentication (Entitiy Framework 6). Now, if I migrate this common dll to netstandard2.0, which does not support EF6 but EFCore (I will loose membership, profile and  user authentication which was i EF6).

How to go handle this?

Do I also need to install System.ServiceModel.Primitives nuget package in the client project? 
So, all the customers using existing client application, will be affected if I migrate WCF service to CoreWCF ?

**Comment by g7ed6e** [comment]
> Hi @g7ed6e Yes you are right. I was using CoreWCF.Primitives nuget package in the common dll.
> 
> Great!!!! I am here reading your comment after watching the video **https://youtu.be/dom2O19fGAo?t=566** . Now I got the sample projects working.
> 
> Service project (.NET6.0) **-->** netstandard2.0 common dll (contracts, DTO, etc) **<--** Client Project (.net framework 4.8)
> 

Great to hear that!

> Now ,coming on to our existing WCF project, the common dll project also has database layer and also user authentication (Entitiy Framework 6). Now, if I migrate this common dll to netstandard2.0, which does not support EF6 but EFCore (I will loose membership, profile and user authentication which was i EF6).
> 
> How to go handle this?

From my experience that's possible to migrate from Microsoft.AspNet.Identity.Core + EF6 to Microsoft.Extensions.Identity.Core + EF Core, but this topic is out of the scope of this repo.

> 
> Do I also need to install System.ServiceModel.Primitives nuget package in the client project? So, all the customers using existing client application, will be affected if I migrate WCF service to CoreWCF ?

You should not need to install System.ServiceModel.Primitives nuget package in .NET framework client side projects.

**Comment by ssmsam12345** [comment]
Hi @g7ed6e again
I have WebInvokeAttribute as well in the common dll, for which System.ServiceModel.Primitives is not sufficient. Is there any other nuget package available for this?

**Comment by g7ed6e** [comment]
@ssmsam12345 are you using HttpClient to make the client side WebInvoke call ?

**Comment by ssmsam12345** [comment]
hi @g7ed6e 
apologies for the late response.

var httpWebRequest = (HttpWebRequest)WebRequest.Create(requestUriString + restApiAddress);
            httpWebRequest.ContentType = "application/json";
            httpWebRequest.Method = "POST";

we are creating POST WebRequests.

**Comment by g7ed6e** [comment]
@ssmsam12345 As the client side code is not using the service contract decorated with WebInvoke, you should be able to install CoreWCF.WebHttp nuget packages in the common project too and decorate the operation with `CoreWCF.Web.WebInvokeAttribute`.

**Comment by ssmsam12345** [comment]
@g7ed6e ahh!!! yes you are right, great. thanks for making that so easy!!!

Can you please throw some light on how to reuse the same web,config contents in CoreWCF. i just now installed CoreWCF.ConfigurationManager nuget package and not able get the usage or documentation

**Comment by g7ed6e** [comment]
@ssmsam12345 CoreWCF.ConfigurationManager does not support all that was available with WCF. Thus you should git it a try a identify missing feature if any.
Another approach is to migrate your configuration file to code.
