### ISSUE TITLE
Addressing Version WSAddressingAugust2004 is not supported

### ISSUE THREAD

**Issue by ioda** [CoreWCF/CoreWCF#1096]
Hi

When I use this binding setting, I got en error is not supported

An ExceptionDetail, likely created by IncludeExceptionDetailInFaults=true, whose value is:
System.InvalidOperationException: An exception was thrown in a call to a WSDL export extension: CoreWCF.Channels.HttpsTransportBindingElement\r\n Endpoint: https://localhost:44380/T1/TransmettreMandatRep2019.svc ----> System.ArgumentException: Addressing Version 'Addressing200408 (http://schemas.xmlsoap.org/ws/2004/08/addressing)' is not supported. (Parameter 'addressingVersion')
   at CoreWCF.EndpointAddress.WriteContentsTo(AddressingVersion addressingVersion, XmlDictionaryWriter writer)
   at CoreWCF.EndpointAddress.WriteTo(AddressingVersion addressingVersion, XmlDictionaryWriter writer, XmlDictionaryString localName, XmlDictionaryString ns)
   at CoreWCF.EndpointAddress.WriteTo(AddressingVersion addressingVersion, XmlWriter writer)
   at CoreWCF.Description.WsdlExporter.WSAddressingHelper.AddAddressToWsdlPort(Port wsdlPort, EndpointAddress addr, AddressingVersion addressing)
   at CoreWCF.Channels.TransportBindingElement.ExportWsdlEndpoint(WsdlExporter exporter, WsdlEndpointConversionContext endpointContext, String wsdlTransportUri, EndpointAddress address, AddressingVersion addressingVersion)
   at CoreWCF.Channels.HttpTransportBindingElement.CoreWCF.Description.IWsdlExportExtension.ExportEndpoint(WsdlExporter exporter, WsdlEndpointConversionContext endpointContext)
   at CoreWCF.Description.WsdlExporter.CallExtension(WsdlEndpointConversionContext endpointContext, IWsdlExportExtension extension)
   --- End of inner ExceptionDetail stack trace ---
   at CoreWCF.Description.WsdlExporter.CallExtension(WsdlEndpointConversionContext endpointContext, IWsdlExportExtension extension)
   at CoreWCF.Description.WsdlExporter.CallExportEndpoint(WsdlEndpointConversionContext endpointContext)
   at CoreWCF.Description.WsdlExporter.ExportEndpoint(ServiceEndpoint endpoint, XmlQualifiedName wsdlServiceQName, BindingParameterCollection bindingParameters)
   at CoreWCF.Description.WsdlExporter.ExportEndpoints(IEnumerable`1 endpoints, XmlQualifiedName wsdlServiceQName, BindingParameterCollection bindingParameters)
   at CoreWCF.Description.ServiceMetadataBehavior.MetadataExtensionInitializer.GenerateMetadata()
   at CoreWCF.Description.ServiceMetadataExtension.EnsureInitialized()
   at CoreWCF.Description.ServiceMetadataExtension.get_Metadata()
   at CoreWCF.Description.ServiceMetadataExtension.HttpGetImpl.InitializationData.InitializeFrom(ServiceMetadataExtension extension)
   at CoreWCF.Description.ServiceMetadataExtension.HttpGetImpl.GetInitData()
   at CoreWCF.Description.ServiceMetadataExtension.HttpGetImpl.TryHandleDocumentationRequestAsync(HttpContext requestContext)
   at CoreWCF.Description.ServiceMetadataExtension.HttpGetImpl.ProcessHttpRequest(HttpContext requestContext)
   at CoreWCF.Description.ServiceMetadataExtension.HttpGetImpl.HandleRequest(HttpContext httpContext)

`
static Binding GetBindingConfiguration()
{
    var textBindingElement = new TextMessageEncodingBindingElement()
    {
        MessageVersion = MessageVersion.CreateVersion(EnvelopeVersion.Soap12, AddressingVersion.WSAddressingAugust2004)
    };

    var httpsBindingElement = new HttpsTransportBindingElement()
    {

        MaxReceivedMessageSize = int.MaxValue,
        RequireClientCertificate = true
    };

    return new CustomBinding(textBindingElement, httpsBindingElement);
}
`

Did I do something wrong or if it really not supported ?

**Comment by mconnew** [comment]
It looks like there's some code missing. The missing code is [here](https://github.com/microsoft/referencesource/blob/master/System.ServiceModel/System/ServiceModel/EndpointAddress.cs#L1022-L1025) and [here](https://github.com/microsoft/referencesource/blob/master/System.ServiceModel/System/ServiceModel/EndpointAddress.cs#L1042-L1112). This was missed as some of the code was copied over from the WCF Client code rather than reference source, and originally the WCF Client didn't support this addressing mode.  

This problem is only with the WSDL generation, there shouldn't be any problem with running of the service. Would you be able to submit a PR with a fix and a unit test? The unit test can simply be creating an EndpointAddress for a dummy url, constructing an XmlDictionaryWriter which writes to a MemoryStream, then calling WriteContentsTo with the AddressingVersion. You can then get the byte array from the MemoryStream and using Encoding.UTF8.GetString to get the string, and then Assert that the string is what's expected.
