### ISSUE TITLE
IWebHostBuilder UseNetTcp is failing to resolve IFramingConnectionHandshakeBuilder

### ISSUE THREAD

**Issue by jobyjcteoco** [CoreWCF/CoreWCF#1102]
When used in conjunction with 'IWebHostBuilder UseUnityServiceProvider(this IWebHostBuilder hostBuilder, IUnityContainer container = null)'  by passing 'container', UseNetTcp is failing with following exception:

Application startup exception: Unity.ResolutionFailedException: Exception has been thrown by the target of an invocation.
_____________________________________________________
Exception occurred while:
   on constructor:  KestrelServerImpl(IOptions`1 options, IEnumerable`1 transportFactories, IEnumerable`1 multiplexedFactories, ILoggerFactory loggerFactory, DiagnosticSource diagnosticSource)

 while resolving:  KestrelServerImpl

_____________________________________________________
Exception occurred while:

 while resolving:  IServer

 ---> Unity.ResolutionFailedException: Exception has been thrown by the target of an invocation.
_____________________________________________________
Exception occurred while:
   on constructor:  KestrelServerImpl(IOptions`1 options, IEnumerable`1 transportFactories, IEnumerable`1 multiplexedFactories, ILoggerFactory loggerFactory, DiagnosticSource diagnosticSource)

 while resolving:  KestrelServerImpl

 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Unable to resolve service for type 'CoreWCF.Configuration.IFramingConnectionHandshakeBuilder' while attempting to activate 'CoreWCF.Channels.Framing.NetMessageFramingConnectionHandler'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetServiceOrCreateInstance[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Connections.ConnectionBuilderExtensions.UseConnectionHandler[TConnectionHandler](IConnectionBuilder connectionBuilder)
   at CoreWCF.Configuration.NetTcpFramingOptionsSetup.<Configure>b__7_0(ListenOptions builder)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions.Listen(EndPoint endPoint, Action`1 configure)
   at CoreWCF.Configuration.NetTcpFramingOptionsSetup.Configure(KestrelServerOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.CreateServiceContext(IOptions`1 options, ILoggerFactory loggerFactory, DiagnosticSource diagnosticSource)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl..ctor(IOptions`1 options, IEnumerable`1 transportFactories, IEnumerable`1 multiplexedFactories, ILoggerFactory loggerFactory, DiagnosticSource diagnosticSource)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Unity.Processors.ConstructorDiagnostic.<>c__DisplayClass14_0.<GetResolverDelegate>b__0(BuilderContext& c)
   at Unity.Processors.MemberProcessor`2.<>c__DisplayClass8_0.<GetResolver>b__0(BuilderContext& c)
   at Unity.Processors.MemberProcessor`2.<>c__DisplayClass8_0.<GetResolver>b__0(BuilderContext& c)
   at Unity.Processors.MemberProcessor`2.<>c__DisplayClass8_0.<GetResolver>b__0(BuilderContext& c)
   at Unity.Strategies.BuildPlanStrategy.PreBuildUp(BuilderContext& context)
   at Unity.UnityContainer.ExecuteValidatingPlan(BuilderContext& context)
   --- End of inner exception stack trace ---
   at Unity.UnityContainer.ExecuteValidatingPlan(BuilderContext& context)
   at Unity.UnityContainer.Unity.IUnityContainer.Resolve(Type type, String name, ResolverOverride[] overrides)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at CoreWCF.Configuration.ServiceModelServiceCollectionExtensions.<>c__DisplayClass1_0.<AddServiceModelServices>b__4(IServiceProvider provider)
   at Unity.Strategies.BuildPlanStrategy.PreBuildUp(BuilderContext& context)
   at Unity.UnityContainer.ExecuteValidatingPlan(BuilderContext& context)
   --- End of inner exception stack trace ---
   at Unity.UnityContainer.ExecuteValidatingPlan(BuilderContext& context)
   at Unity.UnityContainer.Unity.IUnityContainer.Resolve(Type type, String name, ResolverOverride[] overrides)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureServer()
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()

**Comment by jobyjcteoco** [comment]
Forgot to mention that we are using the latest available versions of the packages:
CoreWCF.Primitives, Version="1.3.2"
CoreWCF.ConfigurationManager, Version="1.3.2"
CoreWCF.NetTcp, Version="1.3.2"
Unity.Microsoft.DependencyInjection, Version=5.11.5

and the exception is getting logged while calling 'RunAsync();' on the created IWebHost.

**Comment by mconnew** [comment]
I don't understand how this is possible. My initial thought was that you forgot to call `UseNetTcp`, but that's not possible as that's what adds `NetTcpFramingOptionsSetup` to DI and that's clearly in the exception stack. Can you provide a minimal repro? It looks like something weird might be happening with the DI container, are you using a non-standard DI container or doing something in your own code to modify the `IServiceCollection` in some way?
