### ISSUE TITLE
CommunicationObject swallows exceptions, no way to change this behavior

### ISSUE THREAD

**Issue by podprad** [CoreWCF/CoreWCF#1139]
When there are some issues in the data contract, then there is no way to get the exception details without using debugger.

Example project:
https://github.com/podprad/misc_public/tree/main/playgrounds/csharp/CoreWcfIssues/ExceptionSwallowing

I made a mistake in MyClassLibrary.MyRequest. The setter for property Input is missing.

Internally a following exception is thrown:

```
System.Runtime.Serialization.InvalidDataContractException: No set method for property 'Input' in type 'MyClassLibrary.MyRequest'.
   at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.ThrowInvalidDataContractException(String message, Type type)
   at System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.ImportDataMembers()
   at System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper..ctor(Type type)
   at System.Runtime.Serialization.ClassDataContract..ctor(Type type)
   at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.CreateDataContract(Type type)
   at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.CreateDataContract(Int32 id, RuntimeTypeHandle typeHandle, Type type)
   at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.GetDataContractSkipValidation(Int32 id, RuntimeTypeHandle typeHandle, Type type)
   at System.Runtime.Serialization.DataContract.GetDataContract(RuntimeTypeHandle typeHandle, Type type, SerializationMode mode)
   at System.Runtime.Serialization.DataContract.GetDataContract(Type type)
   at lambda_method12(Closure , Type )
   at CoreWCF.Runtime.Serialization.DataContractEx.<>c__DisplayClass62_0.<GetDataContractStub>b__0(Type type)
   at CoreWCF.Runtime.Serialization.DataContractEx.GetDataContractStub(Type clrType)
   at CoreWCF.Runtime.Serialization.XsdDataContractExporterEx.GetSchemaTypeName(Type type)
   at CoreWCF.Runtime.Serialization.XsdDataContractExporterExWrapper.GetSchemaTypeName(Type type)
   at CoreWCF.Dispatcher.DataContractSerializerOperationFormatter.ValidateDataContractType(Type type)
   at CoreWCF.Dispatcher.DataContractSerializerOperationFormatter..ctor(OperationDescription description, DataContractFormatAttribute dataContractFormatAttribute, DataContractSerializerOperationBehavior serializerFactory)
   at CoreWCF.Description.DataContractSerializerOperationBehavior.GetFormatter(OperationDescription operation, Boolean& formatRequest, Boolean& formatReply, Boolean isProxy)
   at CoreWCF.Description.DataContractSerializerOperationBehavior.CoreWCF.Description.IOperationBehavior.ApplyDispatchBehavior(OperationDescription description, DispatchOperation dispatch)
   at CoreWCF.Description.DispatcherBuilder.BindOperations(ContractDescription contract, ClientRuntime proxy, DispatchRuntime dispatch)
   at CoreWCF.Description.DispatcherBuilder.InitializeServiceHost(ServiceHostBase serviceHost, IServiceProvider services)
   at CoreWCF.Description.DispatcherBuilder.BuildDispatcher[TService](ServiceConfiguration`1 serviceConfig, IServiceProvider services)
   at CoreWCF.Configuration.ServiceConfiguration`1.GetDispatchers()
   at CoreWCF.Configuration.DispatcherBuilderImpl.BuildDispatchers(Type serviceType)
   at CoreWCF.Channels.ServiceModelHttpMiddleware.BuildBranch()
   at CoreWCF.Channels.ServiceModelHttpMiddleware.EnsureBranchBuilt()
   at CoreWCF.Channels.ServiceModelHttpMiddleware.ServiceBuilderOpenedCallback(Object sender, EventArgs e)
   at CoreWCF.Channels.CommunicationObject.OnOpened()
```

The exception is caught here (decompiled code):
```
// CoreWCF.Configuration.ServiceBuilder
// public abstract class CommunicationObject : ICommunicationObject
protected virtual void OnFaulted()
    {
      lock (this.ThisLock)
      {
        if (this._raisedFaulted)
          return;
        this._raisedFaulted = true;
      }
      EventHandler faulted = this.Faulted;
      if (faulted == null)
        return;
      try
      {
        faulted(this.EventSender, EventArgs.Empty);
      }
      catch (Exception ex)
      {
        if (!Fx.IsFatal(ex))
          throw DiagnosticUtility.ExceptionUtility.ThrowHelperCallback(ex);
        throw;
      }
    }
	
// public abstract class CommunicationObject : ICommunicationObjec
public async Task OpenAsync(CancellationToken token)
    {
      CommunicationObject source = this;
      token.ThrowIfCancellationRequested();
      lock (source.ThisLock)
      {
        source.ThrowIfDisposedOrImmutable();
        source.State = CommunicationState.Opening;
      }
      bool throwing = true;
      try
      {
        source.OnOpening();
        if (!source._onOpeningCalled)
          throw TraceUtility.ThrowHelperError(source.CreateBaseClassMethodNotCalledException("OnOpening"), Guid.Empty, (object) source);
        await source.OnOpenAsync(token);
        source.OnOpened();
        if (!source._onOpenedCalled)
          throw TraceUtility.ThrowHelperError(source.CreateBaseClassMethodNotCalledException("OnOpened"), Guid.Empty, (object) source);
        throwing = false;
      }
      finally
      {
        if (throwing)
          source.Fault();
      }
    }
```

In OpenAsync the source.Fault() is called without exception details.
So I can get my code called in case of error, however there is no way to get the exception details.

```

 app.UseServiceModel(b =>
            {                
                b.Faulted += (sender, eventArgs) =>
                {
                    // This one is called, however we don't get any Exception details.
                };
            });
```

**Comment by mconnew** [comment]
We have some ridiculously convoluted code which is intended to make exceptions thrown at startup be bubbled all the way up to the app.RunAsync/app.StartAsync call as by default things get swallowed. The intention is that is WCF using ServiceHost.Open were to throw an exception, then app.RunAsync should throw that exception. Can you confirm that WCF in .NET Framework exposes this exception when you Open the ServiceHost?

**Comment by mconnew** [comment]
You can probably capture a stack trace in the Faulted callback to find out where the problem happened. Just instantiate a new StackTrace and call ToString on it and you will get the callback.
