### ISSUE TITLE
Cannot register WsHttp binding and Web http binding on the same base URL

### ISSUE THREAD

**Issue by podprad** [CoreWCF/CoreWCF#1142]
In my application I have following configuration:

base URL: http://localhost:58232/MyService.svc
wsHttpBinding URL: http://localhost:58232/MyService.svc
webHttpBinding URL: http://localhost:58232/MyService.svc/json

When wsHttpBinding is enabled, then /json endpoint does not work. I'm getting following error when calling /json endpoint:
```
An unhandled exception has occurred while executing the request.
      CoreWCF.ProtocolException: Content Type application/json was sent to a service expecting application/soap+xml; charset=utf-8.  The client and service bindings may be mismatched.
         at CoreWCF.Channels.HttpInput.ThrowHttpProtocolException(String message, HttpStatusCode statusCode, String statusDescription) in D:\Dev\CoreWCF\src\CoreWCF.Http\src\CoreWCF\Channels\HttpChannelHelpers.cs:line 445
         at CoreWCF.Channels.HttpInput.ValidateContentType() in D:\Dev\CoreWCF\src\CoreWCF.Http\src\CoreWCF\Channels\HttpChannelHelpers.cs:line 382
         at CoreWCF.Channels.HttpInput.ParseIncomingMessageAsync() in D:\Dev\CoreWCF\src\CoreWCF.Http\src\CoreWCF\Channels\HttpChannelHelpers.cs:line 393
         at CoreWCF.Channels.AspNetCoreReplyChannel.HandleRequest(HttpContext context) in D:\Dev\CoreWCF\src\CoreWCF.Http\src\CoreWCF\Channels\AspNetCoreReplyChannel.cs:line 117
         at CoreWCF.Channels.RequestDelegateHandler.HandleRequest(HttpContext context) in D:\Dev\CoreWCF\src\CoreWCF.Http\src\CoreWCF\Channels\RequestDelegateHandler.cs:line 125
         at CoreWCF.Channels.ServiceModelHttpMiddleware.InvokeAsync(HttpContext context) in D:\Dev\CoreWCF\src\CoreWCF.Http\src\CoreWCF\Channels\ServiceModelHttpMiddleware.cs:line 49
         at CoreWCF.Channels.MetadataMiddleware.InvokeAsync(HttpContext context) in D:\Dev\CoreWCF\src\CoreWCF.Primitives\src\CoreWCF\Channels\MetadataMiddleware.cs:line 53
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

It seems that wsHttpBinding middleware tries to handle /json endpoint.

Is that an issue or rather thing caused by CoreWCF design? Such URL configuration works fine with legacy ServiceModel WCF.

Example code:
https://github.com/podprad/misc_public/blob/main/playgrounds/csharp/CoreWcfIssues/SameBaseUrl/SameBaseUrl/Program.cs

```
public static void Main(string[] args)
        {
            var builder = WebApplication.CreateBuilder(args);

            builder.Services.AddTransient(typeof(MyService), s => new MyService());

            builder.Services.AddServiceModelServices()
                .AddServiceModelMetadata()
                .AddServiceModelWebServices()
                .AddSingleton<IServiceBehavior, UseRequestHeadersForMetadataAddressBehavior>();

            var app = builder.Build();

            app.UseServiceModel(b =>
            {
                b.AddService(typeof(MyService), serviceOptions =>
                {
                    serviceOptions.BaseAddresses.Add(new Uri("http://localhost:58232/MyService.svc"));
                });

                b.ConfigureServiceHostBase(typeof(MyService), serviceHostBase =>
                {
                    var serviceMetadataBehavior = new ServiceMetadataBehavior
                    {
                        HttpGetEnabled = true,
                    };

                    serviceHostBase.Description.Behaviors.Remove<ServiceMetadataBehavior>();
                    serviceHostBase.Description.Behaviors.Add(serviceMetadataBehavior);

                    serviceHostBase.Faulted += OnUnexpectedError;
                });

                var binding = new WSHttpBinding(SecurityMode.None);

                // This works fine.
                // b.AddServiceEndpoint<MyService, IMyService>(binding, "/wsHttp");

                // This makes /json does not work.
                // b.AddServiceEndpoint<MyService, IMyService>(binding, "/");

                // curl -i -X POST http://localhost:58232/MyService.svc/json/ExecuteDynamic -d "{}" --insecure
                var webBinding = new WebHttpBinding(WebHttpSecurityMode.None);
                b.AddServiceWebEndpoint<MyService, IMyService>(webBinding, "/json");

                b.Faulted += OnUnexpectedError;
            });

            app.Run();
        }
```

**Comment by mconnew** [comment]
Switch the order of the AddServiceWebEndpoint and AddServiceEndpoint as it currently functions as first match wins.

**Comment by mconnew** [comment]
Closing as I believe this fixes the issue, reopen if it doesn't.
