### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by alex-lapuka** [CoreWCF/CoreWCF#1234]
### Duplicate ?

- [X] I have searched issues/discussions and did not find other issues/discussions reporting this bug.

### Product version

1.4.1

### Describe expected behavior

CoreWCF should support the Windows host names that start with '-' symbol (like "-WIN-123")

### Describe actual behavior

There's a crash happens if the Windows host name starts with the '-' symbol.

### Which binding

NetTcp

### security

Transport

### Which .NET version

.NET 6

### Which os platform

Windows

### Stacktrace if any

```shell
System.UriFormatException: Invalid URI: The hostname could not be parsed.
at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
at System.Uri..ctor(String uriString)
at System.UriBuilder.get_Uri()
at CoreWCF.Channels.Binding.BuildServiceDispatcher[TChannel](BindingParameterCollection parameters, IServiceDispatcher dispatcher)
at CoreWCF.Channels.Framing.NetMessageFramingConnectionHandler.BuildAddressTable(IServiceProvider services)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
at CoreWCF.Channels.Framing.NetMessageFramingConnectionHandler.OnServiceBuilderOpened(Object sender, EventArgs e)
at CoreWCF.Channels.CommunicationObject.OnOpened()
--- End of stack trace from previous location ---
at CoreWCF.Configuration.WrappingIServer.StartAsync[TContext](IHttpApplication1 application, CancellationToken cancellationToken)    at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)    at Microsoft.AspNetCore.Hosting.Internal.WebHost.Start()    at Twingate.Client.WinService.Service.<StartServiceHostWithRetry>b__11_0()    at Twingate.Client.Common.Retry.RetryExecutor.RetryInternal(Action logic, Boolean trowException)    at Twingate.Client.Common.Retry.RetryExecutor.Retry(Action logic)    at Twingate.Client.WinService.Service.StartServiceHostWithRetry()    at Twingate.Client.WinService.Service.OnStart(String[] args) [2023-09-20T15:07:42.892734-08:00] [FATAL] [client] Got the unhandled exception [Program.CurrentDomain_UnhandledException] System.UriFormatException: Invalid URI: The hostname could not be parsed.    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)    at System.Uri..ctor(String uriString)    at System.UriBuilder.get_Uri()    at CoreWCF.Channels.Binding.BuildServiceDispatcher[TChannel](BindingParameterCollection parameters, IServiceDispatcher dispatcher)    at CoreWCF.Channels.Framing.NetMessageFramingConnectionHandler.BuildAddressTable(IServiceProvider services)    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)    at CoreWCF.Channels.Framing.NetMessageFramingConnectionHandler.OnServiceBuilderOpened(Object sender, EventArgs e)    at CoreWCF.Channels.CommunicationObject.OnOpened() --- End of stack trace from previous location ---    at CoreWCF.Configuration.WrappingIServer.StartAsync[TContext](IHttpApplication1 application, CancellationToken cancellationToken)
at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
at Microsoft.AspNetCore.Hosting.Internal.WebHost.Start()
```

**Comment by mconnew** [comment]
Does this work with WCF in .NET Framework? Don't worry about the hostname, use localhost as CoreWCF routes based on the path alone.

**Comment by alex-lapuka** [comment]
@mconnew yes, that works with .NET framework
We don't use the hostname anywhere at our app and don't pass it to the CoreWCF code. I assume that it is resolved and used within just the CoreWCF code.

**Comment by mconnew** [comment]
I tracked down the code which is causing this problem. It's an odd one. We use Dns.GetHostEntry(string.Empty) to discover the hostname of the local machine. We then use that to form the listen address which is a Uri. So apparently the `System.Net.Dns` class is able to return host names which aren't valid DNS hostnames, which is counter to its documentation. The best short term fix I can think of is wrap the Uri creation with a try/catch to catch the UriFormatException and try again using localhost if the hostname doesn't work.  

This doesn't fix things generally though as we use the hostname returned by Dns.GetHostEntry in multiple places. The reason we use Dns.GetHostEntry is to make sure that any wsdl has the correct hostname in it by default without having to do any fixup. We don't currently support the Mex endpoint, but it's on my long todo list, so once that has been implemented, having the correct hostname becomes more important. We have the ability to fixup the WSDL addresses when there's an HTTP request for the WSDL as we know what hostname was used from the HTTP Host header, but we don't have the same capability with NetTcp.  

We also have a similar problem on other code paths. If the HTTP IServer is configured to use a loopback IP address as the hostname, then we also use Dns.GetHostEntry to get the hostname to configure the defaults for WSDL, again to prevent having to override anything. That code path will also fail.  

Another place this will fail is when using * as the hostname, e.g. http://*/PathToService. In that case we do the same thing.  

I'm curious, if you host a simple hello world http site in asp.net core, or even IIS, and you use a web browser to navigate to http://-WIN-123/helloworld (or whatever the url is), what does the browser do? Does it accept it?  

I'm going to open an issue in the dotnet/runtime repo to see what they have to say about Dns.GetHostEntry not returning a valid DNS hostname. I suspect their answer will be that they are just calling an OS api and passing the result back, but it's worth a try. We have the same code in .NET Framework, but it's only hit in a few scenarios, most of which aren't supported in CoreWCF (such as composite duplex channels). I want to work out how WCF finds the hostname under normal circumstances before I commit to a permanent change, and also want to hear what the runtime team says.

**Comment by mconnew** [comment]
I opened [this issue](https://github.com/dotnet/runtime/issues/94195) in dotnet/runtime.

**Comment by mconnew** [comment]
@alex-lapuka, how are you hosting in WCF? Is it self hosted or IIS hosted? If self hosted, what are you passing to ServiceHost for the base addresses? Are you using a WSDL to generate a client at all? The problem I realized is that to create a ChannelFactory, you need to pass a Uri, and that Uri will have the invalid DNS name too. If you were doing communication from another machine, even making CoreWCF work with an invalid DNS name wouldn't enable cross machine communication. This suggests to me that falling back to localhost is probably fine as you aren't going to be able to use the hostname from another host anyway.

**Comment by alex-lapuka** [comment]
@mconnew, sorry for the delay.
My app is the Windows service that runs the Kestrel server to host the WCF service. WCF is used for the IPC with the local user space applications. The URL for the endpoint is IP-based and I get it from `IPAddress.Loopback` constant. In my tests it is always equal to `127.0.0.1`.
My concern was specifically because that I don't use the host name at all, and the localhost address seems to be valid on any device.

**Comment by alex-lapuka** [comment]
At a time of the project migration both of them were not yet supported. The `NetNamedPipeBinding` seems to be a good solution, but it is still in beta. How soon can I expect it to be released?
Another issue with the `NetNamedPipeBinding` is that it is still dependent on AspNet libraries through the `CoreWCF.Primitives` dependency. Is there a chance to get rid of it?

**Comment by mconnew** [comment]
CoreWCF will always depend on aspnetcore because that's the hosting model it uses. When we eventually drop .NET Framework support, we should be able to use aspnetcore to handle owning the underlying named pipe.  
These are the known issues with NetNamedPipe:
* Currently forces you to have a listening HTTP endpoint
* When shutting down the service, it doesn't do a clean channel close so the clients will see a faulted channel instead of a closed channel
* WSDL support

It's simply a case that I haven't had the time yet to go back and finish those few things. Everything else I consider production quality code at this point.

**Comment by alex-lapuka** [comment]
Thank you for the clarification. I'm going to test the NetNamedPipeBinding with the current release, but I have to hold that code until the known issues are resolved and a release version is available.
Thank you for your efforts!
