### ISSUE TITLE
[Bug]: MetadataMiddleware.EnsureBranchBuilt is not reentrable

### ISSUE THREAD

**Issue by MaceWindu** [CoreWCF/CoreWCF#1257]
### Duplicate ?

- [X] I have searched issues/discussions and did not find other issues/discussions reporting this bug.

### Product version

1.4.1

### Describe expected behavior

When BuildBranch fails it doesn't discard built state but instead store it and reuse on next build attempts.

That hides original issues with build by producing misleading errors. E.g. DispatchBuilder.BuildDispatcher adds same endpoints on each build call and then fail in ServiceAuthorizationBehavior.Validate trying to create duplicate EndpointAuthorizationBehavior instances.

### Describe actual behavior

```
The value could not be added to the collection, as the collection already contains an item of the same type: ''CoreWCF.Description.EndpointAuthorizationBehavior''. This collection only supports one instance of each type. (Parameter ''item'')', Stack: '   at CoreWCF.Collections.Generic.KeyedByTypeCollection`1.InsertItem(Int32 index, TItem item) in CoreWCF-1.4.1\src\CoreWCF.Primitives\src\CoreWCF\Collections\Generic\KeyedByTypeCollection.cs:line 109

   at CoreWCF.Description.ServiceAuthorizationBehavior.CoreWCF.Description.IServiceBehavior.Validate(ServiceDescription serviceDescription, ServiceHostBase serviceHostBase) in CoreWCF-1.4.1\src\CoreWCF.Primitives\src\CoreWCF\Description\ServiceAuthorizationBehavior.cs:line 191

   at CoreWCF.Description.DispatcherBuilder.ValidateDescription(ServiceHostBase serviceHost) in CoreWCF-1.4.1\src\CoreWCF.Primitives\src\CoreWCF\Description\DispatcherBuilder.cs:line 34

   at CoreWCF.Description.DispatcherBuilder.InitializeServiceHost(ServiceHostBase serviceHost, IServiceProvider services) in CoreWCF-1.4.1\src\CoreWCF.Primitives\src\CoreWCF\Description\DispatcherBuilder.cs:line 158

   at CoreWCF.Description.DispatcherBuilder.BuildDispatcher[TService](ServiceConfiguration`1 serviceConfig, IServiceProvider services) in CoreWCF-1.4.1\src\CoreWCF.Primitives\src\CoreWCF\Description\DispatcherBuilder.cs:line 753

   at CoreWCF.Configuration.ServiceConfiguration`1.GetDispatchers() in CoreWCF-1.4.1\src\CoreWCF.Primitives\src\CoreWCF\Configuration\ServiceConfiguration.cs:line 41

   at CoreWCF.Configuration.DispatcherBuilderImpl.BuildDispatchers(Type serviceType) in CoreWCF-1.4.1\src\CoreWCF.Primitives\src\CoreWCF\Configuration\DispatcherBuilderImpl.cs:line 23

   at CoreWCF.Channels.MetadataMiddleware.BuildBranch() in CoreWCF-1.4.1\src\CoreWCF.Primitives\src\CoreWCF\Channels\MetadataMiddleware.cs:line 115

   at CoreWCF.Channels.MetadataMiddleware.EnsureBranchBuilt() in CoreWCF-1.4.1\src\CoreWCF.Primitives\src\CoreWCF\Channels\MetadataMiddleware.cs:line 68

   at CoreWCF.Channels.MetadataMiddleware.BuildBranchAndInvoke(HttpContext request) in CoreWCF-1.4.1\src\CoreWCF.Primitives\src\CoreWCF\Channels\MetadataMiddleware.cs:line 58

   at CoreWCF.Channels.MetadataMiddleware.InvokeAsync(HttpContext context) in C:\Download\CoreWCF-1.4.1\src\CoreWCF.Primitives\src\CoreWCF\Channels\MetadataMiddleware.cs:line 53

```

### Which binding

WebHttp

### security

Transport

### Which .NET version

.NET 7

### Which os platform

Windows

**Comment by ThomasMaij** [comment]
This same issue is still ongoing using .net 9 and CoreWCF 1.8.0. 

I've got a fairly new .net 9 web project with RestAPI (which uses authorize attributes), Hangfire Dashboard and now moving existing services from .net Framework 4.8 to this .net 9 project using CoreWCF. I was able to move all but one service. All services use BasicHttpBinding except one. It is using a WebHttpBinding and I try to add it using .AddServiceWebEndpoint.

It breaks the whole application with this `The value could not be added to the collection, as the collection already contains an item of the same type: ''CoreWCF.Description.EndpointAuthorizationBehavior''`

I do not intentionally add this behaviour neither would i like to use the new authorization schema's. I want my service to be backwards compatible with existing clients.

Is there any way to work around this issue? Is there some way to opt in/out of this behaviour?

**Comment by mconnew** [comment]
Ideally the failure should bubble up and cause the host StartAsync call to fail so you can address it. If that's not feasible, we should add a route to an error page that's similar to what gets output for WCF in .NET Framework. Do you have details about the original exception which caused the first failure? I'd like to try to duplicate it to work out why it's not failing the host start.

**Comment by a-tze** [comment]
Same issue for me now. 

I think I can give you a hint.

An exception is thrown on startup, preventing the "EnsureBranchBuilt()" methods from completing, therefore later triggering the duplicated adding of Behaviours.

The exception is:

System.InvalidOperationException: Unable to find the endpoint behavior WebHttpBehavior for endpoint address '/PingService'. This is possibly caused by not calling ServiceModelWebServiceCollectionExtensions.AddServiceModelWebServices(IServiceCollection services).
   at CoreWCF.Configuration.ServiceModelWebServiceBuilderExtensions.<>c__DisplayClass17_0.<AddServiceWebEndpoint>b__0(ServiceEndpoint serviceEndpoint) in ...\CoreWCF\src\CoreWCF.WebHttp\src\CoreWCF\Configuration\ServiceModelWebServiceBuilderExtensions.cs:line 233
   at CoreWCF.Configuration.EndpointConfiguratorEndpointBehavior.ApplyDispatchBehavior(ServiceEndpoint endpoint, EndpointDispatcher endpointDispatcher) in ...\CoreWCF\src\CoreWCF.Primitives\src\CoreWCF\Configuration\EndpointConfiguratorEndpointBehavior.cs:line 32
   at CoreWCF.Description.DispatcherBuilder.InitializeServiceHost(ServiceHostBase serviceHost, IServiceProvider services) in ...\CoreWCF\src\CoreWCF.Primitives\src\CoreWCF\Description\DispatcherBuilder.cs:line 277
   at CoreWCF.Description.DispatcherBuilder.BuildDispatcher[TService](ServiceConfiguration`1 serviceConfig, IServiceProvider services) in ...\CoreWCF\src\CoreWCF.Primitives\src\CoreWCF\Description\DispatcherBuilder.cs:line 758
   at CoreWCF.Configuration.ServiceConfiguration`1.GetDispatchers() in ...\CoreWCF\src\CoreWCF.Primitives\src\CoreWCF\Configuration\ServiceConfiguration.cs:line 41

(I'm debugging on tag 1.8.1)

This exception is caught here:

https://github.com/CoreWCF/CoreWCF/blob/v1.8.1/src/CoreWCF.Primitives/src/CoreWCF/Channels/CommunicationObject.cs#L505

and then discarded, because Fx.IsFatal returns false. So this needs to classify the exception as fatal to throw on startup and ideally also will output this very VERY helpful exception - now I know why my program did not work at all! Or use a dedicated Exception for this.
