### ISSUE TITLE
[Bug]: TCP not working within IIS

### ISSUE THREAD

**Issue by oskarjf** [CoreWCF/CoreWCF#1258]
### Duplicate ?

- [X] I have searched issues/discussions and did not find other issues/discussions reporting this bug.

### Product version

1.4.1

### Describe expected behavior

TCP should work on IIS.
HTTP works fine.

IIS version 10.x

Similar issue to [https://github.com/CoreWCF/CoreWCF/issues/1084](https://github.com/CoreWCF/CoreWCF/issues/1084)

### Describe actual behavior

System.ServiceModel.EndpointNotFoundException: The message could not be dispatched because the service at the endpoint address 'net.tcp://localhost/Integration/Services/CapabilityQueryService.svc' is unavailable for the protocol of the address.

### Which binding

NetTcp

### security

None

### Which .NET version

.NET 7

### Which os platform

Windows

### Code snippet used to reproduce the issue

```c#
var netTcpBinding = new NetTcpBinding()
{
    MaxReceivedMessageSize = 33554432,
    Security = new NetTcpSecurity() { Mode = SecurityMode.None },
    ReaderQuotas = new System.Xml.XmlDictionaryReaderQuotas() { MaxDepth = 100, MaxBytesPerRead = 209715200, MaxStringContentLength = 209715200, MaxArrayLength = 209715200 },
    Name = "netTCPBinding"
};

builder.AddService<CapabilityQueryService>((serviceOptions) =>
{
    serviceOptions.DebugBehavior.IncludeExceptionDetailInFaults = includeExceptionDetailInFaults;
    serviceOptions.BaseAddresses.Add(new Uri($"http://{myServerAndPort}/Integration/Services/CapabilityQueryService.svc"));
})
.AddServiceEndpoint<CapabilityQueryService, IQueryCapabilityDomain>(httpBinding, string.Empty)
.AddServiceEndpoint<CapabilityQueryService, IQueryCapabilityDomain>(netTcpBinding, $"net.tcp://{tcpServerAndPort}/Integration/Services/CapabilityQueryService.svc");
```

### Stacktrace if any

```shell
System.ServiceModel.Channels.ConnectionUpgradeHelper.DecodeFramingFault(ClientFramingDecoder decoder, IConnection connection, Uri via, String contentType, TimeoutHelper& timeoutHelper)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.SendPreamble(IConnection connection, ArraySegment`1 preamble, TimeoutHelper& timeoutHelper)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.DuplexConnectionPoolHelper.AcceptPooledConnection(IConnection connection, TimeoutHelper& timeoutHelper)
   at System.ServiceModel.Channels.ConnectionPoolHelper.EstablishConnection(TimeSpan timeout)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOpenOnce.System.ServiceModel.Channels.ServiceChannel.ICallOnce.Call(ServiceChannel channel, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOnceManager.CallOnce(TimeSpan timeout, CallOnceManager cascade)
   at System.ServiceModel.Channels.ServiceChannel.EnsureOpened(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
```

**Comment by oskarjf** [comment]
@mconnew 
I tought I had this solved but now I'm experiencing this again. Did you have any instructions on setting up CoreWCF with IIS?

**Comment by oskarjf** [comment]
Ok, got this working again by pointing my client to the TCP port number specified in my app and updating the Application Pool
