### ISSUE TITLE
[Bug]: CoreWCF 1.5.0-preview1 doesn't play nice with Microsoft.AspNetCore.SignalR.Client 6.0.x or vice-versa for NetNamedPipe

### ISSUE THREAD

**Issue by vvdb-architecture** [CoreWCF/CoreWCF#1261]
### Duplicate ?

- [X] I have searched issues/discussions and did not find other issues/discussions reporting this bug.

### Product version

1.5.0-preview1

### Describe expected behavior

I have a WPF application running a hosted service to listen to incoming NetPipe messages.
This isn't really hard to do using a custom hostbuilder to build a host service and then doing:

~~~csharp
            var hosts = services.GetServices<IHostedService>();
            // it is unlikely that we have more than one hosted service in a desktop application, but we don't take any chances
            bool started = false;
            foreach (var host in hosts)
                if (host.GetType().Name == "NetNamedPipeHostedService")
                {
                    // asynchronous call done synchronously: that's OK in this case, don't get your knickers in a twist!
                    host.StartAsync(CancellationToken.None).GetAwaiter().GetResult();
                    started = true;
                }
            // it is an anomaly if we didn't encounter any named pipe hosted services. Rather than do nothing, we raise an exception.
            if (!started)
                throw new ArgumentException("No net.pipe hosted service found.");
            var applicationLifetime = services.GetRequiredService<ApplicationLifetime>();
            applicationLifetime.NotifyStarted();
~~~

### Describe actual behavior

The above code works perfectly. However, as soon as I link SignalR:

~~~xml
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="6.0.14" />
~~~

The `StartAsync` in the above code fails with:

~~~
System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'Microsoft.AspNetCore.Http.Features.IFeatureCollection Microsoft.AspNetCore.Connections.ConnectionContext.get_Features()'.
  Source=CoreWCF.NetNamedPipe
  StackTrace:
   at CoreWCF.Channels.NamedPipeListener.<StartPumpAsync>d__20.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at CoreWCF.Channels.NamedPipeListener.StartPumpAsync(CancellationToken token)
   at CoreWCF.Channels.NamedPipeListener.StartAccepting()
   at CoreWCF.Channels.NamedPipeTransportManager.<BindAsync>d__4.MoveNext()
   at CoreWCF.Channels.NetNamedPipeHostedService.<StartAsync>d__4.MoveNext()
   at ...
~~~

I am aware of the [breaking change in .NET 6 regarding feature collections](https://learn.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/6.0/microsoft-aspnetcore-http-features-package-split) but everything is .NET 6/.NET 6-windows (except CoreWCF which is .NET Standard 2.0). 

But I tried adding several different NuGet packages, to no avail.

I'm also puzzled about the reason why linking to SignalR gives a problem. Putting the SignalR code in a separate assembly doesn't change anything. 

Remove SignalR, and all works well.

### Which binding

NetNamedPipe

### security

None

### Which .NET version

.NET 6

### Which os platform

Windows

### Code snippet used to reproduce the issue

```c#
See above
```

### Stacktrace if any

```shell
System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'Microsoft.AspNetCore.Http.Features.IFeatureCollection Microsoft.AspNetCore.Connections.ConnectionContext.get_Features()'.
  Source=CoreWCF.NetNamedPipe
  StackTrace:
   at CoreWCF.Channels.NamedPipeListener.<StartPumpAsync>d__20.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at CoreWCF.Channels.NamedPipeListener.StartPumpAsync(CancellationToken token)
   at CoreWCF.Channels.NamedPipeListener.StartAccepting()
   at CoreWCF.Channels.NamedPipeTransportManager.<BindAsync>d__4.MoveNext()
   at CoreWCF.Channels.NetNamedPipeHostedService.<StartAsync>d__4.MoveNext()
   at ...
```

**Comment by vvdb-architecture** [comment]
Answering my own question: You need to add the following in the `.csproj` file:

~~~xml
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
~~~

Make sure that your target framework is set to `net6.0` or `net6.0-windows` 

This will resolve the ambiguity.

Nothing needs to be changed in the CoreWCF assemblies, their definitions are fine.
