### ISSUE TITLE
UDS  throw expection won Linux machine

### ISSUE THREAD

**Issue by ZhaodongTian** [CoreWCF/CoreWCF#1313]
### Duplicate ?

- [X] I have searched issues/discussions and did not find other issues/discussions reporting this bug.

### Product version

1.5.1

### Describe expected behavior

**The service uses UnixDomainSocketBinding to host and run linux machine , will throw be exception:**

fail: Microsoft.AspNetCore.Server.Kestrel[0]
      Unhandled exception while processing 0HN01P4N0N1O4.
      Interop+NetSecurityNative+GssApiException: GSSAPI operation failed with error - Unspecified GSS failure.  Minor code may provide more information (Keytab FILE:/etc/krb5.keytab is nonexistent or empty).
         at Microsoft.Win32.SafeHandles.SafeGssCredHandle.CreateAcceptor()
         at System.Net.NegotiateAuthenticationPal.UnixNegotiateAuthenticationPal..ctor(NegotiateAuthenticationServerOptions serverOptions)
         at System.Net.NegotiateAuthenticationPal.Create(NegotiateAuthenticationServerOptions serverOptions)
         at System.Net.Security.NegotiateAuthentication..ctor(NegotiateAuthenticationServerOptions serverOptions)
         at System.Net.Security.NegotiateStream.ValidateCreateContext(String package, Boolean isServer, NetworkCredential credential, String servicePrincipalName, ChannelBinding channelBinding, ProtectionLevel protectionLevel, TokenImpersonationLevel impersonationLevel)
         at System.Net.Security.NegotiateStream.ValidateCreateContext(String package, NetworkCredential credential, String servicePrincipalName, ExtendedProtectionPolicy policy, ProtectionLevel protectionLevel, TokenImpersonationLevel impersonationLevel)
         at System.Net.Security.NegotiateStream.AuthenticateAsServerAsync(NetworkCredential credential, ExtendedProtectionPolicy policy, ProtectionLevel requiredProtectionLevel, TokenImpersonationLevel requiredImpersonationLevel)
         at CoreWCF.Channels.WindowsStreamSecurityUpgradeProvider.WindowsStreamSecurityUpgradeAcceptor.OnAcceptUpgradeAsync(Stream stream)
         at CoreWCF.Channels.StreamSecurityUpgradeAcceptorBase.AcceptUpgradeAsync(Stream stream)
         at CoreWCF.Channels.Framing.ServerFramingDuplexSessionMiddleware.UpgradeConnectionAsync(FramingConnection connection, String contentType)
         at CoreWCF.Channels.Framing.ServerFramingDuplexSessionMiddleware.OnConnectedAsync(FramingConnection connection)
         at CoreWCF.Channels.Framing.NetMessageFramingConnectionHandler.PerformServiceHandshake(IFramingConnectionHandshakeBuilder configuration, FramingConnection connection, HandshakeDelegate next)
         at CoreWCF.Channels.Framing.DuplexFramingMiddleware.OnConnectedAsync(FramingConnection connection)
         at CoreWCF.Configuration.MapMiddleware.Invoke(FramingConnection connection)
         at CoreWCF.Channels.Framing.FramingModeHandshakeMiddleware.OnConnectedCoreAsync(FramingConnection connection)
         at CoreWCF.Channels.Framing.FramingModeHandshakeMiddleware.OnConnectedAsync(FramingConnection connection)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection`1.ExecuteAsync()
Unhandled exception. System.ServiceModel.CommunicationException: A UDS error (32: Broken pipe) occurred while transmitting data.
---> System.Net.Sockets.SocketException (32): Broken pipe
   at System.ServiceModel.Channels.SocketConnection.WriteAsync(ReadOnlyMemory`1 buffer, Boolean immediate, TimeSpan timeout)
   --- End of inner exception stack trace ---
   at System.ServiceModel.Channels.SocketConnection.WriteAsync(ReadOnlyMemory`1 buffer, Boolean immediate, TimeSpan timeout)
   at System.ServiceModel.Channels.BufferedConnection.WriteNowAsync(ReadOnlyMemory`1 buffer, TimeSpan timeout)
   at System.Net.StreamFramer.WriteMessageAsync[TAdapter](Stream stream, Byte[] message, CancellationToken cancellationToken)
   at System.Net.Security.NegotiateStream.SendAuthResetSignalAndThrowAsync[TIOAdapter](Byte[] message, Exception exception, CancellationToken cancellationToken)
   at System.Net.Security.NegotiateStream.SendBlobAsync[TIOAdapter](Byte[] message, CancellationToken cancellationToken)
   at System.Net.Security.NegotiateStream.AuthenticateAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.ServiceModel.Channels.WindowsStreamSecurityUpgradeProvider.WindowsStreamSecurityUpgradeInitiator.OnInitiateUpgradeAsync(Stream stream)
   at System.ServiceModel.Channels.StreamSecurityUpgradeInitiatorBase.InitiateUpgradeAsync(Stream stream)
   at System.ServiceModel.Channels.ConnectionUpgradeHelper.InitiateUpgradeAsync(StreamUpgradeInitiator upgradeInitiator, IConnection connection, ClientFramingDecoder decoder, IDefaultCommunicationTimeouts defaultTimeouts, TimeSpan timeout)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.SendPreambleAsync(IConnection connection, Memory`1 preamble, TimeSpan timeout)
   at System.ServiceModel.Channels.ConnectionPoolHelper.EstablishConnectionAsync(TimeSpan timeout)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.OnOpenAsync(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.OnOpenAsyncInternal(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.System.ServiceModel.IAsyncCommunicationObject.OpenAsync(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.OnOpenAsync(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.OnOpenAsyncInternal(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.System.ServiceModel.IAsyncCommunicationObject.OpenAsync(TimeSpan timeout)
   at System.Runtime.TaskHelpers.WaitForCompletion(Task task)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open()
   at System.ServiceModel.Channels.ServiceChannelProxy.System.ServiceModel.ICommunicationObject.Open()
   at ConsoleApp4.Program.Main(String[] args) in E:\ConsoleApp4\ConsoleApp4\Program.cs:line 37
Aborted (core dumped)

**[ConsoleApp4.zip](https://github.com/CoreWCF/CoreWCF/files/13734436/ConsoleApp4.zip)**

**after i run the command  apt-get update && apt-get install -y gss-ntlmssp ,  the exception changed:**

info: Microsoft.Hosting.Lifetime[0]
      Content root path: /home/wcfcore/Downloads/linux-x64
Unhandled exception. System.ServiceModel.Security.SecurityNegotiationException: Authentication failed, see inner exception.
---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
---> System.ComponentModel.Win32Exception (0x80090304): Unknown error -2146893052
   --- End of inner exception stack trace ---
   at System.Net.Security.NegotiateStream.SendAuthResetSignalAndThrowAsync[TIOAdapter](Byte[] message, Exception exception, CancellationToken cancellationToken)
   at System.Net.Security.NegotiateStream.SendBlobAsync[TIOAdapter](Byte[] message, CancellationToken cancellationToken)
   at System.Net.Security.NegotiateStream.AuthenticateAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.ServiceModel.Channels.WindowsStreamSecurityUpgradeProvider.WindowsStreamSecurityUpgradeInitiator.OnInitiateUpgradeAsync(Stream stream)
   --- End of inner exception stack trace ---
   at System.ServiceModel.Channels.WindowsStreamSecurityUpgradeProvider.WindowsStreamSecurityUpgradeInitiator.OnInitiateUpgradeAsync(Stream stream)
   at System.ServiceModel.Channels.StreamSecurityUpgradeInitiatorBase.InitiateUpgradeAsync(Stream stream)
   at System.ServiceModel.Channels.ConnectionUpgradeHelper.InitiateUpgradeAsync(StreamUpgradeInitiator upgradeInitiator, IConnection connection, ClientFramingDecoder decoder, IDefaultCommunicationTimeouts defaultTimeouts, TimeSpan timeout)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.SendPreambleAsync(IConnection connection, Memory`1 preamble, TimeSpan timeout)
   at System.ServiceModel.Channels.ConnectionPoolHelper.EstablishConnectionAsync(TimeSpan timeout)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.OnOpenAsync(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.OnOpenAsyncInternal(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.System.ServiceModel.IAsyncCommunicationObject.OpenAsync(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.OnOpenAsync(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.OnOpenAsyncInternal(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.System.ServiceModel.IAsyncCommunicationObject.OpenAsync(TimeSpan timeout)
   at System.Runtime.TaskHelpers.WaitForCompletion(Task task)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open()
   at System.ServiceModel.Channels.ServiceChannelProxy.System.ServiceModel.ICommunicationObject.Open()
   at ConsoleApp4.Program.Main(String[] args) in E:\ConsoleApp4\ConsoleApp4\Program.cs:line 37
Aborted (core dumped)

### Describe actual behavior

it should works the output helloworld. 

### Which binding

NetTcp

### security

Transport

### Which .NET version

.NET 7

### Which os platform

Linux

**Comment by birojnayak** [comment]
@ZhaodongTian it looks like you are using  clientCredentialType as UnixDomainSocketClientCredentialType.Windows and it's complaining about missing keytab in LInux "(Keytab FILE:/etc/krb5.keytab is nonexistent or empty". If you need windows auth ([link to setup ](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-8.0&tabs=visual-studio#linux-and-macos-environment-configuration)).

If you don't need Windows auth, can try other auth mode and check out this UnixDomainSocketClientCredentialType.PosixIdentity specifically for Linux ([Blog](https://corewcf.github.io/blog/2023/09/01/udsbinding)). 

Let me know if you are stuck further
