### ISSUE TITLE
[Bug]: CoreWCF.ProtocolException: Content Type application/soap+xml; charset=utf-8 was sent to a service expecting text/xml; charset=utf-8.  The client and service bindings may be mismatched.

### ISSUE THREAD

**Issue by wangyimingok** [CoreWCF/CoreWCF#1364]
### Duplicate ?

- [X] I have searched issues/discussions and did not find other issues/discussions reporting this bug.

### Product version

1.5.2

### Describe expected behavior

Request service method and obtain data

### Describe actual behavior

2024-04-09 00:04:16.370 +08:00 [ERR] Connection id "0HN2NSKGKAMP6", Request id "0HN2NSKGKAMP6:00000001": An unhandled exception was thrown by the application.
CoreWCF.ProtocolException: Content Type application/soap+xml; charset=utf-8 was sent to a service expecting text/xml; charset=utf-8.  The client and service bindings may be mismatched.
   at CoreWCF.Channels.HttpInput.ThrowHttpProtocolException(String message, HttpStatusCode statusCode, String statusDescription)
   at CoreWCF.Channels.HttpInput.ValidateContentType()
   at CoreWCF.Channels.HttpInput.ParseIncomingMessageAsync()
   at CoreWCF.Channels.AspNetCoreReplyChannel.HandleRequest(HttpContext context)
   at CoreWCF.Channels.RequestDelegateHandler.HandleRequest(HttpContext context)
   at CoreWCF.Channels.ServiceModelHttpMiddleware.InvokeAsync(HttpContext context)
   at CoreWCF.Channels.MetadataMiddleware.InvokeAsync(HttpContext context)

### Which binding

BasicHttp

### security

None

### Which .NET version

.NET 6

### Which os platform

Windows

### Code snippet used to reproduce the issue

```c#
//绑定WareHouse服务
 builder.AddService<WareHouseDataService>((serviceOptions) =>
 {
     serviceOptions.BaseAddresses.Add(new Uri($"{localhosthttpAddress}/WareHouseSvc.svc"));
     serviceOptions.DebugBehavior.HttpHelpPageUrl = new Uri($"{localhosthttpAddress}/WareHouseSvc.svc/help");
     serviceOptions.DebugBehavior.HttpHelpPageEnabled = true;
     serviceOptions.DebugBehavior.IncludeExceptionDetailInFaults = true;
 })
.AddServiceEndpoint<WareHouseDataService, IWareHouseSvc>(new BasicHttpBinding(), $"{localhosthttpAddress}/WareHouseSvc.svc", option =>
{
    option.Name = "WareHouseSvc";
    option.ListenUri = new Uri($"{localhosthttpAddress}/WareHouseSvc.svc");       
});
```

### Stacktrace if any

```shell
2024-04-09 00:04:16.370 +08:00 [ERR] Connection id "0HN2NSKGKAMP6", Request id "0HN2NSKGKAMP6:00000001": An unhandled exception was thrown by the application.
CoreWCF.ProtocolException: Content Type application/soap+xml; charset=utf-8 was sent to a service expecting text/xml; charset=utf-8.  The client and service bindings may be mismatched.
   at CoreWCF.Channels.HttpInput.ThrowHttpProtocolException(String message, HttpStatusCode statusCode, String statusDescription)
   at CoreWCF.Channels.HttpInput.ValidateContentType()
   at CoreWCF.Channels.HttpInput.ParseIncomingMessageAsync()
   at CoreWCF.Channels.AspNetCoreReplyChannel.HandleRequest(HttpContext context)
   at CoreWCF.Channels.RequestDelegateHandler.HandleRequest(HttpContext context)
   at CoreWCF.Channels.ServiceModelHttpMiddleware.InvokeAsync(HttpContext context)
   at CoreWCF.Channels.MetadataMiddleware.InvokeAsync(HttpContext context)
```

**Comment by wangyimingok** [comment]
Using WCFTestClient.exe to call the service can get normal data return, but using the proxy client class cannot get normal data return.

**Comment by wangyimingok** [comment]
Personally, I feel that there should be an agreement between the server/client that needs to constrain its return type, and that both the client and the server need to be consistent, but I don't know where to agree on it.

**Comment by mconnew** [comment]
The content type `application/soap+xml` is when you are using SOAP 1.2, and `text/xml` is when you are using SOAP 1.1.  BasicHttpBinding uses the oldest most supported protocol (when considering other programming languages/frameworks) which is SOAP 1.1. The most likely binding you need to use is `new WSHttpBinding(SecurityMode.None)` or `new WSHttpBinding(SecurityMode.Transport)`. If you use transport security, you will need to set `WSHttpBinding.Security.Transport.ClientCredentialType` to the appropriate value as it defaults to `Windows`.  
Where are you getting the client from? Is it a WCF client? Or some other platform?

**Comment by wangyimingok** [comment]
> The content type `application/soap+xml` is when you are using SOAP 1.2, and `text/xml` is when you are using SOAP 1.1. BasicHttpBinding uses the oldest most supported protocol (when considering other programming languages/frameworks) which is SOAP 1.1. The most likely binding you need to use is `new WSHttpBinding(SecurityMode.None)` or `new WSHttpBinding(SecurityMode.Transport)`. If you use transport security, you will need to set `WSHttpBinding.Security.Transport.ClientCredentialType` to the appropriate value as it defaults to `Windows`. Where are you getting the client from? Is it a WCF client? Or some other platform?

Thank you, I am now using CoreWCF to migrate the previous .NET Framework WCF service to adapt to the updated iteration of technology, and using .NET Core to enable container cluster deployment, the current exception is obtained from the old Windows client.

**Comment by mconnew** [comment]
You need to use the same binding as we used with .NET Framework. This can be non-obvious sometimes as .NET Framework primarily used .config for configuring the binding, and if you are using a custom binding, working out the equivalence in code can be tricky. If you would like to provide you binding config from .NET Framework, I can help you work out what it should be in code.

**Comment by wangyimingok** [comment]
> You need to use the same binding as we used with .NET Framework. This can be non-obvious sometimes as .NET Framework primarily used .config for configuring the binding, and if you are using a custom binding, working out the equivalence in code can be tricky. If you would like to provide you binding config from .NET Framework, I can help you work out what it should be in code.

I have a general understanding of WSHttpBinding and BasicHttpBinding. Synchronously translating from .NET Framewoek to .NET Core should not be a big problem, for example:
` <system.serviceModel>
    <behaviors>
      <serviceBehaviors>
        <behavior>
          
          <serviceMetadata httpGetEnabled="true"/>
          
          <serviceDebug includeExceptionDetailInFaults="true"/>
          <serviceCredentials>
            <clientCertificate>
              <authentication certificateValidationMode="None"/>
            </clientCertificate>
            <serviceCertificate findValue="CPKey" x509FindType="FindBySubjectName" storeLocation="LocalMachine" storeName="My"/>
            <userNameAuthentication userNamePasswordValidationMode="Custom" customUserNamePasswordValidatorType="B2C.Bussiness.CustomUserNameValidator,  B2C.Bussiness"/>
          </serviceCredentials>
          <serviceAuthorization principalPermissionMode="Custom">
            <authorizationPolicies>
              <add policyType=" B2C.Bussiness.AuthorizationPolicy,  B2C.Bussiness"/>
            </authorizationPolicies>
          </serviceAuthorization>
          <B2CCustomErrorHandler/>
          <serviceThrottling maxConcurrentCalls="10000" maxConcurrentSessions="10000" maxConcurrentInstances="10000"/>
          <dataContractSerializer maxItemsInObjectGraph="2147483647"/>
        </behavior>
      </serviceBehaviors>
      <endpointBehaviors>
        <behavior>
          <dataContractSerializer maxItemsInObjectGraph="2147483647"/>
        </behavior>
      </endpointBehaviors>
    </behaviors>
    <extensions>
      <behaviorExtensions>
        <add name="B2CCustomErrorHandler" type="B2C.Interface.ErrorHandlerElement, B2C.Interface"/>
      </behaviorExtensions>
    </extensions>
    <protocolMapping>
      <add binding="wsHttpBinding" scheme="http"/>
    </protocolMapping>
    <bindings>
      <wsHttpBinding>
        <binding maxReceivedMessageSize="65536000" maxBufferPoolSize="524288000">
          <readerQuotas maxStringContentLength="2147483647" maxDepth="32" maxArrayLength="163840000" maxBytesPerRead="4096" maxNameTableCharCount="16384"/>
          <security mode="Message">
            <message clientCredentialType="UserName"/>
          </security>
        </binding>
      </wsHttpBinding>
    </bindings>
    <serviceHostingEnvironment multipleSiteBindingsEnabled="true" aspNetCompatibilityEnabled="false"/>
  </system.serviceModel>`
Translated into .NET Core you can directly:
 `var webHttpBinding= new WebHttpBinding(WebHttpSecurityMode.None);
webHttpBinding.Security.Transport.ClientCredentialType = HttpClientCredentialType.None;
//webHttpBinding.WriteEncoding = Encoding.UTF8;
var myWSHttpBinding = new WSHttpBinding(SecurityMode.None);
myWSHttpBinding.Security.Transport.ClientCredentialType = HttpClientCredentialType.None;
`
My personal understanding is that the configuration section of the .NET Framework probably has corresponding objects for use in .NET Core. It's just that I'm not sure how to use the certificate now. Can you please give me some advice?

**Comment by mconnew** [comment]
Are you saying you want to use certificate authentication? The code you provided is quite a bit different than what the config has. In the config, you are using full Message security (which isn't supported yet), with UserName authentication. The closest match would be to use SecurityMode.TransportWithMessageCredentials with UserName client credential type. But you will need to configure asp.net core to use https instead of http, and will need to configure a server certificate. You will need to change the client side too as these are incompatible on the wire with Message security. Documentation for setting up Kestrel to use https can be found here: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-8.0#configure-https

BTW, WebHttpBinding is REST based services and not SOAP.

**Comment by wangyimingok** [comment]
I read your reply carefully, and in summary it means that if I want to migrate the existing .NET Framework WCF to .NET Core WCF, the conditions cannot be completely migrated so far. Is my understanding correct?

**Comment by wangyimingok** [comment]
> Are you saying you want to use certificate authentication? The code you provided is quite a bit different than what the config has. In the config, you are using full Message security (which isn't supported yet), with UserName authentication. The closest match would be to use SecurityMode.TransportWithMessageCredentials with UserName client credential type. But you will need to configure asp.net core to use https instead of http, and will need to configure a server certificate. You will need to change the client side too as these are incompatible on the wire with Message security. Documentation for setting up Kestrel to use https can be found here: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-8.0#configure-https
> 
> BTW, WebHttpBinding is REST based services and not SOAP.

I read your reply carefully, and in summary it means that if I want to migrate the existing .NET Framework WCF to .NET Core WCF, the conditions cannot be completely migrated so far. Is my understanding correct?
