### ISSUE TITLE
[Bug]: Support reading messageType attribute for basicHttpBinding in config xml

### ISSUE THREAD

**Issue by loftum** [CoreWCF/CoreWCF#1374]
### Duplicate ?

- [X] I have searched issues/discussions and did not find other issues/discussions reporting this bug.

### Product version

1.5.2

### Describe expected behavior

```csharp
public void ConfigureServices(IServiceCollection services)
{
  services.AddServiceModelConfigurationManagerFile("wcf.config");
}
```

should parse messageEncoding in basicHttpBinding from this config file:

wcf.config:
```xml
<?xml version="1.0"?>
<configuration>
    <system.serviceModel>
        <bindings>
            <basicHttpBinding>
                <binding name="BasicHttpBinding_Example" messageEncoding="Text"></binding>
            </basicHttpBinding>
        </bindings>
    </system.serviceModel>
</configuration>
```

### Describe actual behavior

```csharp
services.AddServiceModelConfigurationManagerFile("wcf.config");
```

throws

```
System.Configuration.ConfigurationErrorsException: Unrecognized attribute 'MessageEncoding'. Note that attribute names are case-sensitive.
```

### Which binding

BasicHttp

### security

None

### Which .NET version

.NET 6

### Which os platform

Mac OS

### Code snippet used to reproduce the issue

```c#
<?xml version="1.0"?>
<configuration>
    <system.serviceModel>
        <bindings>
            <basicHttpBinding>
                <binding name="BasicHttpBinding_Example" messageEncoding="Text"></binding>
            </basicHttpBinding>
        </bindings>
    </system.serviceModel>
</configuration>
```

### Stacktrace if any

```shell
System.Configuration.ConfigurationErrorsException: Unrecognized attribute 'messageEncoding'. Note that attribute names are case-sensitive. (wcf.config line 5)
   at System.Configuration.BaseConfigurationRecord.EvaluateOne(String[] keys, SectionInput input, Boolean isTrusted, FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult)
   at System.Configuration.BaseConfigurationRecord.Evaluate(FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult, Boolean getLkg, Boolean getRuntimeObject, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey, Boolean getLkg, Boolean checkPermission)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Configuration.ConfigurationSectionCollection.Get(String name)
   at System.Configuration.ConfigurationSectionCollection.get_Item(String name)
   at CoreWCF.Configuration.ServiceModelSectionGroup.get_Bindings()
   at CoreWCF.Configuration.ConfigurationManagerServiceModelOptions.ReadConfigSection(ServiceModelSectionGroup group)
   at CoreWCF.Configuration.ConfigurationManagerServiceModelOptions.ParseConfig()
   at CoreWCF.Configuration.ConfigurationManagerServiceModelOptions.Configure(ServiceModelOptions options)
   at CoreWCF.Configuration.ConfigurationManagerServiceModelOptions.Configure(String name, ServiceModelOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
   at CoreWCF.Configuration.ServiceModelApplicationBuilderExtensions.UseServiceModel(IApplicationBuilder app)
   at RubberChickenWithPulleyInTheMiddle.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment environment) in /melee/island/Startup.cs:line 42
```

**Comment by loftum** [comment]
Possible solution:
Adding configuration property

```
[ConfigurationProperty(ConfigurationStrings.MessageEncoding, DefaultValue = WSMessageEncoding.Text)]
public WSMessageEncoding MessageEncoding
{
    get { return (WSMessageEncoding)base[ConfigurationStrings.MessageEncoding]; }
    set { base[ConfigurationStrings.MessageEncoding] = value; }
}
```

to `CoreWCF.Configuration.BasicHttpBindingElement.cs` makes the exception go away.

Not sure if this will have any side-effects, but I can't think of any.

**Comment by loftum** [comment]
I would be happy to create a PR.

**Comment by mconnew** [comment]
The original code can be found here: https://referencesource.microsoft.com/#System.ServiceModel/System/ServiceModel/Configuration/BasicHttpBindingElement.cs,28

It looks like this:
```c#
        [ConfigurationProperty(ConfigurationStrings.MessageEncoding, DefaultValue = BasicHttpBindingDefaults.MessageEncoding)]
        [ServiceModelEnumValidator(typeof(WSMessageEncodingHelper))]
        public WSMessageEncoding MessageEncoding
        {
            get { return (WSMessageEncoding)base[ConfigurationStrings.MessageEncoding]; }
            set { base[ConfigurationStrings.MessageEncoding] = value; }
        }
```
I don't know if we have support for ServiceModelEnumValidator or WSMessageEncodingHelper, but if we do, that should be there too. A PR would be greatly appreciated.

**Comment by kachalkov** [comment]
how is that PR coming @loftum :)
