### ISSUE TITLE
[Bug]: System.TimeoutException occurs when using TransferMode.Streamed without security (TcpClientCredentialType.None, SecurityMode.None)

### ISSUE THREAD

**Issue by benjaminrupp** [CoreWCF/CoreWCF#1391]
### Duplicate ?

- [X] I have searched issues/discussions and did not find other issues/discussions reporting this bug.

### Product version

1.5.1 / 1.5.2

### Describe expected behavior

We are using a CoreWCF service in an .NET8 App with streaming (TransferMode.Streamed). With TcpClientCredentialType.Windows or certifcate everything works fine. 
When switching to TcpClientCredentialType.None we get an exception.

### Describe actual behavior

System.TimeoutException:

Exception: 
Beim Anforderungskanal ist während eines Sendeversuchs nach 10675199.02:48:05.4775807 ein Timeout aufgetreten. Erhöhen Sie den an den Aufruf von "Request" übergebenen Zeitlimitwert, oder erhöhen Sie den SendTimeout-Wert für die Bindung. Der für diesen Vorgang zugewiesene Zeitraum war möglicherweise ein Teil eines längeren Zeitlimits.

Translated: The request channel timed out during a send attempt after 10675199.02:48:05.4775807. Increase the timeout value passed to the Request call or increase the SendTimeout value for the binding. The time allotted for this operation may have been part of a longer time limit.

Inner exception: 
Der Anforderungsvorgang wurde nicht innerhalb des zugewiesenen Zeitlimits von 10675199.02:48:05.4775807 abgeschlossen. Der für diesen Vorgang zugewiesene Zeitraum war möglicherweise ein Teil eines längeren Timeouts.

Translated: The request operation did not complete within the allotted timeout of 10675199.02:48:05.4775807. The time allotted for this operation may have been part of a longer timeout.

Inner exception: 
Bei der Socketübertragung ist nach -00:00:00.0010000 ein Timeout aufgetreten. Das für die Bindung festgelegte Zeitlimit wurde überschritten. Der für diesen Vorgang zugewiesene Zeitraum war möglicherweise ein Teil eines längeren Zeitlimits.

Translated: The socket transfer timed out after -00:00:00.0010000. The binding time limit has been exceeded. The time allotted for this operation may have been part of a longer time limit.

### Which binding

NetTcp

### security

None

### Which .NET version

.NET 6

### Which os platform

Windows

### Code snippet used to reproduce the issue

```c#
var netTcpBinding = new NetTcpBinding(SecurityMode.None)
  {
      Namespace = Namespace,
      OpenTimeout = TimeSpan.FromSeconds(60),
      CloseTimeout = TimeSpan.FromSeconds(60),
      SendTimeout = TimeSpan.MaxValue,
      ReceiveTimeout = TimeSpan.MaxValue,
      MaxBufferPoolSize = int.MaxValue,
      MaxBufferSize = int.MaxValue,
      ReaderQuotas =
      {
          MaxStringContentLength = int.MaxValue,
          MaxArrayLength = int.MaxValue,
          MaxBytesPerRead = int.MaxValue,
          MaxNameTableCharCount = int.MaxValue,
          MaxDepth = 200,
      },
  };
 netTcpBinding.Security.Transport.ClientCredentialType = TcpClientCredentialType.None;
 netTcpBinding.TransferMode = TransferMode.Streamed;
 netTcpBinding.MaxReceivedMessageSize = long.MaxValue;



var customBinding = new CustomBinding(netTcpBinding);
customBinding.Elements.Find<BinaryMessageEncodingBindingElement>().CompressionFormat =       CompressionFormat.GZip;
```

### Stacktrace if any

```shell
System.TimeoutException
Bei der Socketübertragung ist nach -00:00:00.0010000 ein Timeout aufgetreten. Das für die Bindung festgelegte Zeitlimit wurde überschritten. Der für diesen Vorgang zugewiesene Zeitraum war möglicherweise ein Teil eines längeren Zeitlimits.
•	   at System.ServiceModel.Channels.SocketConnection.SetWriteTimeout(TimeSpan timeout)
•	   at System.ServiceModel.Channels.SocketConnection.WriteAsync(ReadOnlyMemory`1 buffer, Boolean immediate, TimeSpan timeout)
•	   at System.ServiceModel.Channels.BufferedConnection.WriteNowAsync(ReadOnlyMemory`1 buffer, TimeSpan timeout)
•	   at System.ServiceModel.Channels.StreamingConnectionHelper.StreamingOutputConnectionStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
•	   at System.ServiceModel.Channels.TimeoutStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
•	   at System.ServiceModel.Channels.TimeoutStream.WriteAsyncInternal(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
•	   at System.Runtime.TaskHelpers.WaitForCompletion(Task task)
•	   at System.ServiceModel.Channels.TimeoutStream.Write(Byte[] buffer, Int32 offset, Int32 count)
•	   at System.IO.Compression.DeflateStream.WriteDeflaterOutput()
•	   at System.IO.Compression.DeflateStream.WriteCore(ReadOnlySpan`1 buffer)
•	   at System.IO.Compression.DeflateStream.Write(Byte[] buffer, Int32 offset, Int32 count)
•	   at System.Xml.XmlStreamNodeWriter.FlushBuffer()
•	   at System.Xml.XmlBinaryNodeWriter.UnsafeWriteText(Char* chars, Int32 charCount)
•	   at System.Xml.XmlBinaryNodeWriter.WriteTextImpl(String value)
•	   at System.Xml.XmlBaseWriter.WriteValue(String value)
•	   at System.Runtime.Serialization.DataContractSerializer.InternalWriteObjectContent(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
•	   at System.Runtime.Serialization.DataContractSerializer.InternalWriteObject(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
•	   at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
•	   at System.ServiceModel.Dispatcher.DataContractSerializerOperationFormatter.SerializeParameterPart(XmlDictionaryWriter writer, PartInfo part, Object graph)
•	   at System.ServiceModel.Dispatcher.DataContractSerializerOperationFormatter.SerializeParameter(XmlDictionaryWriter writer, PartInfo part, Object graph)
•	   at System.ServiceModel.Dispatcher.DataContractSerializerOperationFormatter.SerializeParameters(XmlDictionaryWriter writer, PartInfo[] parts, Object[] parameters)
•	   at System.ServiceModel.Dispatcher.DataContractSerializerOperationFormatter.SerializeBody(XmlDictionaryWriter writer, MessageVersion version, String action, MessageDescription messageDescription, Object returnValue, Object[] parameters, Boolean isRequest)
•	   at System.ServiceModel.Dispatcher.OperationFormatter.SerializeBodyContents(XmlDictionaryWriter writer, MessageVersion version, Object[] parameters, Object returnValue, Boolean isRequest)
•	   at System.ServiceModel.Dispatcher.OperationFormatter.OperationFormatterMessage.OperationFormatterBodyWriter.OnWriteBodyContents(XmlDictionaryWriter writer)
•	   at System.ServiceModel.Channels.BodyWriterMessage.OnWriteBodyContents(XmlDictionaryWriter writer)
•	   at System.ServiceModel.Channels.Message.OnWriteMessage(XmlDictionaryWriter writer)
•	   at System.ServiceModel.Channels.BinaryMessageEncoderFactory.BinaryMessageEncoder.WriteMessage(Message message, Stream stream)
•	   at System.ServiceModel.Channels.MessageEncoder.WriteMessageAsync(Message message, Stream stream)
•	   at System.ServiceModel.Channels.StreamingConnectionHelper.WriteMessageAsync(Message message, IConnection connection, Boolean isRequest, IConnectionOrientedTransportFactorySettings settings, TimeoutHelper timeoutHelper)
•	   at System.ServiceModel.Channels.StreamedFramingRequestChannel.StreamedConnectionPoolHelper.StreamedFramingAsyncRequest.SendRequestAsync(Message message, TimeoutHelper timeoutHelper)
System.TimeoutException
Der Anforderungsvorgang wurde nicht innerhalb des zugewiesenen Zeitlimits von 10675199.02:48:05.4775807 abgeschlossen. Der für diesen Vorgang zugewiesene Zeitraum war möglicherweise ein Teil eines längeren Timeouts.
•	   at System.ServiceModel.Channels.StreamedFramingRequestChannel.StreamedConnectionPoolHelper.StreamedFramingAsyncRequest.SendRequestAsync(Message message, TimeoutHelper timeoutHelper)
•	   at System.ServiceModel.Channels.RequestChannel.RequestAsync(Message message, TimeSpan timeout)
System.TimeoutException
Beim Anforderungskanal ist während eines Sendeversuchs nach 10675199.02:48:05.4775807 ein Timeout aufgetreten. Erhöhen Sie den an den Aufruf von "Request" übergebenen Zeitlimitwert, oder erhöhen Sie den SendTimeout-Wert für die Bindung. Der für diesen Vorgang zugewiesene Zeitraum war möglicherweise ein Teil eines längeren Zeitlimits.
•	   at System.ServiceModel.Channels.RequestChannel.RequestAsync(Message message, TimeSpan timeout)
•	   at System.ServiceModel.Channels.RequestChannel.RequestAsyncInternal(Message message, TimeSpan timeout)
•	   at System.Runtime.TaskHelpers.WaitForCompletionNoSpin[TResult](Task`1 task)
•	   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
•	   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
•	   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
•	   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
•	   at generatedProxy_12.DownloadDatabaseBackup(DownloadDatabaseBackupRequest)
```

**Comment by mconnew** [comment]
This might be a client side bug. Leave it here for now as I'll investigate to verify. The thing which makes me think this is a client side problem is that you have configured the send timeout to TimeSpan.MaxValue, which is 10675199 days, which is roughly 29247 years. You shouldn't ever be able to get a client side timeout with that duration. When you use any type of security, there's an IConnection which gets wrapped as a Stream, which is then wrapped in either SslStream or NegotiateStream, which is then wrapped back as an IConnection again. This causes the timeout mechanism to be handled slightly differently, and I think that's where the bug it. How long does it actually take to throw a TimeoutException?

**Comment by benjaminrupp** [comment]
Hi Matt, thanks for the response. 
The TimeoutException occurs immediately after the method is called.
Benjamin

**Comment by mconnew** [comment]
We got to the bottom of this, and it came down to a really dumb bug. Long explanation below of what went wrong below. There's a simple workaround you can use, which unfortunately has some side effects which you need to keep in mind when choosing a value.  
Don't use TimeSpan.MaxValue but a sufficiently big TimeSpan instead. As the TimeSpan you specify will get converted to an int for some internal purposes, you can't exceed int.MaxValue ms in duration. `TimeSpan.FromMilliseconds(int.MaxValue).Days` returns 24 so if you went over that, there would overflow problems. There is a side effect you have to be aware of which depending on your usage may or may not be of concern. To reduce the number of CancellationToken instances created in a high throughput app, we coalesce CancellationTokenSource instances. This is because while WCF passes around TimeSpan, the runtime api's we use take a CancellationToken. One top level call with a TimeSpan can result in dozens of CancellationToken's being created, each with their own timer. In the early days of .NET Core, there were contention problems doing this (we saw 50%+ CPU time on timer queue contention in some load testing). The solution was to store every CancellationTokenSource we create in a pool until it expires, and every time we need one, we look in the pool for one with a close enough expiry time. This is especially applicable for Streamed transfer where a 1GB transfer would have tens of thousands of writes. The single call sending 1GB will have the same deadline, so you'd only allocate a single CancellationTokenSource (and a single timer) for the entire operation despite there being over 65k writes to the socket. There isn't an api surface we can pass a CancellationToken down through so each call to a runtime api which needs a CancellationToken has no direct access to the previous one used for the same top level operation, so we use a pool to avoid creating and disposing at a high rate. Because two operations kicked off at the same time (or with 2 different timeouts at different times which end up with the same deadline time), we can't dispose the CancellationTokenSource until the timer fires, so it lives until the timeout happens.  
What this means is if you set a non MaxValue TimeSpan, every call will have one (sometimes a few more as there's a bit of imprecision) CancellationTokenSource with an associated Timer that will exist in your process until the timer expires. What this comes down to is if you set your SendTimeout to 10 days, and you make 5,000 calls per day, at the end of the 10 days your process will have 50,000 timers waiting to fire.  
We will work on releasing a fix for this bug, but until that's released, set the timeouts to something sufficiently large that you will never have them fire, but the minimum you can tolerate to avoid accumulating too many CancellationTokenSource instances in your process. E.g. if an hour is sufficient that you would never hit that, set it to `TimeSpan.FromHours(1)`.

You can stop reading here if you want, the rest is the explanation of the root cause if you're interested.  

WCF was created before CancellationToken was invented, so it has its own mechanism for composite operations which need to time out. If you have a timeout of 10 seconds and you are doing 5 things, you don't want to use a 10 second timeout for each thing as that could take up to 50 seconds before it times out. We have a TimeoutHelper class which we set the desired timeout on. This class calculates the deadline based on the timeout and the current time. Then for each component operation, it does the math to see how much time is left and returns the timeout duration for the remaining time left. Because that math can go negative (you got past the timeout), we can end up with a negative TimeSpan. When passing around timeouts as millisecond (e.g. to Stream calls), -1 means infinite. We want to avoid having a timeout elapse by 1ms and end up passing infinite timeout to a .NET runtime call such as Stream.ReadAsync. For our own bookkeeping, we use TimeSpan.MaxValue to indicate infinite (as opposed to Timeout.InfiniteTimeSpan which just represents -1 ms). You are doing this when setting the binding timeouts to TimeSpan.MaxValue to indicate no timeout.  
There were 2 places which only affected Streamed transfer mode with no security where the conversion was being done incorrectly. When we're setting the WriteTimeout (an int property) on a Stream class (our own implementation, but need to keep the same semantics as the base runtime class), we correctly convert that to -1 as that means infinite for Stream. Then when we go to write to our SocketConnection class which takes TimeSpan, we used the wrong helper method to convert the WriteTimeout to a TimeSpan and instead of using TimeSpan.MaxValue, we passed a TimeSpan representing a timeout that expired 1ms ago (-1). The fix is to use the correct timeout helper method.

**Comment by benjaminrupp** [comment]
Thanks for the detailed explanation

**Comment by mconnew** [comment]
Are you sufficiently unblocked for now?

**Comment by benjaminrupp** [comment]
We just checked your described workaround. I worked fine for us. Thanks
