### ISSUE TITLE
[Feature Request]: Can't use security on Windows with UnixDomainSocketBinding

### ISSUE THREAD

**Issue by cbenard** [CoreWCF/CoreWCF#1411]
**Is your feature request related to a problem? Please describe.**
`CoreWCF.UnixDomainSocketTransportSecurity` is missing the following code that is in the `System.ServiceModel` version:

```cs
[DefaultValue(DefaultProtectionLevel)]
public ProtectionLevel ProtectionLevel
{
    get { return _protectionLevel; }
    set
    {
        if (!Security.ProtectionLevelHelper.IsDefined(value))
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException(nameof(value)));
        }

        _protectionLevel = value;
    }
}
```

This means I can't write the following code I write on the client side:
`binding.Security.Transport.ProtectionLevel = System.Net.Security.ProtectionLevel.None;`

I honestly can't figure out how to implement authentication that the [blog post](https://corewcf.github.io/blog/2023/09/01/udsbinding) mentions.

Ideally, I want to authenticate based on the Windows account on the same machine without a certificate, since it's local. I am trying to replace `NetNamedPipeBinding`, since it seems like it's never going to be committed to the `main` branch here.

The only way I've gotten it to work is with `new CoreWCF.UnixDomainSocketBinding(CoreWCF.UnixDomainSocketSecurityMode.None);`.

I'm not certain of the security implications of that though. I don't know if I can rely on NTFS permissions of read/write to protect me here, since I've never used Unix Domain Sockets on Windows before.

**Describe the solution you'd like**

* Add the missing code to `UnixDomainSocketTransportSecurity`, if applicable.
* Add samples, especially for Windows, for `UnixDomainSocketBinding` and include authenticating on the server side, according to best practices, since `AF_UNIX` usage is definitely not common on Windows yet.
* **Ideally, complete `NetNamedPipeBinding` in the mainline releases instead of relegating to pre-release, so that it can be used instead, like the legacy code.**

**Describe alternatives you've considered**
`new CoreWCF.UnixDomainSocketBinding(CoreWCF.UnixDomainSocketSecurityMode.None);`.

**Comment by mconnew** [comment]
UnixDomainSockets should perform better than NetNamedPipe. If you don't have legacy systems to interop with, it's the better option.  
When running on Windows, you should get the same authentication mechanism as NetNamedPipe. On Windows, the default transport mode is Transport (unix has different default behavior), and the default transport client credential type is Default. This looks a little weird, but it's to accommodate sensible defaults on Windows and Linux without having to do too much work. On Windows, Default means Windows auth (for Linux it means posix identification, basically the service looks up the username of the process at the other end of the socket). This translates to using `WindowsStreamSecurityBindingElement` which in turn secures the connection with `NegotiateStream`, the same as `NetNamedPipe` uses by default. You should just be able to use the `UnixDomainSocketBinding` with the default constructor and have it use the same security as `NetNamedPipe`.  
It looks like that's a bug missing the ProtectionLevel property. The good news is there's another way to set it.
```c#
var udsBinding = new CoreWCF.UnixDomainSocketBinding();
var binding = new CustomBinding(udsBinding);
var wssbe = binding.Elements.Find<WindowsStreamSecurityBindingElement>();
wssbe.ProtectionLevel = System.Net.Security.ProtectionLevel.None;
```
Then use the custom binding for your endpoint. Why are you wanting to set the ProtectionLevel to None? Is it to remove the overhead of the encryption and hashing done in NegotiateStream? I'm curious if you've measured the overhead, and if so, how much is it? And was the measurement recent? Modern processors have special purpose instructions for doing encryption so the overhead will be lower than 10 years ago (ignoring the improvement due to CPU performance increases).  

As for security implications of different options, the only difference between using UnixDomainSocketSecurityMode.None (no security), and Transport with Default/Windows client credential type when you set the ProtectionLevel to None is the latter lets you know who the user is that's connected. Neither have any encryption or integrity checks (uses a hash to make sure data wasn't modified). I don't know the inner workings of UnixDomainSockets to know if another process can listen in on the communication. The file ACL is about which user can connect to the socket to talk to the service. I suspect the permission level required to snoop on an established UnixDomainSocket connection would also enable you to attach to the process and read from its memory, but I'm not an authority on this aspect, that's just a hunch. The primary purpose of using UnixDomainSocket/NetNamedPipe is to ensure a remote host can't connect to your service. Once someone is able to run code on a host, it's generally game over when it comes to security. If I was owning a product which was using UDS with CoreWCF, I would leave the ProtectLevel at the default and use Windows auth (so leave as Default) unless there was a strong reason not to (e.g. performance).

**Comment by cbenard** [comment]
First, thanks for replying. Second, before reviewing my reply, please also look at #1412. **It would negate my need for any of the stuff below or this bug.**

> Why are you wanting to set the ProtectionLevel to None?

I was trying to set the properties the correct way based on the code below in `UnixDomainSocketSecurity` in order to get security on both sides (ServiceModel client and CoreWCF server). My goal was **to** have security that didn't rely on certificates and ideally authenticate with the claims (documented on the blog post) that the user is the same user on the other end. However, there is no sample that does any of this, yet.

Do I need to open a new issue as a Bug for the missing `ProtectionLevel` property?

From `UnixDomainSocketSecurity`:

```cs
internal BindingElement CreateTransportSecurity()
{
    if (_mode == UnixDomainSocketSecurityMode.Transport || _mode == UnixDomainSocketSecurityMode.TransportCredentialOnly)
    {
        if ((_mode == UnixDomainSocketSecurityMode.TransportCredentialOnly && Transport.ClientCredentialType != UnixDomainSocketClientCredentialType.PosixIdentity)
            ||
            (_mode == UnixDomainSocketSecurityMode.Transport && Transport.ClientCredentialType == UnixDomainSocketClientCredentialType.PosixIdentity))
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new NotSupportedException(SR.Format(SR.UnsupportedSecuritySetting, "Mode", _mode)));
        }
        return Transport.CreateTransportProtectionAndAuthentication();
    }
    else if (_mode == UnixDomainSocketSecurityMode.None)
    {
        return null;
    }
    else
    {
        throw new NotSupportedException();
    }
}
```

**Comment by mconnew** [comment]
I would appreciate you opening a bug for ProtectionLevel. You generally should just leave it as is. You should be good to just use UnixDomainSocketBinding with the default constructor when on Windows. For ClaimSet stuff, you should see a WindowsClaimsSet with the user as part of that claimset. I'll reply to the other issue other there.

**Comment by cbenard** [comment]
If I use the default constructor for `UnixDomainSocketBinding` on both sides, I get the following client-side (ServiceModel) exception:

```
System.ServiceModel.Security.SecurityNegotiationException
  HResult=0x80131500
  Message=Authentication failed on the remote side (the stream might still be available for additional authentication attempts).
  Source=System.ServiceModel.NetFramingBase
  StackTrace:
   at System.ServiceModel.Channels.WindowsStreamSecurityUpgradeProvider.WindowsStreamSecurityUpgradeInitiator.<OnInitiateUpgradeAsync>d__9.MoveNext()
   at System.ServiceModel.Channels.StreamSecurityUpgradeInitiatorBase.<InitiateUpgradeAsync>d__13.MoveNext()
   at System.ServiceModel.Channels.ConnectionUpgradeHelper.<InitiateUpgradeAsync>d__1.MoveNext()
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.<SendPreambleAsync>d__9.MoveNext()
   at System.ServiceModel.Channels.ConnectionPoolHelper.<EstablishConnectionAsync>d__14.MoveNext()
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.<OnOpenAsync>d__10.MoveNext()
   at System.ServiceModel.Channels.CommunicationObject.<OnOpenAsyncInternal>d__89.MoveNext()
   at System.ServiceModel.Channels.CommunicationObject.<System-ServiceModel-IAsyncCommunicationObject-OpenAsync>d__88.MoveNext()
   at System.ServiceModel.Channels.ServiceChannel.<OnOpenAsync>d__152.MoveNext()
   at System.ServiceModel.Channels.CommunicationObject.<OnOpenAsyncInternal>d__89.MoveNext()
   at System.ServiceModel.Channels.CommunicationObject.<System-ServiceModel-IAsyncCommunicationObject-OpenAsync>d__88.MoveNext()
   at System.Runtime.TaskHelpers.WaitForCompletion(Task task)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open()
   at System.ServiceModel.Channels.ServiceChannelProxy.System.ServiceModel.ICommunicationObject.Open()
   at ConcurrentCoreWcfUnixSocket.Program.EnsureWcf() in D:\Git\Temp\NamedPipeTesting\ConcurrentCoreWcfUnixSocket\Program.cs:line 117
   at ConcurrentCoreWcfUnixSocket.Program.SendMessage(String name) in D:\Git\Temp\NamedPipeTesting\ConcurrentCoreWcfUnixSocket\Program.cs:line 128
   at ConcurrentCoreWcfUnixSocket.Program.<>c.<Main>b__9_8() in D:\Git\Temp\NamedPipeTesting\ConcurrentCoreWcfUnixSocket\Program.cs:line 91
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)

Inner Exception 1:
AuthenticationException: Authentication failed on the remote side (the stream might still be available for additional authentication attempts).

Inner Exception 2:
Win32Exception: The credentials supplied to the package were not recognized
```

**Comment by cbenard** [comment]
@mconnew can you look at the stack trace caused with the default constructor?

**Comment by mconnew** [comment]
The exception is coming from NegotiateStream. Despite the message in Inner Exception 1, I believe this is a client side problem. Seeing the exception stack of Inner Exeception 2 might help verify that. I would expect the same behavior from NetTcp and NetNamedPipe as NegotiateStream has no knowledge about the underlying connection it is communicating over.

**Comment by cbenard** [comment]
> Seeing the exception stack of Inner Exeception 2 might help verify that

Inner 1:
```
System.Security.Authentication.AuthenticationException: Authentication failed on the remote side (the stream might still be available for additional authentication attempts).
 ---> System.ComponentModel.Win32Exception (0x8009030D): The credentials supplied to the package were not recognized
   --- End of inner exception stack trace ---
   at System.Net.Security.NegotiateStream.ThrowCredentialException(Int64 error)
   at System.Net.Security.NegotiateStream.ReceiveBlobAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.NegotiateStream.SendBlobAsync[TIOAdapter](Byte[] message, CancellationToken cancellationToken)
   at System.Net.Security.NegotiateStream.ReceiveBlobAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.NegotiateStream.SendBlobAsync[TIOAdapter](Byte[] message, CancellationToken cancellationToken)
   at System.Net.Security.NegotiateStream.AuthenticateAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.ServiceModel.Channels.WindowsStreamSecurityUpgradeProvider.WindowsStreamSecurityUpgradeInitiator.OnInitiateUpgradeAsync(Stream stream)
```

Inner 2:
```
System.ComponentModel.Win32Exception (0x8009030D): The credentials supplied to the package were not recognized
```

Stack trace is null:

![image](https://github.com/user-attachments/assets/bc21e576-24b6-4cdc-8c7c-133e9974bd0c)

**Comment by cbenard** [comment]
@mconnew no errors with default ctors on `NetTcpBinding`. Only code changed was this. The rest was the same.

Please see above for the limited `Exception.ToString()`s on the `InnerException`s and the screenshot confirming `Exception.StackTrace` being `null`.

Can you assist, since `UnixDomainSocketBinding` just **does not work with the default ctor**.

```cs
var binding = new System.ServiceModel.NetTcpBinding();
var endpoint = new System.ServiceModel.EndpointAddress(new Uri(NetTcpEndpoint));
```

**Comment by mconnew** [comment]
I've worked out what the problem is with UDS. Change your code to this and it should work:
```c#
var endpoint = new System.ServiceModel.EndpointAddress(new Uri(NetUdsEndpoint), new SpnEndpointIdentity("host/localhost"));
```
The problem is caused by the Uri scheme for UDS not having a hostname. The existing code tries to extract the target name from the Uri, which it does by creating the string `"host/uriHostname"`. For NetTcp and NetNamedPipe, this works fine as they both require a hostname as part of the Uri. But UDS doesn't have a hostname, so the string created is `host/` with nothing after the slash. This causes authentication to fail. By specifying an `SpnEndpointIdentity`, you remove the implicit creation of the targetName and are explicitly telling it exactly the target name to use. Now the auth works with the default UDS binding.

**Comment by mconnew** [comment]
I've opened an issue in the WCF repo at dotnet/wcf#5621 to track the bug there.

**Comment by cbenard** [comment]
The workaround worked. I definitely would not have figured that out. Are there not tests around the default security once it was added?

Also, is there any way we can get code samples to verify the claims created by the default security, especially on Windows?

**Comment by mconnew** [comment]
There are tests, but there were 2 things hiding the issue. First, a UriBuilder was used to construct the url. So doing something like this:
```c#
var uriBuilder = new UriBuilder()
{
    Scheme = "net.uds",
    Path = LinuxSocketFilepath
};
var uri = uriBuilder.Uri;
```
Results in a Uri with the hostname of the Uri automatically populated with "localhost". There's code to fix up the EndpointAddress which strips the hostname out as it doesn't make sense to be in there, but also if an EndpointIdentity isn't provided, it took the hostname and created a DnsEndpointIdentity from it. If the hostname was null, it would use "localhost". That null check should be a string.IsNullOrEmpty check instead.  

The second problem why tests didn't catch it is even if the Uri had been created without a hostname, we have `try { /* execute call and cleanup channel/factory */ } finally { /* cleanup channel/factory if aborted etc */ }` logic, and the tests mistakenly had a `catch` block which would have caught the test failure and made it look like a pass.

**Comment by mconnew** [comment]
You can also do this providing the hostname as part of the Uri:
```
var uri = new Uri("net.uds://localhost/" + SocketFilepath);
```
And that would have also fixed it.

**Comment by cbenard** [comment]
Interesting. I think that last one looks more legible in our code. I wouldn't think to concat a "URI" with a Windows file path syntax.

I'm about to comment again on the named pipe issue just as an FYI.
