### ISSUE TITLE
[Bug]: Service can't process reuest when load balancer or proxy with BasicHttpMessageCredentialType.UserName

### ISSUE THREAD

**Issue by SwimUp** [CoreWCF/CoreWCF#1432]
### Duplicate ?

- [X] I have searched issues/discussions and did not find other issues/discussions reporting this bug.

### Product version

1.5.2

### Describe expected behavior

I'm trying to use BasicHttpMessageCredentialType.UserName with BasicHttpBinding and proxy, since the service should be behind a load balancer, and only accepts requests on the http port.

I'm also deploying the service in a docker container, Ubuntu and Kestrel

**I'm using .NET 8.0**

### Describe actual behavior

If I create a BasicHttpBinding I get an error: Could not find a base address that matches scheme https for the endpoint with binding BasicHttpBinding. Registered base address schemes are [http].

I created a new class and overridden Scheme to always return http:
```
    public class BasicHttpBindingWithSecurity : BasicHttpBinding
    {
        public override string Scheme => "http"

        public BasicHttpBindingWithSecurity() : this(BasicHttpSecurityMode.None)
        {
        }

        public BasicHttpBindingWithSecurity(BasicHttpSecurityMode securityMode) : base(securityMode) 
        {

        }
    }
```

Now the service starts, but when I try to send a request I get
```
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:u="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
   <s:Header>
      <o:Security s:mustUnderstand="1" xmlns:o="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
         <u:Timestamp u:Id="_0">
            <u:Created>2024-08-08T08:48:33.976Z</u:Created>
            <u:Expires>2024-08-08T08:53:33.976Z</u:Expires>
         </u:Timestamp>
      </o:Security>
   </s:Header>
   <s:Body>
      <s:Fault>
         <faultcode xmlns:a="http://schemas.microsoft.com/net/2005/12/windowscommunicationfoundation/dispatcher">a:InternalServiceFault</faultcode>
         <faultstring>Object reference not set to an instance of an object.</faultstring>
         <detail>
            <ExceptionDetail xmlns="http://schemas.datacontract.org/2004/07/System.ServiceModel" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
               <HelpLink i:nil="true"/>
               <InnerException i:nil="true"/>
               <Message>Object reference not set to an instance of an object.</Message>
               <StackTrace>at lambda_method4(Closure, Object, Object[], Object[])
   at CoreWCF.Dispatcher.SyncMethodInvoker.InvokeAsync(Object instance, Object[] inputs)
   at CoreWCF.Dispatcher.DispatchOperationRuntime.&lt;>c__DisplayClass71_0.&lt;&lt;InvokeAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at CoreWCF.Dispatcher.DispatchOperationRuntime.InvokeAsync(MessageRpc rpc)
   at CoreWCF.Dispatcher.DispatchOperationRuntime.InvokeAsync(MessageRpc rpc)
   at CoreWCF.Dispatcher.ImmutableDispatchRuntime.ProcessMessageAsync(MessageRpc rpc)
   at CoreWCF.Dispatcher.MessageRpc.ProcessAsync(Boolean isOperationContextSet)</StackTrace>
               <Type>System.NullReferenceException</Type>
            </ExceptionDetail>
         </detail>
      </s:Fault>
   </s:Body>
</s:Envelope>
```
I tried log request on service side and it's looks fine:
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/">
	<soapenv:Header>
		<wsse:Security soapenv:mustUnderstand="1" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
			<wsse:UsernameToken wsu:Id="UsernameToken-AB8204CC05666F943417230640526568">
				<wsse:Username>user</wsse:Username>
				<wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText">user</wsse:Password>
				<wsse:Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">/iCaZ4tplU/MZqu6byxUOg==</wsse:Nonce>
				<wsu:Created>2024-08-07T20:54:12.656Z</wsu:Created>
			</wsse:UsernameToken>
		</wsse:Security>
	</soapenv:Header>
	<soapenv:Body>
		<tem:GetData>
			<!--Optional:-->
			<tem:DateWithinInterval>2023-01-01</tem:DateWithinInterval>
		</tem:GetData>
	</soapenv:Body>
</soapenv:Envelope>
```

### Which binding

BasicHttp

### security

TransportWithMessageCredential

### Which .NET version

.NET 7

### Which os platform

Linux

### Code snippet used to reproduce the issue

```c#
BasicHttpBindingWithSecurity:
 public class BasicHttpBindingWithSecurity : BasicHttpBinding
    {
        public override string Scheme => "http"

        public BasicHttpBindingWithSecurity() : this(BasicHttpSecurityMode.None)
        {
        }

        public BasicHttpBindingWithSecurity(BasicHttpSecurityMode securityMode) : base(securityMode) 
        {

        }
    }

Create kestrel:
    internal class Program
    {
        static void Main(string[] args)
        {
            IWebHost host = CreateWebHostBuilder(args).Build();
            host.Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
            .UseKestrel(options => {
                options.ListenAnyIP(Startup.HTTP_PORT);
            })
            .UseStartup<Startup>();
    }

Startup:
    public class Startup
    {
        public const int HTTP_PORT = 8080;
        //public const int HTTPS_PORT = 443;

        public IConfiguration Configuration { get; private set; }

        public Startup(IConfiguration configuration)
        {
            this.Configuration = configuration;
        }

        public void ConfigureServices(IServiceCollection services)
        {
            // Enable CoreWCF Services, enable metadata
            // Use the Url used to fetch WSDL as that service endpoint address in generated WSDL 
            services.AddServiceModelServices()
                    .AddServiceModelMetadata()
                    .AddSingleton<IServiceBehavior, UseRequestHeadersForMetadataAddressBehavior>();
        }

        public void Configure(IApplicationBuilder app)
        {
            var basicHttpBinding = new BasicHttpBinding(BasicHttpSecurityMode.TransportWithMessageCredential);
            basicHttpBinding.Security.Mode = BasicHttpSecurityMode.TransportWithMessageCredential;
            basicHttpBinding.Security.Transport.ClientCredentialType = HttpClientCredentialType.None;
            basicHttpBinding.Security.Message.ClientCredentialType = BasicHttpMessageCredentialType.UserName;

            string httpUri = Configuration.GetValue<string>("Basic:HttpURI");
            app.UseServiceModel(builder =>
            {
                builder.AddService<Service>(serviceOptions =>
                {
                    if (!string.IsNullOrEmpty(httpUri))
                    {
                        serviceOptions.BaseAddresses.Add(new Uri($"http://{httpUri}"));
                    }

                    serviceOptions.DebugBehavior.IncludeExceptionDetailInFaults = true;
                })
                .AddServiceEndpoint<Service, IService>(basicHttpBinding, "/Service.svc")

                .ConfigureServiceHostBase<Service>(serviceHostBase =>
                {
                    serviceHostBase.Credentials.UserNameAuthentication.UserNamePasswordValidationMode = UserNamePasswordValidationMode.Custom;
                    serviceHostBase.Credentials.UserNameAuthentication.CustomUserNamePasswordValidator = new CustomUserNameValidator();
                });
            });

            var serviceMetadataBehavior = app.ApplicationServices.GetRequiredService<CoreWCF.Description.ServiceMetadataBehavior>();
            serviceMetadataBehavior.HttpGetEnabled = true;
        }
    }

CustomUserNameValidator:
    public class CustomUserNameValidator : UserNamePasswordValidator
    {
        public override void Validate(string userName, string password)
        {
            if (userName != "user" || password != "pass")
            {
                throw new SecurityException("Wrong password");
            }
        }
    }
```

**Comment by SwimUp** [comment]
It seems the error occurs if I don't specify an optional parameter

```
    [ServiceContract]
    public interface IService
    {

        [OperationContract]
        List<Data> GetData(DateTime DateWithinInterval, int versionNumber = 1);

    }

 [DataContract]
 public class Data
 {
     [DataMember]
     public double? value{ get; set; }
 }
```

if i send:
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/">
   <soapenv:Header/>
   <soapenv:Body>
      <tem:GetData>
         
         <tem:DateWithinInterval>2013-01-01</tem:DateWithinInterval>
      </tem:GetData>
   </soapenv:Body>
</soapenv:Envelope>
i got:
`The server was unable to process the request due to an internal error.  For more information about the error, either turn on IncludeExceptionDetailInFaults (either from ServiceBehaviorAttribute or from the &lt;serviceDebug> configuration behavior) on the server in order to send the exception information back to the client, or turn on tracing as per the Microsoft .NET Framework SDK documentation and inspect the server trace logs.`
with detail
```
            <ExceptionDetail xmlns="http://schemas.datacontract.org/2004/07/System.ServiceModel" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
               <HelpLink i:nil="true"/>
               <InnerException i:nil="true"/>
               <Message>Object reference not set to an instance of an object.</Message>
               <StackTrace>at lambda_method4(Closure, Object, Object[], Object[])
   at CoreWCF.Dispatcher.SyncMethodInvoker.InvokeAsync(Object instance, Object[] inputs)
   at CoreWCF.Dispatcher.DispatchOperationRuntime.&lt;>c__DisplayClass71_0.&lt;&lt;InvokeAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at CoreWCF.Dispatcher.DispatchOperationRuntime.InvokeAsync(MessageRpc rpc)
   at CoreWCF.Dispatcher.DispatchOperationRuntime.InvokeAsync(MessageRpc rpc)
   at CoreWCF.Dispatcher.ImmutableDispatchRuntime.ProcessMessageAsync(MessageRpc rpc)
   at CoreWCF.Dispatcher.MessageRpc.ProcessAsync(Boolean isOperationContextSet)</StackTrace>
               <Type>System.NullReferenceException</Type>
            </ExceptionDetail>
```
if i send:
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/">
   <soapenv:Header/>
   <soapenv:Body>
      <tem:GetData>
         <!--Optional:-->
         <tem:DateWithinInterval>2013-01-01</tem:DateWithinInterval>
         <!--Optional:-->
         <tem:versionNumber>1</tem:versionNumber>
      </tem:GetData>
   </soapenv:Body>
</soapenv:Envelope>
```

request works

**Comment by SwimUp** [comment]
Okay, now i use
```
 public class BasicHttpBindingWithSecurity : BasicHttpBinding
    {
        public override string Scheme => "http"

        public BasicHttpBindingWithSecurity() : this(BasicHttpSecurityMode.None)
        {
        }

        public BasicHttpBindingWithSecurity(BasicHttpSecurityMode securityMode) : base(securityMode) 
        {

        }
    }
```
When i send request, i got "An error occurred when verifying security for the message"
In server logs:
```
CoreWCF.Security.MessageSecurityException: Cannot find a token authenticator for the 'CoreWCF.IdentityModel.Tokens.UserNameSecurityToken' token type. Tokens of that type cannot be accepted according to current security settings.
   at CoreWCF.Security.ReceiveSecurityHeader.ReadTokenAsync(XmlReader reader, SecurityTokenResolver tokenResolver, IList`1 allowedTokenAuthenticators)
   at CoreWCF.Security.ReceiveSecurityHeader.ReadTokenAsync(XmlDictionaryReader reader, Int32 position, Byte[] decryptedBuffer, SecurityToken encryptionToken, String idInEncryptedForm, TimeSpan timeout)
   at CoreWCF.Security.ReceiveSecurityHeader.ExecuteReadingPassAsync(XmlDictionaryReader reader)
   at CoreWCF.Security.LaxModeSecurityHeaderElementInferenceEngine.ExecuteProcessingPassesAsync(ReceiveSecurityHeader securityHeader, XmlDictionaryReader reader)
   at CoreWCF.Security.ReceiveSecurityHeader.ProcessAsync(TimeSpan timeout, ChannelBinding channelBinding, ExtendedProtectionPolicy extendedProtectionPolicy)
   at CoreWCF.Security.TransportSecurityProtocol.VerifyIncomingMessageCoreAsync(Message message, TimeSpan timeout)
   at CoreWCF.Security.TransportSecurityProtocol.VerifyIncomingMessageAsync(Message message, TimeSpan timeout)
   at CoreWCF.Security.SecurityProtocol.VerifyIncomingMessageAsync(Message message, TimeSpan timeout, SecurityProtocolCorrelationState[] correlationStates)
   at CoreWCF.Dispatcher.ServerSecurityChannelDispatcher`1.VerifyIncomingMessageAsync(Message message, TimeSpan timeout, SecurityProtocolCorrelationState[] correlationState)
   at CoreWCF.Dispatcher.SecurityReplyChannelDispatcher.ProcessReceivedRequestAsync(RequestContext requestContext)
   at CoreWCF.Dispatcher.SecurityReplyChannelDispatcher.ProcessReceivedRequestAsync(RequestContext requestContext)
   at CoreWCF.Dispatcher.SecurityReplyChannelDispatcher.DispatchAsync(RequestContext context)
   at CoreWCF.Channels.AspNetCoreReplyChannel.HandleRequest(HttpContext context)
   at CoreWCF.Channels.RequestDelegateHandler.HandleRequest(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at CoreWCF.Channels.ServiceModelHttpMiddleware.InvokeAsync(HttpContext context)
   at CoreWCF.Channels.MetadataMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by SwimUp** [comment]
Finnaly, i got it worked

1.  Create new binding, related BasicHttpBinding and override Scheme
  ```
  public class BasicHttpBindingWithSecurity : BasicHttpBinding
    {
        public override string Scheme
        {
            get
            {
                string value = base.Scheme;

                value = "http";

                return value;
            }
        }


        public BasicHttpBindingWithSecurity() : this(BasicHttpSecurityMode.None)
        {
        }

        public BasicHttpBindingWithSecurity(BasicHttpSecurityMode securityMode) : base(securityMode)
        {

        }
    }
```

2. Create your own CustomUserNameValidator
### Important: In CoreWCF you need override "ValidateAsync" insted "Validate"

  ```
  public class CustomUserNameValidator : UserNamePasswordValidator
    {
        public override ValueTask ValidateAsync(string userName, string password)
        {
            if (userName != Service.Settings.Settings["auth"]["username"] || password != Service.Settings.Settings["auth"]["password"])
            {
                throw new SecurityException("Неверный логин/пароль");
            }

            return ValueTask.CompletedTask;
        }
    }
```

3. Create your binding:
```
           var basicHttpBinding = new BasicHttpBindingWithSecurity(BasicHttpSecurityMode.TransportWithMessageCredential);
            basicHttpBinding.Security.Mode = BasicHttpSecurityMode.TransportWithMessageCredential;
            basicHttpBinding.Security.Transport.ClientCredentialType = HttpClientCredentialType.None;
            basicHttpBinding.Security.Message.ClientCredentialType = BasicHttpMessageCredentialType.UserName;
```
and create endpoints:

//your endpoint from appsettings.json
```
string httpUri = Configuration.GetValue<string>("Basic:HttpURI");

            app.UseServiceModel(builder =>
            {
                builder.AddService<Service>(serviceOptions =>
                {
                    if (!string.IsNullOrEmpty(httpUri))
                    {
                        serviceOptions.BaseAddresses.Add(new Uri($"http://{httpUri}"));
                    }
                })
                .AddServiceEndpoint<Service, IService>(basicHttpBinding, "/Service.svc")

                .ConfigureServiceHostBase<Service>(serviceHostBase =>
                {
                    serviceHostBase.Credentials.UserNameAuthentication.UserNamePasswordValidationMode = UserNamePasswordValidationMode.Custom;
                    serviceHostBase.Credentials.UserNameAuthentication.CustomUserNamePasswordValidator = new CustomUserNameValidator();
                });
            });


            var serviceMetadataBehavior = app.ApplicationServices.GetRequiredService<ServiceMetadataBehavior>();
            serviceMetadataBehavior.HttpGetEnabled = true;
```

**Comment by mconnew** [comment]
You answered your own question before I had a change to respond.  

I couldn't find the behavior documented anywhere of what WCF does to handle this so I went to the ultimate documentation, the source code. I compared the implementation between WCF and CoreWCF/WCF Client and it looks like a difference in behavior bug here which has been fixed in main but not shipped yet. When deserializing the request parameters, they are placed into an `object[]` array matching the parameter index. If the element is missing from the request, it gets left as null. We have a new Expression based implementation which when calling the service operation, the values are cast to the correct type and passed as arguments to the method call. `DateTime` is a struct so you can't cast null to a `DateTime` which is why you get the exception. The older implementation passed the null in the `object[]` to `MethodInfo.Invoke` which surprisingly handles realizing it's a struct and passes the `default` value instead. There two options to solve that:
1. Set the AppContext switch `CoreWCF.Dispatcher.UseLegacyInvokeDelegate` to true until the next release is out.
2. Change your method to use a nullable, ie `DateTime? DateWithinInterval` as you can cast a null to `DateTime?`

For the security problem, there's an easier fix. When you specify `BasicHttpSecurityMode.TransportWithMessageCredential`, the `Transport` part means you are using SSL. It's understandable that the token needs to be securely transferred as you are sending the password in plain text, but you have a LB which is doing the SSL offload. In this situation, you can add some inline middleware before call app.UseServiceModel to switch the HttpRequest to say it's using SSL. We just look at the request scheme. You will also need to modify the service base address to tell it you're listening on https instead of http, so you can do this:

```c#
app.Use((context, next) =>
{
    IHttpRequestFeature httpRequestFeature = context.Features.Get();
    httpRequestFeature.Scheme = "https";
    return next(context);
});

app.UseServiceModel(builder =>
{
    builder.AddService<Service>(serviceOptions =>
    {
        if (!string.IsNullOrEmpty(httpUri))
        {
            serviceOptions.BaseAddresses.Clear();
            serviceOptions.BaseAddresses.Add(new Uri($"https://{httpUri}"));
        }
    })
    /* Rest of configuration */
});
```
If you have non CoreWCF endpoints too (e.g. WebApi/Mvc) you will need to make the code which modifies the scheme be conditional, e.g. based on the path. My general preference with solving problems is to update state to how things are (it was an HTTPS request from the client to the LB so the request should say that) rather than modifying the expected conditions (ie make the binding tell CoreWCF it's handling http requests) as you're less likely to have problems if additional validation is added down the line.  

BTW, you can still override the Validate method if you need common code between .NET Framework and CoreWCF, it will just give you a compiler warning that it's obsolete, but it's still functional.
