### ISSUE TITLE
[Bug]: CoreWCF server returns 0 bytes when accessed from an old .NET Framework application

### ISSUE THREAD

**Issue by nmg196** [CoreWCF/CoreWCF#1476]
### Duplicate ?

- [X] I have searched issues/discussions and did not find other issues/discussions reporting this bug.

### Product version

1.6.0

### Describe expected behavior

I have created a basic CoreWCF server to hopefully replace an old .NET Framework server. However it needs to be backwards compatible with the old interface.

I'm finding that when I connect from my legacy app, the server returns 0 bytes. Yet when I build a new .NET Framework console app, it works OK.   I can't spot what the differences are as they both target .NET Framework 4.5.2.

Is there a way perhaps to see if there is any internal error in CoreWCF when the connection comes from the older application?

Is CoreWCF compatible with SOAP 1.1? 

Here is my server code for the Core 8 app:

`using CoreWCFService;
using System.Web.Services.Description;

var builder = WebApplication.CreateBuilder();

builder.Services.AddServiceModelServices();
builder.Services.AddServiceModelMetadata();
builder.Services.AddSingleton<IServiceBehavior, UseRequestHeadersForMetadataAddressBehavior>();

var app = builder.Build();

app.UseServiceModel(serviceBuilder =>
{
	serviceBuilder.AddService<UploaderAPI>();
	var binding = new BasicHttpBinding(BasicHttpSecurityMode.Transport);
	serviceBuilder.AddServiceEndpoint<UploaderAPI, IUploaderAPISoap>(binding, "/Service.svc");

	var serviceMetadataBehavior = app.Services.GetRequiredService<ServiceMetadataBehavior>(); 
	serviceMetadataBehavior.HttpsGetEnabled = true;
	serviceMetadataBehavior.HttpGetEnabled = true;

});

app.Run();`

In the Windows event log, there is an exception which says CoreWCF thinks the XML is invalid.

The XML sent by each app is differnt for some reason (different SOAP versions?):

Older app:
<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><HelloWorld xmlns="http://mileagecount.live.x-rm.com/uploaderapi"><echo>foo</echo></HelloWorld></soap:Body></soap:Envelope>

Newer app:
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><HelloWorld xmlns="http://mileagecount.live.x-rm.com/uploaderapi" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><echo>foo</echo></HelloWorld></s:Body></s:Envelope>

But I have no idea why as they're both .NET Framework 4.5 apps using the same auto-generated client code.

### Describe actual behavior

Expected behaviour is that it should respond the same in both the old and new apps. 

### Which binding

BasicHttp

### security

Transport

### Which .NET version

.NET 7

### Which os platform

Windows

### Stacktrace if any

```shell
CoreWCF.ProtocolException: There is a problem with the XML that was received from the network. See inner exception for more details.
 ---> System.Xml.XmlException: The data at the root level is invalid. Line 1, position 1.
   at System.Xml.XmlExceptionHelper.ThrowXmlException(XmlDictionaryReader reader, String res, String arg1, String arg2, String arg3)
   at System.Xml.XmlUTF8TextReader.Read()
   at System.Xml.XmlBaseReader.IsStartElement()
   at System.Xml.XmlBaseReader.IsStartElement(XmlDictionaryString localName, XmlDictionaryString namespaceUri)
   at CoreWCF.Channels.ReceivedMessage.ReadStartEnvelope(XmlDictionaryReader reader)
   at CoreWCF.Channels.BufferedMessage..ctor(IBufferedMessageData messageData, RecycledMessageState recycledMessageState, Boolean[] understoodHeaders, Boolean understoodHeadersModified)
   at CoreWCF.Channels.BufferedMessage..ctor(IBufferedMessageData messageData, RecycledMessageState recycledMessageState)
   at CoreWCF.Channels.TextMessageEncoderFactory.TextMessageEncoder.ReadMessage(ArraySegment`1 buffer, BufferManager bufferManager, String contentType)
   at CoreWCF.Channels.HttpInput.DecodeBufferedMessageAsync(ArraySegment`1 buffer, Stream inputStream)
   --- End of inner exception stack trace ---
   at CoreWCF.Channels.HttpInput.DecodeBufferedMessageAsync(ArraySegment`1 buffer, Stream inputStream)
   at CoreWCF.Channels.HttpInput.ReadBufferedMessageAsync(Stream inputStream)
   at CoreWCF.Channels.HttpInput.ParseIncomingMessageAsync()
   at CoreWCF.Channels.AspNetCoreReplyChannel.HandleRequest(HttpContext context)
   at CoreWCF.Channels.RequestDelegateHandler.HandleRequest(HttpContext context)
   at CoreWCF.Channels.ServiceModelHttpMiddleware.InvokeAsync(HttpContext context)
   at CoreWCF.Channels.MetadataMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Comment by nmg196** [comment]
It turns out CoreWCF doesn't like it when the request is compressed with GZIP. I think it unpacks the ZIP but then uses the original content-length header to read the XML resulting in truncated XML.
