### ISSUE TITLE
[Bug]: Second named Pipe connection can't be open after first one closed

### ISSUE THREAD

**Issue by MJE-GTI** [CoreWCF/CoreWCF#1492]
### Duplicate ?

- [X] I have searched issues/discussions and did not find other issues/discussions reporting this bug.

### Product version

1.5.0-preview1 and local 1.6.0 branch Build for CoreWCF.NetNamedPipe; 1.6.0 all other CoreWCF Components

### Describe expected behavior

I can open a second named pipe connection after the first one is closed.

### Describe actual behavior

I can't open a second named pipe connection after the first one is closed. If I try to open a second, I will receive a `System.IO.IOException` on the client side with the exception message `Pipe is broken`. In the server log, I can find a NullReferenceException. This only happens if I wait some time before I open the second connection after closing the first one.

The fix that works for me was inserting `AddNamedPipeListenOptionsToConnectionContext(options);` between these two lines: https://github.com/CoreWCF/CoreWCF/blob/1fbc816d8aa2263eec2f737ec211dc4bb1b8b859/src/CoreWCF.NetNamedPipe/src/CoreWCF/Channels/NamedPipeListener.cs#L42-L43

### Which binding

NetNamedPipe

### security

None

### Which .NET version

.NET 7

### Which os platform

Windows

### Code snippet used to reproduce the issue

```c#
private static async Task CallNetPipeBinding(string hostAddr)
{
    IClientChannel channel = null;

    var binding = new NetNamedPipeBinding();

    var factory = new ChannelFactory<IEchoService>(binding, new EndpointAddress($"{hostAddr}/netnamedpipe"));
    await Task.Factory.FromAsync(factory.BeginOpen, factory.EndOpen, TaskCreationOptions.None);
    try
    {
        IEchoService client = factory.CreateChannel();
        channel = client as IClientChannel;
        await Task.Factory.FromAsync(channel.BeginOpen, channel.EndOpen, TaskCreationOptions.None);
        await client.Echo("Test");
        channel.Close();

        await Task.Delay(10_000); // wait for the server side to completly close the session
        client = factory.CreateChannel();
        channel = client as IClientChannel;
        await Task.Factory.FromAsync(channel.BeginOpen, channel.EndOpen, TaskCreationOptions.None);
        await client.Echo("Test");
        channel.Close();
    }
    catch (Exception ex)
    {
        Console.WriteLine(DateTime.Now + "NET PIPE Error: " + ex.Message);
    }
    finally
    {
        factory.Close();
    }
}
```

### Stacktrace if any

```shell
Unhandled exception while processing 711ed7bc-9918-4729-8741-e03d3d1ba5bd.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at CoreWCF.Channels.Framing.FramingModeHandshakeMiddleware.OnConnectedCoreAsync(FramingConnection connection)
         at CoreWCF.Channels.Framing.FramingModeHandshakeMiddleware.OnConnectedAsync(FramingConnection connection)
         at CoreWCF.Channels.NamedPipeConnection.ExecuteAsync()
```

**Comment by FST-GTI** [comment]
This bug is already fixed, so it should be closed
