### ISSUE TITLE
Crash due to CoreWCF: KeyNotFoundException in RequestReplyCorrelator

### ISSUE THREAD

**Issue by 0x53A** [CoreWCF/CoreWCF#181]
I found this event in my windows server eventlog:

```
Application: MyWebAPI.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Collections.Generic.KeyNotFoundException
   at System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_Item(System.__Canon)
   at CoreWCF.Channels.RequestReplyCorrelator.CoreWCF.Channels.IRequestReplyCorrelator.Find[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](CoreWCF.Channels.Message, Boolean)
   at CoreWCF.Dispatcher.DuplexChannelBinder.HandleRequestAsReplyCore(CoreWCF.Channels.Message)
   at CoreWCF.Dispatcher.DuplexChannelBinder.HandleRequestAsReply(CoreWCF.Channels.Message)
   at CoreWCF.Dispatcher.ChannelHandler+<HandleRequestAsync>d__48.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

This is CoreWCF running in IIS with ASP.Net Core 2.1 on .NET Framework 4.6.1.

The version of CoreWCF used is ``0.1.0-alpha.71``.

I only get this exception like twice a month.

---------

(I don't know how actionable this stacktrace alone is, feel free to just close it)

**Comment by mconnew** [comment]
This is an expected condition that can happen, but the exception should be swallowed and not kill the process. So this is missing a try/catch and log somewhere. I consider this a must fix before coming out of pre-release.

**Comment by mconnew** [comment]
This looks like the same issue as has been reported by the WCF Core client in dotnet/wcf#4301
