### ISSUE TITLE
Operation with IsOneWay=true throw System.NullReferenceException

### ISSUE THREAD

**Issue by imcarolwang** [CoreWCF/CoreWCF#197]
Enable below test variation will repro the issue: https://github.com/CoreWCF/CoreWCF/blob/d86c26483b8a8300d98b14d5c8338dc4fb14bc0d/src/CoreWCF.Http/tests/OpActionReplyActionBehaviorTests.cs#L27

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=CoreWCF.Http
  StackTrace:
   at CoreWCF.Channels.HttpOutput.AspNetCoreHttpOutput..ctor(HttpContext httpContext, IHttpTransportFactorySettings settings, Message message, String httpMethod) in E:\OSS\carol\CoreWCF\src\CoreWCF.Http\src\CoreWCF\Channels\HttpChannelHelpers.cs:line 823
   at CoreWCF.Channels.HttpOutput.CreateHttpOutput(HttpContext httpContext, IHttpTransportFactorySettings settings, Message message, String httpMethod) in E:\OSS\carol\CoreWCF\src\CoreWCF.Http\src\CoreWCF\Channels\HttpChannelHelpers.cs:line 807
   at CoreWCF.Channels.HttpRequestContext.AspNetCoreHttpContext.GetHttpOutput(Message message) in E:\OSS\carol\CoreWCF\src\CoreWCF.Http\src\CoreWCF\Channels\HttpRequestContext.cs:line 369
   at CoreWCF.Channels.HttpRequestContext.<OnReplyAsync>d__25.MoveNext() in E:\OSS\carol\CoreWCF\src\CoreWCF.Http\src\CoreWCF\Channels\HttpRequestContext.cs:line 231
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

  This exception was originally thrown at this call stack:
    CoreWCF.Channels.HttpOutput.AspNetCoreHttpOutput.AspNetCoreHttpOutput(Microsoft.AspNetCore.Http.HttpContext, CoreWCF.Channels.IHttpTransportFactorySettings, CoreWCF.Channels.Message, string) in HttpChannelHelpers.cs
    CoreWCF.Channels.HttpOutput.CreateHttpOutput(Microsoft.AspNetCore.Http.HttpContext, CoreWCF.Channels.IHttpTransportFactorySettings, CoreWCF.Channels.Message, string) in HttpChannelHelpers.cs
    CoreWCF.Channels.HttpRequestContext.AspNetCoreHttpContext.GetHttpOutput(CoreWCF.Channels.Message) in HttpRequestContext.cs
    CoreWCF.Channels.HttpRequestContext.OnReplyAsync(CoreWCF.Channels.Message, System.Threading.CancellationToken) in HttpRequestContext.cs
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by mconnew** [comment]
Investigation is for GA milestone, not necessarily the fix depending on size of fix.
