### ISSUE TITLE
How to configure transport encryption when using net.tcp?

### ISSUE THREAD

**Issue by FreeAndNil** [CoreWCF/CoreWCF#200]
I would like to migrate an existing service from WCF to CoreWCF.
The service uses a certificate (from Windows Cert Store).
In WCF this is done via behavior in config file:

`      <serviceBehaviors>`
`        <behavior name="UseMyCert">`
`          <serviceCredentials>`
`            <serviceCertificate x509FindType="FindByIssuerName" findValue="MY ISSUING CA"/>`
`          </serviceCredentials>`
`        </behavior>`
`      </serviceBehaviors>`

`        <binding name="streamedSecureTcp" transferMode="Streamed">`
`          <security mode="Transport">`
`            <transport clientCredentialType="None" />`
`          </security>`
`        </binding>`

`      <service behaviorConfiguration="UseMyCert" name="MyNamespace.MyService">`
`        <endpoint address="net.tcp://localhost:800/MyService.svc"`
`           binding="netTcpBinding"`
`           bindingConfiguration="streamedSecureTcp"`
`           name="MyServer" bindingNamespace="http://my.com/service"`
`           contract="MyNamespace.IMyService" />`
`      </service>`

How can this be done in CoreWCF?
Providing the certificate as file would also be ok.

**Comment by FreeAndNil** [comment]
@mconnew do you have any suggestions?

**Comment by mconnew** [comment]
You should be able do this using something like this. I haven't compiled this so there's a chance of typos etc, but you should get the gist.
```c#
    public void Configure(IApplicationBuilder app, IHostingEnvironment env)
    {
        app.UseServiceModel(builder =>
        {
            builder.AddService<MyNamespace.MyService>();
            var binding = new NetTcpBinding();
            binding.TransferMode = TransferMode.Streamed;
            binding.Security.Transport.ClientCredentialType = TcpClientCredentialType.None;
            builder.AddServiceEndpoint<MyNamespace.MyService, MyNamespace.IMyService>(binding, "/MyService.svc");
            builder.ConfigureServiceHostBase<ContractBehaviorBasic_ByHand_Service>(serviceHost =>
            {
                serviceHost.Credentials.ServiceCertificate.SetCertificate(
                    StoreLocation.LocalMachine,
                    StoreName.My,
                    X509FindType.FindByIssuerName,
                    "MY ISSUING CA");
            });
        });
    }
```

You will also need to configure your host to use NetTcp, look in the samples folder for an example of how to set that up. You can also get the certificate by using X509Store to get an instance of an X509Certificate2 and pass that to SetCertificate instead.

**Comment by FreeAndNil** [comment]
Thanks for the response.
Sadly the callback provided to ConfigureServiceHostBase() is not called.
Is there any magic behind ContractBehaviorBasic_ByHand_Service?

**Comment by mconnew** [comment]
@FreeAndNil, sorry, I was copying it from some test code and forgot to replace the service type in the generic parameter for ConfigureServiceHostBase.  I've edited my prior comment to fix it. Did you use the service type or the service contract type in the generic parameter? It needs to be the service type. If you still can't get it working, can you provide a repro app? I should probably add some code to throw an exception if the generic parameter isn't a known service type to catch mistakes.

**Comment by FreeAndNil** [comment]
Thanks for the hint.
I've changed the NetCoreServer sample:

`        builder.ConfigureServiceHostBase<EchoService>(serviceHost =>
        {
          serviceHost.Credentials.ServiceCertificate.SetCertificate(
              StoreLocation.LocalMachine,
              ...
`
Now I get a NullReferenceException when accessing serviceHost.Credentials.ServiceCertificate because serviceHost.Credentials is not (yet) initialized.

**Comment by mconnew** [comment]
Whoops, looks like that's a TODO that I haven't got to yet: https://github.com/CoreWCF/CoreWCF/blob/master/src/CoreWCF.Primitives/src/CoreWCF/ServiceHostBase.cs#L125  
I can either quickly fix this and there would be a new package available by EOD, or you can insert this code into your delegate which is essentially the same code as is missing:
```c#
            ServiceCredentials c = serviceHost.Description.Behaviors.Find<ServiceCredentials>();
            if (c == null)
            {
                c = new ServiceCredentials();
                serviceHost.Description.Behaviors.Add(c);
            }
            c.ServiceCertificate.SetCertificate(.....);
```
I also believe you could add an instance of ServiceCredentials to DI in your ConfigureServices method, but add it as an IServiceBehavior. Something like this:
```c#
    var creds = new ServiceCredentials();
    // configure credentials class 
    services.AddSingleton<IServiceBehavior>(creds);
```
ServiceCredentials implements IServiceBehavior so any service behavior added to DI automatically gets added to the behaviors. I haven't tested this particular scenario, but I think it would work. I'll update this issue once there's a new package with this small fix.

**Comment by mconnew** [comment]
@FreeAndNil, the latest packages should fix the NullReferenceException. Please let me know if you were able to get everything working.

**Comment by FreeAndNil** [comment]
Thanks, now I get

System.InvalidOperationException
  HResult=0x80131509
  Message=The service certificate is not provided. Specify a service certificate in ServiceCredentials. 
  Source=CoreWCF.Primitives
  StackTrace:
   at CoreWCF.Security.ServiceCredentialsSecurityTokenManager.CreateServerX509TokenProvider() in D:\Git\CoreWCF\src\CoreWCF.Primitives\src\CoreWCF\Security\ServiceCredentialsSecurityTokenManager.cs:line 294

`
        X509SecurityTokenProvider CreateServerX509TokenProvider()
        {
            if (parent.ServiceCertificate.Certificate == null) // this is null
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidOperationException(SR.ServiceCertificateNotProvidedOnServiceCredentials));
            }
            SecurityUtils.EnsureCertificateCanDoKeyExchange(parent.ServiceCertificate.Certificate);
            return new ServiceX509SecurityTokenProvider(parent.ServiceCertificate.Certificate);
        }
`
The callback provided to ConfigureServiceHostBase() gets called and after that and serviceHost.Credentials.ServiceCertificate.Certificate has the expected value.

**Comment by mconnew** [comment]
Just want you to know I haven't forgotten about you, just got bogged down with other things right now.

**Comment by dubomire** [comment]
Hi there,
I have a similar issue but I'm getting the certificate from outside as base64 string. 
So I've tried the approach described above but got the InvalidOperationException 'The service certificate is not provided. Specify a service certificate in ServiceCredentials.' on host.Run() and exception thrown by [ServiceCredentialsSecurityTokenManager.CreateServerX509TokenProvider](https://github.com/CoreWCF/CoreWCF/blob/852471fe7e1fedd19fcdd3fac4be1dd0f27a842d/src/CoreWCF.Primitives/src/CoreWCF/Security/ServiceCredentialsSecurityTokenManager.cs#L290-L293). 
I'd pushed a sample with [my code on github](https://github.com/dubomire/CoreWCF/tree/feature/EncyptedNetTcpExample/src/Samples/NetTcpCoreServer) but I will describe the code bellow. Could you say what wrong there?

I took sample with CoreServer and updated Configure method.

Here is how I'm setting up my binding first:

```
    private static NetTcpBinding GetAndSetupTcpBinding()
    {
      NetTcpBinding tcpBinding = new NetTcpBinding();

      // Base binding params setup.
      tcpBinding.Name = "encryptedTcpBinding";
      tcpBinding.MaxBufferPoolSize = 52428800;
      tcpBinding.MaxReceivedMessageSize = 16777216;
      tcpBinding.MaxBufferSize = 16777216;

      // Setup reader quotas.
      tcpBinding.ReaderQuotas.MaxStringContentLength = 65536;
      tcpBinding.ReaderQuotas.MaxArrayLength = 65536;

      // Security settings.
      tcpBinding.Security.Mode = SecurityMode.Transport;
      tcpBinding.Security.Transport.ProtectionLevel = ProtectionLevel.EncryptAndSign;
      tcpBinding.Security.Transport.ClientCredentialType = TcpClientCredentialType.None;
      return tcpBinding;
    }
```
[...link](https://github.com/dubomire/CoreWCF/blob/50e2313499596824e382453d0c780e7036bedaeb/src/Samples/NetTcpCoreServer/Startup.cs#L18-L37)

Then how I'm using binding in Configure:
```
    public void Configure(IApplicationBuilder app, IHostingEnvironment env)
    {
      app.UseServiceModel(builder =>
      {
        NetTcpBinding tcpBinding = GetAndSetupTcpBinding();

        builder
          .AddService<EchoService>()
          .AddServiceEndpoint<EchoService, IEchoService>(
            binding: tcpBinding,
            address: hostUri)
          .ConfigureServiceHostBase<IEchoService>(
            serviceHost =>
            {
              serviceHost.Description.Behaviors.Add(
                CertificateHelper
                  .GenerateCertificateEncryptedBehaviour());
            });
      });
    }
```
[...link](https://github.com/dubomire/CoreWCF/blob/50e2313499596824e382453d0c780e7036bedaeb/src/Samples/NetTcpCoreServer/Startup.cs#L47-L66)

You can see that I'm adding ServiceCredentials with the certificate assignment. Here is the most significant code related to that:
```
public static ServiceCredentials GenerateCertificateEncryptedBehaviour()
    {
      ServiceCredentials certBehavior = new ServiceCredentials();
      certBehavior.ServiceCertificate.Certificate = GetCertificateFromBase64(cert);
      certBehavior.UserNameAuthentication.UserNamePasswordValidationMode =
        UserNamePasswordValidationMode.Custom;
      certBehavior.ClientCertificate.Authentication.CertificateValidationMode =
        X509CertificateValidationMode.None;
      return certBehavior;
    }
```
[... link](https://github.com/dubomire/CoreWCF/blob/50e2313499596824e382453d0c780e7036bedaeb/src/Samples/NetTcpCoreServer/Helpers/CertificateHelper.cs#L48-L57)

So after that I have  InvalidOperationException 'The service certificate is not provided. Specify a service certificate in ServiceCredentials.'. I'd tried to use a workaround with injecting credentials but still not got how to fix that.

**Comment by LukasGelke** [comment]
Hi, I'm working with @FreeAndNil. @mconnew do you have any news?
I've noticed that, `parent.ServiceCertificate.Certificate` in `CreateServerX509TokenProvider()` is always null, because (going by stacktrace) `SslStreamSecurityUpgradeProvider.CreateServerProvider(...)` creates a default ('empty') `SecurityCredentialsManager`, and that in turn is because it is passed a `BindingContext` with an empty `BindingParameterCollection` (within `HandshakeDelegate.BuildHandshakeDelegateForDispatcher(...)`).

I've tried setting `parent.ServiceCertificate.Certificate` manually in `CreateServerX509TokenProvider()` to the same certificate as in `Setup` (`builder.ConfigureServiceHostBase<EchoService>(...)`), but that just results in a completely different problem (see below), when running the NetCoreClient (with the same certificate (even tried both `factory.Credentials.ClientCertificate.SetCertificate(...)` and `factory.Credentials.ServiceCertificate.SetDefaultCertificate(...)`), NetTcpBinding, etc, run under the same user, on the same machine), so I'm unsure now what to do next.
(Note that I've of course tested the exact same sample scenario (url, binding,...) but without using a certificate, and that works)

```txt
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      ConnectionDispatcher.Execute() 0HM4DA5H0OOVG
System.ComponentModel.Win32Exception (0x8009030D): The credentials supplied to the package were not recognized
   at System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface secModule, String package, CredentialUse intent, SCHANNEL_CRED scc)
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCHANNEL_CRED secureCredential)
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(X509Certificate certificate, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
   at System.Net.Security.SecureChannel.AcquireServerCredentials(Byte[]& thumbPrint, Byte[] clientHello)
   at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
   at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessAuthentication(LazyAsyncResult lazyResult, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.BeginAuthenticateAsServer(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.BeginAuthenticateAsServer(X509Certificate serverCertificate, Boolean clientCertificateRequired, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__68_1(X509Certificate arg1, Boolean arg2, SslProtocols arg3, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2,TArg3](Func`6 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2,TArg3](Func`6 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state)
   at System.Net.Security.SslStream.AuthenticateAsServerAsync(X509Certificate serverCertificate, Boolean clientCertificateRequired, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
   at CoreWCF.Channels.SslStreamSecurityUpgradeAcceptor.OnAcceptUpgradeAsync(Stream stream) in D:\Git\CoreWCF\src\CoreWCF.Primitives\src\CoreWCF\Channels\SslStreamSecurityUpgradeProvider.cs:line 295
   at CoreWCF.Channels.StreamSecurityUpgradeAcceptorBase.AcceptUpgradeAsync(Stream stream) in D:\Git\CoreWCF\src\CoreWCF.Primitives\src\CoreWCF\Channels\StreamSecurityUpgradeAcceptorBase.cs:line 28
   at CoreWCF.Channels.Framing.ServerFramingSingletonMiddleware.UpgradeConnectionAsync(FramingConnection connection) in D:\Git\CoreWCF\src\CoreWCF.NetTcp\src\CoreWCF\Channels\Framing\ServerFramingSingletonMiddleware.cs:line 245
   at CoreWCF.Channels.Framing.ServerFramingSingletonMiddleware.OnConnectedAsync(FramingConnection connection) in D:\Git\CoreWCF\src\CoreWCF.NetTcp\src\CoreWCF\Channels\Framing\ServerFramingSingletonMiddleware.cs:line 109
   at CoreWCF.Channels.Framing.NetMessageFramingConnectionHandler.<>c__DisplayClass9_3.<<BuildHandshake>b__7>d.MoveNext() in D:\Git\CoreWCF\src\CoreWCF.NetTcp\src\CoreWCF\Channels\Framing\NetMessageFramingConnectionHandler.cs:line 63
--- End of stack trace from previous location where exception was thrown ---
   at CoreWCF.Channels.Framing.SingletonFramingMiddleware.OnConnectedAsync(FramingConnection connection) in D:\Git\CoreWCF\src\CoreWCF.NetTcp\src\CoreWCF\Channels\Framing\SingletonFramingMiddleware.cs:line 102
   at CoreWCF.Configuration.MapMiddleware.Invoke(FramingConnection connection) in D:\Git\CoreWCF\src\CoreWCF.NetTcp\src\CoreWCF\Configuration\MapMiddleware.cs:line 43
   at CoreWCF.Configuration.MapMiddleware.Invoke(FramingConnection connection) in D:\Git\CoreWCF\src\CoreWCF.NetTcp\src\CoreWCF\Configuration\MapMiddleware.cs:line 47
   at CoreWCF.Channels.Framing.FramingModeHandshakeMiddleware.OnConnectedAsync(FramingConnection connection) in D:\Git\CoreWCF\src\CoreWCF.NetTcp\src\CoreWCF\Channels\Framing\FramingModeHandshakeMiddleware.cs:line 59
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.ConnectionDispatcher.Execute(ConnectionContext connectionContext)
```

**Comment by LukasGelke** [comment]
as a follow up:
I fixed that Exception. As suspected it was a problem with the certificate. My (AD) user account did not have explicit read access to the certificates private key (changed via mmc.exe). Though i seem to be in the local administrator group for the machine (which has access). 
As a side note, in the client I had to change the endpoint `localhost` to the FQDN of my machine, since that is the address used by the certificate. (otherwise the client throws a DNS mismatch)

With that, the EchoService example works. So now, the certificate has to find its way from the callback in `Startup` into `CreateServerX509TokenProvider()`

**Comment by LukasGelke** [comment]
With minimal edits, it seemed logical to me to do this: 023be93b5259911726bd461b9a04df731148681b.
It fixes the `InvalidOperationException 'The service certificate is not provided. Specify a service certificate in ServiceCredentials.'` on host.Run(). Judging by the `Find()` in `SslStreamSecurityUpgradeProvider.CreateServerProvider(...)`, this should be the correct way to do it. I'm also not so sure about changing `IServiceDispatcher`, so I'd like hear some feedback.

The Eco example works (as expected), without modifying anything else (apart from `Startup`, and adding the certificate of course).

**Comment by MemoTrap** [comment]
> With minimal edits, it seemed logical to me to do this: 023be93.

Apparently, this didn't make it into 0.1.0.

I have applied this patch in my local copy. It also required to implement `IServiceDispatcher.ChannelDispatcher` in a few other classes, did that with placeholders, throwing not implemented.

It now does work! 😎

**Comment by pankti11** [comment]
Hello,

I am also getting the below error:

System.InvalidOperationException: 'The service certificate is not provided. Specify a service certificate in ServiceCredentials. '

This exception was originally thrown at this call stack:
    CoreWCF.Security.ServiceCredentialsSecurityTokenManager.CreateServerX509TokenProvider()
    
Code for configuring the certificate it 

```
_ = app.UseServiceModel(builder =>
			{
				builder
					.AddService<DumService>()
					.AddServiceEndpoint<DumService, IDumService>(
						new NetTcpBinding() { Security = new NetTcpSecurity { Mode = SecurityMode.Transport, Transport = new TcpTransportSecurity { ClientCredentialType = TcpClientCredentialType.Certificate } } },
						"/WcfServiceTest/")
					.ConfigureServiceHostBase<DumService>((serviceHost) =>
					serviceHost.Credentials.ServiceCertificate.SetCertificate(StoreLocation.LocalMachine, StoreName.Root, X509FindType.FindBySubjectName, "DumName"));

			});
```
 
 Has anyone solved this ?

**Comment by FreeAndNil** [comment]
@mconnew Could you take a look at the problem?

**Comment by FreeAndNil** [comment]
@mconnew the issue was fixed by https://github.com/CoreWCF/CoreWCF/commit/6ee63ce1 #331 
Thanks @birojnayak
