### ISSUE TITLE
Server needs http endpoint, although client uses only net.tcp

### ISSUE THREAD

**Issue by pushack** [CoreWCF/CoreWCF#226]
I’m using net.tcp client and my server logic is reduced to use only net.tcp:

//Program.cs
public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
            .UseNetTcp(8808)
            .UseStartup<Startup>();

//Startup.cs
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseServiceModel(builder =>
            {
                builder
                    .AddService<EchoService>()
                    .AddServiceEndpoint<EchoService, Contract.IEchoService>(new NetTcpBinding(), "/nettcp");
            });
        }

It was working fine inclusive version 0.1.0-alpha.115.
Since the next available version 0.1.0-alpha.121 I’m getting exception:

System.ArgumentException
  HResult=0x80070057
  Message=This collection already contains an address with scheme net.tcp.  There can be at most one address per scheme in this collection. If your service is being hosted in IIS you can fix the problem by setting 'system.serviceModel/serviceHostingEnvironment/multipleSiteBindingsEnabled' to true or specifying 'system.serviceModel/serviceHostingEnvironment/baseAddressPrefixFilters'. (Parameter 'item')
  Source=CoreWCF.Primitives
  StackTrace:
   at CoreWCF.UriSchemeKeyedCollection.InsertItem(Int32 index, Uri item) in C:\Users\me\Source\Repos\CoreWCF\CoreWCF\src\CoreWCF.Primitives\src\CoreWCF\UriSchemeKeyedCollection.cs:line 35
   at CoreWCF.Collections.Generic.SynchronizedCollection`1.Add(T item) in C:\Users\me\Source\Repos\CoreWCF\CoreWCF\src\CoreWCF.Primitives\src\CoreWCF\Collections\Generic\SynchronizedCollection.cs:line 96
   at CoreWCF.UriSchemeKeyedCollection..ctor(Uri[] addresses) in C:\Users\me\Source\Repos\CoreWCF\CoreWCF\src\CoreWCF.Primitives\src\CoreWCF\UriSchemeKeyedCollection.cs:line 20
   at CoreWCF.ServiceHostObjectModel`1..ctor(IServiceProvider serviceProvider, IServer server, IServiceBuilder serviceBuilder, ILogger`1 logger) in C:\Users\me\Source\Repos\CoreWCF\CoreWCF\src\CoreWCF.Primitives\src\CoreWCF\ServiceHostObjectModel.cs:line 36

After a little bit experimenting, I found, that adding http endpoint solves my exception.
The issue can be easy reproduced with samples: NetCoreClient & NetCoreServer.

**Comment by mconnew** [comment]
I suspect this was introduced by a change to support specifying port 0 to tell Kestrel to pick an available port for me. I think I have a general idea how to fix this. I'll see if it's an easy fix.

**Comment by mconnew** [comment]
This is fixed now. Turns out it wasn't an easy fix and took me 3 days to work out how to fix, but I solved some other problems while I was at it and this needed to be done before RTM.
