### ISSUE TITLE
One way async operations raising exceptions

### ISSUE THREAD

**Issue by louiswerth** [CoreWCF/CoreWCF#27]
I need to implement a pre-defined(from vendor) wsdl & xsd. They have defined the operation as "IsOneWay".

I generated the proxies using svcutil.exe using the wsdl & xsd.

If you look at the proxy, it generates it as follows:

` [XmlSerializerFormat]
        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://callback.someCompany.com/some_callback/someMethod")]
        System.Threading.Tasks.Task someMethodAsync(t_data_event request);`

When you try to start the service up, it raises the following exception:
_System.ArgumentException: .NET type CancellationToken cannot be resolved into XML schema type
   at SoapCore.MetaBodyWriter.ResolveType(Type type)
   at SoapCore.MetaBodyWriter.AddSchemaType(XmlDictionaryWriter writer, Type type, String name, Boolean isArray, String namespace)
   at SoapCore.MetaBodyWriter.AddTypes(XmlDictionaryWriter writer)
   at SoapCore.MetaBodyWriter.OnWriteBodyContents(XmlDictionaryWriter writer)
   at System.ServiceModel.Channels.Message.OnWriteBodyContentsAsync(XmlDictionaryWriter writer)
   at System.ServiceModel.Channels.Message.OnWriteMessageAsync(XmlDictionaryWriter writer)
   at System.ServiceModel.Channels.Message.WriteMessageAsync(XmlDictionaryWriter writer)
   at System.ServiceModel.Channels.TextMessageEncoderFactory.TextMessageEncoder.WriteMessageAsync(Message message, Stream stream)
   at System.ServiceModel.Channels.TextMessageEncoderFactory.TextMessageEncoder.WriteMessageAsyncInternal(Message message, Stream stream)
   at System.Runtime.TaskHelpers.WaitForCompletionNoSpin(Task task)
   at SoapCore.SoapEndpointMiddleware.ProcessMeta(HttpContext httpContext)
   at SoapCore.SoapEndpointMiddleware.ProcessOperation(HttpContext httpContext, IServiceProvider serviceProvider)
   at SoapCore.SoapEndpointMiddleware.Invoke(HttpContext httpContext, IServiceProvider serviceProvider)
   at SoapCore.SoapEndpointMiddleware.Invoke(HttpContext httpContext, IServiceProvider serviceProvider)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()_

The problem seems to be that the OneWay async implementation is not supported. In the process of finding the problem I added a return object in the code(<bool>):

`[XmlSerializerFormat] [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://callback.someCompany.com/some_callback/someMethod")] System.Threading.Tasks.Task<bool> someMethodAsync(t_data_event request);`

It then starts up, however I cannot request the vendor to change due numerous other clients not having a problem with this implementation. 

Your guidance will be appreciated.

**Comment by mconnew** [comment]
You're using SoapCore, not CoreWCF. If you provide a ServiceContract with enough methods to cover the various features you need working (we don't need 50 methods with the same operation shape) I will make sure they work.  
What would be even better would be if you could add some unit tests for your usage scenarios as that will get it working in CoreWCF quicker. If you are willing to do this, I can provide pointers on how to add tests for your scenario.

**Comment by tibor19** [comment]
You can manually change the generated code, however every time you will update the proxy, your changes will be overridden. 
One thing that I am thinking about though, is what is the point of having an async one way method? Those are fire and forget, so there will be nothing to wait for anyway.

**Comment by mconnew** [comment]
@tibor19, it's important for keeping track of call throttles. You want to have an async method so you don't block a thread waiting on something, but you don't want to release the call throttle until you have completed your work. If you don't care about throttles, then make it synchronous and call Task.Run to execute your work and have it run in the background. Otherwise async one way is an important scenario.

**Comment by mconnew** [comment]
Another thing I had forgotten is if your service implementation class implements IDisposable and you are using InstanceContextMode.PerCall or InstanceContextMode.PerSession with a sessionless binding such as BasicHttpBinding, then Dispose will be called when your operation completes. If it's sync and you kick off your implementation on a background thread and return, you could have your service instance disposed while you are still trying to use it.

**Comment by louiswerth** [comment]
Thank you for your feedback, apologies for logging for the wrong project, I will try your library
