### ISSUE TITLE
Adding reference to "Microsoft.Extensions.Hosting" Version="5.0.0" kills the service

### ISSUE THREAD

**Issue by kkkmail** [CoreWCF/CoreWCF#272]
If a project references both `CoreWCF` and `"Microsoft.Extensions.Hosting" Version="5.0.0"` (which is a substantial part of NET5), then WCF service fails to start with:
```
fail: Microsoft.AspNetCore.Server.Kestrel[0]
      Heartbeat.OnHeartbeat
      System.TypeLoadException: Could not load type 'Microsoft.Extensions.Primitives.InplaceStringBuilder' from assembly 'Microsoft.Extensions.Primitives, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
         at Microsoft.Net.Http.Headers.DateTimeFormatter.ToRfc1123String(DateTimeOffset dateTime, Boolean quoted)
         at Microsoft.Net.Http.Headers.HeaderUtilities.FormatDate(DateTimeOffset dateTime, Boolean quoted)
         at Microsoft.Net.Http.Headers.HeaderUtilities.FormatDate(DateTimeOffset dateTime)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.DateHeaderValueManager.SetDateValues(DateTimeOffset value)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.DateHeaderValueManager.OnHeartbeat(DateTimeOffset now)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.Heartbeat.OnHeartbeat()
```

This is sort of a known issue because `CoreWCF` references an obsolete package `"Microsoft.AspNetCore" Version="2.2.0"`, which, in turn, results in this error when `"Microsoft.Extensions.Hosting" Version="5.0.0"` is also used: https://github.com/dotnet/aspnetcore/issues/27986

**Known workarounds**: None so far

**Repro steps**:
1. Pull repo: https://github.com/kkkmail/Softellect/tree/kk-master then build `Release|x64` config in VS or Rider on Windows.
2. Navigate to e.g. `C:\GitHub\Softellect\Samples\Msg\MsgService\bin\x64\Release\net5.0` (adjusted to point to a local folder), then run `Softellect.Samples.Msg.Service.exe`.
3. Observe that it runs without errors.
4. Add a reference to `"Microsoft.Extensions.Hosting" Version="5.0.0"` to this project (located in `Samples\MsgService`).
5. Clean / rebuild the solution, then try running `Softellect.Samples.Msg.Service.exe`.
6. Observer that now it started producing the exception above.

This is fairly severe as reference to `"Microsoft.Extensions.Hosting" Version="5.0.0"` is pretty much a must in almost any NET5 web related app.

**Comment by mconnew** [comment]
Work to support the latest version of .NET Core will happen after the initial GA release happening later this month.

**Comment by BradBarnich** [comment]
If you are blocked, it is pretty small amount of work to cross compile to net5.0: https://github.com/BradBarnich/CoreWCF/commit/84beb95d27d1ddd2446134d2aabed2fdf98f3c73, while you wait for a proper solution from upstream.

**Comment by denisbredikhin** [comment]
@BradBarnich Hm, I see in this commit that it is about porting to .NET 5? Does it mean that CoreWCF won't be compatible with .NET Framework anymore? I read in another thread that this will happen only after the release of version 1.0.
We have the issue with Microsoft.Extensions.Hosting in .NET Framework application.

**Comment by denisbredikhin** [comment]
Ok, I've missed that this was a commit in fork.
Is there any plans when this will be available in upstream?

**Comment by denisbredikhin** [comment]
@mconnew we are blocked by this issue. Is there a way for us to work on this and create PR?

**Comment by mconnew** [comment]
I'm currently recovering from some surgery so can't look into this with any urgency. I do know many people are using it on .NET 5 & 6 without an issue. Make sure you aren't referencing any earlier aspnetcore packages in any of you projects and make sure the framework reference is in the launching project as well as any project referencing CoreWCF and I would expect it to work. If it doesn't, then the fastest way to a resolution is to provide a simplified repro solution which exhibits the problem. We run our full test suite on .NET 5 & 6 so it's definitialy a working scenario, which means there's something different about your project. I can't guess what that difference is which is why a basic repro solution is needed.

**Comment by denisbredikhin** [comment]
@mconnew we are working in .NET Framework but referencing Microsoft.Extensions.Hosting" Version=5.0.0, which targets .NET Standard 2.0, so it is a valid scenario.
I will ask our developers to make minimal example or test.

**Comment by mconnew** [comment]
If you are running on framework, the problem with using a 5.0 version of the package is a compatibility problem with aspnetcore. Running on framework, you can only use asp.net core 2.1. I would expect you to have the same problem with an asp.net core app not involving CoreWCF running on framework.

**Comment by denisbredikhin** [comment]
@mconnew that you for your explanation. Now I understand this is issue not in CoreWCF. We need to use package of version 2.1.  Currently we can't because we have dependency which requires version 5.0. So this is issue in this dependency, it should use 2.1 when it targets .NET Framework.

**Comment by mconnew** [comment]
If you specify using the 2.1 version as a direct dependency in your app it will override whatever any over dependency is trying to pull it. As long as they aren't using api's which only exist in the newest version of the package, that has a good chance of working.
