### ISSUE TITLE
NetTcpBinding doesnt support TransportWithMessageCredentials in GA 0.1.0

### ISSUE THREAD

**Issue by john-e-lewis** [CoreWCF/CoreWCF#314]
I'm migrating an existing WCF app to CoreWCF GA 0.1.0 and aim to support deployment to windows and linux.  The app uses NetTcpBinding with TransportWithMessageCredentials security.

The original wcf service configuration is set up as

```
<netTcpBinding>
 <binding>
  <security mode="TransportWithMessageCredential">
     <transport clientCredentialType="Certificate" protectionLevel="EncryptAndSign" />
     <message clientCredentialType="UserName" />
    </security>
 </binding>
 </netTcpBinding>
```

My CoreWCF config looks like

```
var binding = new CoreWCF.NetTcpBinding(CoreWCF.SecurityMode.TransportWithMessageCredential);
binding.Security.Transport.ClientCredentialType = CoreWCF.TcpClientCredentialType.Certificate;
binding.Security.Transport.ProtectionLevel = System.Net.Security.ProtectionLevel.EncryptAndSign;
// binding.Security.Message.ClientCredentialType = CoreWCF.MessageCredentialType.UserName;
```

Note, the binding.Security,Message field is not available in NetTcpBinding in CoreWCF.
 

I get the following exception

```
System.NotSupportedException
  HResult=0x80131515
  Message=The value 'TransportWithMessageCredential' is not supported in this context for the binding security property 'Mode'.
  Source=CoreWCF.NetTcp
  StackTrace:
   at CoreWCF.NetTcpBinding.CheckSettings() in E:\TE_Git\CoreWcf\src\CoreWCF.NetTcp\src\CoreWCF\NetTcpBinding.cs:line 144
   at CoreWCF.NetTcpBinding.CreateBindingElements() in E:\TE_Git\CoreWcf\src\CoreWCF.NetTcp\src\CoreWCF\NetTcpBinding.cs:line 148
   at CoreWCF.Channels.CustomBinding.SafeCreateBindingElements(Binding binding) in E:\TE_Git\CoreWcf\src\CoreWCF.Primitives\src\CoreWCF\Channels\CustomBinding.cs:line 65
   at CoreWCF.Channels.CustomBinding..ctor(Binding binding) in E:\TE_Git\CoreWcf\src\CoreWCF.Primitives\src\CoreWCF\Channels\CustomBinding.cs:line 55
   at CoreWCF.Channels.Binding.GetProperty[T](BindingParameterCollection parameters) in E:\TE_Git\CoreWcf\src\CoreWCF.Primitives\src\CoreWCF\Channels\Binding.cs:line 222
   at CoreWCF.Configuration.ServiceModelApplicationBuilderExtensions.UseServiceModel(IApplicationBuilder app, Action`1 configureServices) in E:\TE_Git\CoreWcf\src\CoreWCF.Primitives\src\CoreWCF\Configuration\ServiceModelApplicationBuilderExtensions.cs:line 48
   at tidalsoft.exs.TcpHostService.Core.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, IHostApplicationLifetime lifetime) in E:\Explorer_Core\BuildArea\TidalExplorer\TE-Service\tidalsoft.exs.TcpHostService.Core\Startup.cs:line 52
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.<StartAsync>d__31.MoveNext()
```

Can this be addressed as a fix to the GA 0.1 release.

Other that this, all of the other CoreWCF 0.1 GA features used including Windows Authentication have worked well.

Thanks for the great work.

**Comment by birojnayak** [comment]
taking a look

**Comment by birojnayak** [comment]
@john-e-lewis please close this issue as we added the support in 0.2.0 release

**Comment by john-e-lewis** [comment]
Great work,
