### ISSUE TITLE
SSL/TLS support for https with BasicHttpBinding?

### ISSUE THREAD

**Issue by MZar2019** [CoreWCF/CoreWCF#32]
Does CoreWCF have SSL/TLS support when using the BasicHttpBinding?

**Comment by MZar2019** [comment]
@mconnew 
Maybe I'm doing something wrong.

I build my TLS host:

public Host(Uri baseUri, X509Certificate2 certificate)
{
    WebHost = new WebHostBuilder()
                .UseUrls($"baseUri")
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseKestrel()
                .ConfigureKestrel(options =>
                {
                    options.ConfigureHttpsDefaults(https =>
                    {
                        https.ServerCertificate = certificate;
                        https.SslProtocols = SslProtocols.Tls12;
                        https.ClientCertificateMode = ClientCertificateMode.NoCertificate;
                    });
                })
                .ConfigureLogging(config =>
                {
                    config.ClearProviders();
                    config.SetMinimumLevel(LogLevel.Debug);
                    config.AddDebug();
                    config.AddEventSourceLogger();
                    config.AddConsole();
                })
               .UseStartup<Startup>()
               .Build();
}

public class Startup
{
...
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddServiceModelServices();
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseServiceModel(builder =>
            {
                builder.AddService<Dispatcher>();
                builder.AddServiceEndpoint<Dispatcher, IMyAPI>(new BasicHttpBinding(), "/MyService");
        }
    }
}

Note: There's no BasicHttpBinding in CoreWCF that allows me to specify BasicHttpSecurityMode.Transport, though there is one on System.ServiceModel.Primitives.

When I try to open the Host, the error is:

Could not find a base address that matches scheme http for the endpoint with binding BasicHttpBinding. Registered base address schemes are [https].    at CoreWCF.ServiceHostObjectModel`1.MakeAbsoluteUri(Uri uri, Binding binding)
   at CoreWCF.Description.DispatcherBuilder.BuildDispatcher[TService](ServiceConfiguration`1 serviceConfig, IServiceProvider services)
   at CoreWCF.Configuration.ServiceConfiguration`1.GetDispatchers()
   at CoreWCF.Configuration.DispatcherBuilderImpl.BuildDispatchers(Type serviceType)
   at CoreWCF.Channels.ServiceModelHttpMiddleware.BuildBranch(IApplicationBuilder app, IServiceBuilder serviceBuilder, IDispatcherBuilder dispatcherBuilder)
   at CoreWCF.Channels.ServiceModelHttpMiddleware..ctor(RequestDelegate next, IApplicationBuilder app, IServiceBuilder serviceBuilder, IDispatcherBuilder dispatcherBuilder)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at UnitTests.CustomerAPI.OpenCloseHost._OpenSecureTls(Int32 delay, SslProtocols tls) in E:\source\Libraries\Test\UnitTests\API\OpenCloseHost.cs:line 63

**Comment by mconnew** [comment]
You are doing everything correctly. I will get this scenario to work and update this issue when it's working.

**Comment by AAATechGuy** [comment]
We need this feature as well.

**Comment by mconnew** [comment]
@MZar2019, this is now working. New packages should be available very soon. Please re-open this issue is you still have problems.
