### ISSUE TITLE
System.PlatformNotSupportedException: Server implementation is not supported

### ISSUE THREAD

**Issue by wxb1** [CoreWCF/CoreWCF#34]
I published the NetCoreServer and NetCoreClient to linux binaries. The development machine is windows 10 os. I took the  binaries to a my ubuntu machine and tried to launch them there. Initially, the server launches ok but once I launch the client I get the following errors:

[Server]
(xenial)wbuckner@localhost:~/Documents/NetCoreServer/netcoreapp2.2
/linux-x64/publish$ ./NetCoreServer
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Overriding address(es) 'http://localhost:8080'. Binding to endpoints defined in UseKestrel() instead.
Hosting environment: Production
Content root path: /home/wbuckner/Documents/NetCoreServer/netcoreapp2.2/linux-x64/publish
Now listening on: http://localhost:8080
Now listening on: http://0.0.0.0:8808
Application started. Press Ctrl+C to shut down.
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      ConnectionDispatcher.Execute() 0HLP8L48PMSGK
System.PlatformNotSupportedException: Server implementation is not supported
   at System.Net.Security.NegotiateStreamPal.AcquireCredentialsHandle(String package, Boolean isServer, NetworkCredential credential)
   at System.Net.Security.NegotiateStreamPal.AcquireDefaultCredential(String package, Boolean isServer)
   at System.Net.NTAuthentication.Initialize(Boolean isServer, String package, NetworkCredential credential, String spn, ContextFlagsPal requestedContextFlags, ChannelBinding channelBinding)
   at System.Net.Security.NegoState.ValidateCreateContext(String package, Boolean isServer, NetworkCredential credential, String servicePrincipalName, ChannelBinding channelBinding, ProtectionLevel protectionLevel, TokenImpersonationLevel impersonationLevel)
   at System.Net.Security.NegoState.ValidateCreateContext(String package, NetworkCredential credential, String servicePrincipalName, ExtendedProtectionPolicy policy, ProtectionLevel protectionLevel, TokenImpersonationLevel impersonationLevel)
   at System.Net.Security.NegotiateStream.BeginAuthenticateAsServer(NetworkCredential credential, ExtendedProtectionPolicy policy, ProtectionLevel requiredProtectionLevel, TokenImpersonationLevel requiredImpersonationLevel, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.NegotiateStream.BeginAuthenticateAsServer(NetworkCredential credential, ProtectionLevel requiredProtectionLevel, TokenImpersonationLevel requiredImpersonationLevel, AsyncCallback asyncCallback, Object asyncState)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2,TArg3](Func`6 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state)
   at System.Net.Security.NegotiateStream.AuthenticateAsServerAsync(NetworkCredential credential, ProtectionLevel requiredProtectionLevel, TokenImpersonationLevel requiredImpersonationLevel)
   at CoreWCF.Channels.WindowsStreamSecurityUpgradeProvider.WindowsStreamSecurityUpgradeAcceptor.OnAcceptUpgradeAsync(Stream stream) in C:\CoreWCF\src\CoreWCF.Primitives\src\CoreWCF\Channels\WindowsStreamSecurityUpgradeProvider.cs:line 145
   at CoreWCF.Channels.StreamSecurityUpgradeAcceptorBase.AcceptUpgradeAsync(Stream stream) in C:\CoreWCF\src\CoreWCF.Primitives\src\CoreWCF\Channels\StreamSecurityUpgradeAcceptorBase.cs:line 28
   at CoreWCF.Channels.Framing.ServerFramingDuplexSessionMiddleware.UpgradeConnectionAsync(FramingConnection connection) in C:\CoreWCF\src\CoreWCF.NetTcp\src\CoreWCF\Channels\Framing\ServerFramingDuplexSessionMiddleware.cs:line 155
   at CoreWCF.Channels.Framing.ServerFramingDuplexSessionMiddleware.OnConnectedAsync(FramingConnection connection) in C:\CoreWCF\src\CoreWCF.NetTcp\src\CoreWCF\Channels\Framing\ServerFramingDuplexSessionMiddleware.cs:line 65
   at CoreWCF.Channels.Framing.NetMessageFramingConnectionHandler.<>c__DisplayClass4_1.<<BuildHandshake>b__5>d.MoveNext() in C:\CoreWCF\src\CoreWCF.NetTcp\src\CoreWCF\Channels\Framing\NetMessageFramingConnectionHandler.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at CoreWCF.Channels.Framing.DuplexFramingMiddleware.OnConnectedAsync(FramingConnection connection) in C:\CoreWCF\src\CoreWCF.NetTcp\src\CoreWCF\Channels\Framing\DuplexFramingMiddleware.cs:line 68
   at CoreWCF.Configuration.MapMiddleware.Invoke(FramingConnection connection) in C:\CoreWCF\src\CoreWCF.NetTcp\src\CoreWCF\Configuration\MapMiddleware.cs:line 43
   at CoreWCF.Channels.Framing.FramingModeHandshakeMiddleware.OnConnectedAsync(FramingConnection connection) in C:\CoreWCF\src\CoreWCF.NetTcp\src\CoreWCF\Channels\Framing\FramingModeHandshakeMiddleware.cs:line 22
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.ConnectionDispatcher.Execute(KestrelConnection connection)

[Client]
(xenial)wbuckner@localhost:~/Documents/NetCoreClient/netcoreapp2.2
/linux-x64/publish$ ./NetCoreClient

Unhandled Exception: System.ServiceModel.Security.SecurityNegotiationException: Authentication failed, see inner exception. ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> System.ComponentModel.Win32Exception: GSSAPI operation failed with error - An invalid status code was supplied (SPNEGO cannot find mechanisms to negotiate).
   --- End of inner exception stack trace ---
   at System.Net.Security.NegoState.StartSendAuthResetSignal(LazyAsyncResult lazyResult, Byte[] message, Exception exception)
   at System.Net.Security.NegoState.StartSendBlob(Byte[] message, LazyAsyncResult lazyResult)
   at System.Net.Security.NegoState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.NegotiateStream.BeginAuthenticateAsClient(NetworkCredential credential, ChannelBinding binding, String targetName, ProtectionLevel requiredProtectionLevel, TokenImpersonationLevel allowedImpersonationLevel, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.NegotiateStream.BeginAuthenticateAsClient(NetworkCredential credential, String targetName, ProtectionLevel requiredProtectionLevel, TokenImpersonationLevel allowedImpersonationLevel, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.NegotiateStream.<>c__DisplayClass27_0.<AuthenticateAsClientAsync>b__0(AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   at System.Net.Security.NegotiateStream.AuthenticateAsClientAsync(NetworkCredential credential, String targetName, ProtectionLevel requiredProtectionLevel, TokenImpersonationLevel allowedImpersonationLevel)
   at System.ServiceModel.Channels.WindowsStreamSecurityUpgradeProvider.WindowsStreamSecurityUpgradeInitiator.OnInitiateUpgradeAsync(Stream stream, OutWrapper`1 remoteSecurity)
   --- End of inner exception stack trace ---
   at System.ServiceModel.Channels.WindowsStreamSecurityUpgradeProvider.WindowsStreamSecurityUpgradeInitiator.OnInitiateUpgradeAsync(Stream stream, OutWrapper`1 remoteSecurity)
   at System.ServiceModel.Channels.StreamSecurityUpgradeInitiatorBase.InitiateUpgradeAsync(Stream stream)
   at System.ServiceModel.Channels.ConnectionUpgradeHelper.InitiateUpgradeAsync(StreamUpgradeInitiator upgradeInitiator, OutWrapper`1 connectionWrapper, ClientFramingDecoder decoder, IDefaultCommunicationTimeouts defaultTimeouts, TimeSpan timeout)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.SendPreambleAsync(IConnection connection, ArraySegment`1 preamble, TimeSpan timeout)
   at System.ServiceModel.Channels.ConnectionPoolHelper.EstablishConnectionAsync(TimeSpan timeout)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.OnOpenAsync(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.OnOpenAsyncInternal(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.System.ServiceModel.IAsyncCommunicationObject.OpenAsync(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.OpenAsyncInternal(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.Runtime.TaskHelpers.CallActionAsync[TArg](Action`1 action, TArg argument)
   at System.ServiceModel.Channels.CommunicationObject.OpenOtherAsync(ICommunicationObject other, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.OnOpenAsync(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.OnOpenAsyncInternal(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.System.ServiceModel.IAsyncCommunicationObject.OpenAsync(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.OpenAsyncInternal(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.System.ServiceModel.ICommunicationObject.Open()
   at NetCoreClient.Program.Main(String[] args) in C:\CoreWCF\src\Samples\NetCoreClient\Program.cs:line 14
Aborted (core dumped)

**Comment by mconnew** [comment]
I did actually test CoreWCF using AspNetCore 2.1 on .NET Core 3.0 and everything works. This was on Windows though, not Linux. Could you try that combination on Linux as I expect that to work?

**Comment by wxb1** [comment]
To be perfectly honest... I am not sure how to do that. I did build CoreWCF using core 3.0 preview. It built just fine but the results were the same on linux... These are the samples I was trying to build. It already looked like the project sdk was set properly (NetCoreServer/NetCoreClient).  Both of these samples work fine on Windows...

**Comment by mconnew** [comment]
Modify the samples .csproj file to include netcoreapp3.0. If you want to only produce an app for .NET Core 3.0, remove the targetramework**s** property and replace it with a targetframework proeprty (no "s") and set it to netcoreapp3.0.

**Comment by wxb1** [comment]
Thanks. I think I actually did try that on ubutnu. I don't think it worked. I'll try it again...

**Comment by mconnew** [comment]
I have been talking with the owners of NegotiateStream and here's what I know so far. NegotiateStream isn't fully supported on Linux. For example, localhost NTLM isn't known to be working. You should be able to get it working using Kerberos, but you have to set up your server with Kerberos correctly. You should be able to follow the [documentation here](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-3.0&tabs=visual-studio#linux-and-macos-environment-configuration) to set things up correctly.

**Comment by birojnayak** [comment]
It should work now with this PR => https://github.com/CoreWCF/CoreWCF/pull/133 .. tested in my mac.. feel free to close this issue or let us know if you are having this issue.
