### ISSUE TITLE
Linux net.tcp TcpClientCredentialType.Windows

### ISSUE THREAD

**Issue by ewinnington** [CoreWCF/CoreWCF#360]
Has anyone got TcpClientCredentialType.Windows working on an AspNet net5.0 linux host? 

I don't really understand all the steps necessary to configure the docker image for a linux hosted AspNet to pass the credentials along. 

I have my current tries here  https://github.com/ewinnington/Server-Client-Communication-WCF 

For the moment, it works on Linux with SecurityMode = None, what do I need to setup for it to work with Transport security and CredentialType.Windows? What should I run on my linux Docker and must I have an AD Server?

            NetTcpBinding binding = new NetTcpBinding();
            binding.TransferMode = TransferMode.Streamed;

            //I'd like to remove this IF statement 
            if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
            {
                binding.Security.Mode = SecurityMode.None;
            }
            else
            {
                binding.Security.Mode = SecurityMode.Transport;
                binding.Security.Transport.ClientCredentialType = TcpClientCredentialType.Windows;
            }

Exception is: 
```
crit: Microsoft.AspNetCore.Server.Kestrel[0]
ConnectionDispatcher.Execute() 0HM8M9F4MDR0I
CoreWCF.Security.SecurityNegotiationException: Authentication failed, see inner exception.
---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
---> System.ComponentModel.Win32Exception (0x80090020): GSSAPI operation failed with error - Unspecified GSS failure. Minor code may provide more information (Keytab FILE:/etc/krb5.keytab is nonexistent or empty).

--- End of inner exception stack trace ---
at System.Net.Security.NegotiateStream.SendAuthResetSignalAndThrowAsync[TAdapter](TAdapter adapter, Byte[] message, Exception exception)
at System.Net.Security.NegotiateStream.SendBlobAsync[TAdapter](TAdapter adapter, Byte[] message)
at System.Net.Security.NegotiateStream.ReceiveBlobAsync[TAdapter](TAdapter adapter)
at System.Net.Security.NegotiateStream.AuthenticateAsync[TAdapter](TAdapter adapter, String callerName)
at CoreWCF.Channels.WindowsStreamSecurityUpgradeProvider.WindowsStreamSecurityUpgradeAcceptor.OnAcceptUpgradeAsync(Stream stream)

--- End of inner exception stack trace ---
at CoreWCF.Channels.WindowsStreamSecurityUpgradeProvider.WindowsStreamSecurityUpgradeAcceptor.OnAcceptUpgradeAsync(Stream stream)
at CoreWCF.Channels.StreamSecurityUpgradeAcceptorBase.AcceptUpgradeAsync(Stream stream)
at CoreWCF.Channels.Framing.ServerFramingSingletonMiddleware.UpgradeConnectionAsync(FramingConnection connection)
at CoreWCF.Channels.Framing.ServerFramingSingletonMiddleware.OnConnectedAsync(FramingConnection connection)
at CoreWCF.Channels.Framing.NetMessageFramingConnectionHandler.<>c__DisplayClass9_3.<<BuildHandshake>b__7>d.MoveNext()
--- End of stack trace from previous location ---
at CoreWCF.Channels.Framing.SingletonFramingMiddleware.OnConnectedAsync(FramingConnection connection)
at CoreWCF.Configuration.MapMiddleware.Invoke(FramingConnection connection)
at CoreWCF.Configuration.MapMiddleware.Invoke(FramingConnection connection)
at CoreWCF.Channels.Framing.FramingModeHandshakeMiddleware.OnConnectedAsync(FramingConnection connection)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.ConnectionDispatcher.Execute(KestrelConnection connection)
```

**Comment by birojnayak** [comment]
It should work.. I have done some testing around it in .net core3.1... one thing to ensure that keytab file is present.. it's complaining that "FILE:/etc/krb5.keytab is nonexistent or empty"... here is a link https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-5.0&tabs=visual-studio#linux-and-macos-environment-configuration

**Comment by ewinnington** [comment]
Thanks a lot, I'm working on getting an environment setup to test this correctly.
