### ISSUE TITLE
Issue after upgrade to 0.2.0 -CoreWCF.Configuration.ServiceBuilder, cannot be used for communication because it is in the Faulted state

### ISSUE THREAD

**Issue by cszczotka** [CoreWCF/CoreWCF#396]
Hi,
After upgrade nuget -s to version 0.2.0 I see such issue for .net core 3.1 service running on IIS . Do you know what can be wrong ?

2021-08-02 08:48:16.8224|20|-|ERROR|Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext+Log.ApplicationError|Connection ID "12682136552285962056", Request ID "80007f9f-0000-b000-b63f-84710c7967bb": An unhandled exception was thrown by the application.Exception class: CommunicationObjectFaultedException
Message: The communication object, CoreWCF.Configuration.ServiceBuilder, cannot be used for communication because it is in the Faulted state.
Source: CoreWCF.Primitives

Stack Trace:    at CoreWCF.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   at CoreWCF.ServiceHostObjectModel`1.WaitForServiceBuilderOpening(ServiceBuilder serviceBuilder)
   at CoreWCF.ServiceHostObjectModel`1..ctor(IServiceProvider serviceProvider, ServiceBuilder serviceBuilder, ILogger`1 logger)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at CoreWCF.Description.DispatcherBuilder.BuildDispatcher[TService](ServiceConfiguration`1 serviceConfig, IServiceProvider services)
   at CoreWCF.Configuration.ServiceConfiguration`1.GetDispatchers()
   at CoreWCF.Configuration.DispatcherBuilderImpl.BuildDispatchers(Type serviceType)
   at CoreWCF.Channels.ServiceModelHttpMiddleware.BuildBranch()
   at CoreWCF.Channels.ServiceModelHttpMiddleware.EnsureBranchBuilt()
   at CoreWCF.Channels.ServiceModelHttpMiddleware.BuildBranchAndInvoke(HttpContext request)
   at CoreWCF.Channels.ServiceModelHttpMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()  (Depth: 0)

**Comment by mconnew** [comment]
Are there any other exceptions thrown before this? Would you be able to provide the code for how you configure IIS with the host builder?

**Comment by cszczotka** [comment]
Hi,
Look like this issue is related with multiple bindings on my IIS for example bindings:
localhost:8080
*:8080
hostname:8080

If I leave one binding *:8080 I don;t see this exception.

This code is standard:

`public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureLogging(logging => {
                    logging.AddFile("C:/logs/soap-api-{Date}.txt");
                    logging.AddConsole();
                })
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }

    public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddServiceModelServices();
            services.Configure<IISServerOptions>(options =>
            {
                options.AllowSynchronousIO = true;

            });

            services.AddLogging(config =>
            {
                config.AddDebug();
                config.AddConsole();
            });
            services.AddControllers();
            services.AddTransient<MyService>();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseRouting();

            app.UseServiceModel(builder => {

                builder.AddService<MyService>()
                .AddServiceEndpoint<MyService, IMyService>(new BasicHttpBinding(), "/myservice.svc");

            });
            
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }
    }

`

**Comment by mconnew** [comment]
This an unfixed bug with IIS hosting when using https and using the * or + in place of the hostname. There's also a bug which I've fixed and should be released later today which causes problems when you have multiple listen addresses for the same scheme (e.g. http or https). The fix is to key on the scheme and port number, but it's still going to have a problem with the same scheme and port number but different hostnames. So for example, you won't be able to use http://0.0.0.0:8080 (0.0.0.0 means all ipv4 addresses) and http://localhost:8080.

**Comment by cszczotka** [comment]
Ok. Thanks. I have also noticed in https://github.com/CoreWCF/CoreWCF/blob/main/src/CoreWCF.Primitives/src/CoreWCF/ServiceHostObjectModel.cs FixUri method
`...
else if (address.StartsWith("https://+:", StringComparison.OrdinalIgnoreCase) ||
                         address.StartsWith("https://+/", StringComparison.OrdinalIgnoreCase) ||
                         address.StartsWith("https://*:", StringComparison.OrdinalIgnoreCase) ||
                         address.StartsWith("https://*/", StringComparison.OrdinalIgnoreCase))
                {
                    address = "https://localhost" + address.Substring(8);
                }
...
`
imho should be rather address.Substring(9) right ?

**Comment by mconnew** [comment]
That is the problem I mentioned about using https and using * or +. If you don't use those, then it should work fine with the 0.2.1 release which has just been released yesterday. Can you give 0.2.1 a try and let me know if it fixes your problem.

**Comment by mconnew** [comment]
Closing as I believe 0.2.1 fixes the issue. Please reopen if that's not the case.

**Comment by absinghal** [comment]
Getting the following error when hosting on IIS
```
Connection ID "17942340938529506164", Request ID "80000375-0005-f900-b63f-84710c7967bb": An unhandled exception was thrown by the application.

Exception: 
System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at CoreWCF.ServiceHostObjectModel`1.FixUri(String address)
   at CoreWCF.ServiceHostObjectModel`1.ApplyConfiguration()
   at CoreWCF.ServiceHostBase.InitializeDescription(UriSchemeKeyedCollection baseAddresses)
   at CoreWCF.ServiceHostObjectModel`1..ctor(IServiceProvider serviceProvider, ServiceBuilder serviceBuilder, ILogger`1 logger)
```

I am using a IIS site binding with hostname as follows
`*.edu.qa.appsnirvana.com`

I believe error is coming from [this](https://github.com/CoreWCF/CoreWCF/blob/c370e8661bb25018e7631bb33a47ee7bf465a4a6/src/CoreWCF.Primitives/src/CoreWCF/ServiceHostObjectModel.cs#L259) line of code 

Uri constructor does not recognize *.

As a workaround, we can skip addresses with wildcard.

**Comment by absinghal** [comment]
@mconnew have implemented like below and seems to be working fine.

https://github.com/absinghal/CoreWCF/commit/dda3eedd73c4973a7a77bad79b9cd4ef5d06e6f2
