### ISSUE TITLE
Exception after updating from 0.1.0-alpha.113 to 0.2.1: 'The base type 'CoreWCF.Channels.ServiceChannelProxy' cannot be sealed. (Parameter 'TProxy')'

### ISSUE THREAD

**Issue by 0x53A** [CoreWCF/CoreWCF#430]
I had a working setup with a .NET 5 server and a .NET Framework client using NetHttpBinding with client callbacks.

After only updating the CoreWcf version from 0.1.0-alpha.113 to 0.2.1, the server fails with 

```
An unhandled exception has occurred while executing the request.
      CoreWCF.CommunicationException: The remote party closed the WebSocket connection without completing the close handshake.
       ---> System.Net.WebSockets.WebSocketException (997): The remote party closed the WebSocket connection without completing the close handshake. ---> Microsoft.AspNetCore.Connections.ConnectionResetException: An existing connection was forcibly closed by the remote host.
       ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitableEventArgs.<GetResult>g__ThrowSocketException|7_0(SocketError e)
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketAwaitableEventArgs.GetResult()
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.ProcessReceives()
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.DoReceive()
         --- End of inner exception stack trace ---
         at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
         at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
         at System.IO.Pipelines.Pipe.GetReadAsyncResult()
         at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1UpgradeMessageBody.ReadAsyncInternalAwaited(ValueTask`1 readTask, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 destination, CancellationToken cancellationToken)
         at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
         at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
         at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
         at CoreWCF.Channels.WebSocketTransportDuplexSessionChannel.WebSocketMessageSource.ReadBufferedMessageAsync()
         --- End of inner exception stack trace ---
         at CoreWCF.Channels.WebSocketTransportDuplexSessionChannel.ThrowOnPendingException(Exception& pendingException)
         at CoreWCF.Channels.WebSocketTransportDuplexSessionChannel.WebSocketMessageSource.GetPendingMessage()
         at CoreWCF.Channels.WebSocketTransportDuplexSessionChannel.WebSocketMessageSource.ReceiveAsync(CancellationToken token)
         at CoreWCF.Channels.SynchronizedMessageSource.ReceiveAsync(CancellationToken token)
         at CoreWCF.Channels.TransportDuplexSessionChannel.ReceiveAsync(CancellationToken token)
         at CoreWCF.Channels.TransportDuplexSessionChannel.TryReceiveAsync(CancellationToken token)
         at CoreWCF.Channels.TransportDuplexSessionChannel.StartReceivingAsync()
         at CoreWCF.Channels.RequestDelegateHandler.HandleRequest(HttpContext context)
         at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
         at CoreWCF.Channels.ServiceModelHttpMiddleware.InvokeAsync(HttpContext context)
```

When attaching a debugger, I can see the underlying exception:

```
System.ArgumentException: 'The base type 'CoreWCF.Channels.ServiceChannelProxy' cannot be sealed. (Parameter 'TProxy')'
```

```
>	System.Reflection.DispatchProxy.dll!System.Reflection.DispatchProxyGenerator.GenerateProxyType(System.Type baseType, System.Type interfaceType)	Unknown
 	System.Reflection.DispatchProxy.dll!System.Reflection.DispatchProxyGenerator.GetProxyType(System.Type baseType, System.Type interfaceType)	Unknown
 	System.Reflection.DispatchProxy.dll!System.Reflection.DispatchProxyGenerator.CreateProxyInstance(System.Type baseType, System.Type interfaceType)	Unknown
 	System.Reflection.DispatchProxy.dll!System.Reflection.DispatchProxy.Create<R5dLib.RemotingContracts.Contracts.ebosYc.IEbosYcAPIClientCallback, CoreWCF.Channels.ServiceChannelProxy>()	Unknown
 	CoreWCF.Primitives.dll!CoreWCF.Channels.ServiceChannelProxy.CreateProxy<R5dLib.RemotingContracts.Contracts.ebosYc.IEbosYcAPIClientCallback>(CoreWCF.Description.MessageDirection direction, CoreWCF.Channels.ServiceChannel serviceChannel)	Unknown
 	CoreWCF.Primitives.dll!CoreWCF.Channels.ServiceChannelFactory.CreateProxyWithType<R5dLib.RemotingContracts.Contracts.ebosYc.IEbosYcAPIClientCallback>(CoreWCF.Description.MessageDirection direction, CoreWCF.Channels.ServiceChannel serviceChannel)	Unknown
 	CoreWCF.Primitives.dll!CoreWCF.Channels.ServiceChannelFactory.CreateProxy(System.Type interfaceType, System.Type proxiedType, CoreWCF.Description.MessageDirection direction, CoreWCF.Channels.ServiceChannel serviceChannel)	Unknown
 	CoreWCF.Primitives.dll!CoreWCF.Dispatcher.ChannelHandler.InitializeServiceChannel(CoreWCF.Channels.ServiceChannel channel)	Unknown
 	CoreWCF.Primitives.dll!CoreWCF.Dispatcher.ChannelHandler.GetSessionChannel(CoreWCF.Channels.Message message, out CoreWCF.Dispatcher.EndpointDispatcher endpoint, out bool addressMatched)	Unknown
 	CoreWCF.Primitives.dll!CoreWCF.Dispatcher.ChannelHandler.EnsureChannelAndEndpointAsync(CoreWCF.Channels.RequestContext request, CoreWCF.Dispatcher.ChannelHandler.RequestInfo requestInfo)	Unknown
 	CoreWCF.Primitives.dll!CoreWCF.Dispatcher.ChannelHandler.TryRetrievingInstanceContextCoreAsync(CoreWCF.Channels.RequestContext request, CoreWCF.Dispatcher.ChannelHandler.RequestInfo requestInfo)	Unknown
 	CoreWCF.Primitives.dll!CoreWCF.Dispatcher.ChannelHandler.TryRetrievingInstanceContextAsync(CoreWCF.Channels.RequestContext request, CoreWCF.Dispatcher.ChannelHandler.RequestInfo requestInfo)	Unknown
 	CoreWCF.Primitives.dll!CoreWCF.Dispatcher.ChannelHandler.HandleRequestAsync(CoreWCF.Channels.RequestContext request)	Unknown
 	CoreWCF.Primitives.dll!CoreWCF.Dispatcher.ChannelHandler.DispatchAsync(CoreWCF.Channels.RequestContext requestContext)	Unknown
 	CoreWCF.Primitives.dll!CoreWCF.Dispatcher.DuplexChannelBinder.DispatchAsync(CoreWCF.Channels.Message message)	Unknown
 	CoreWCF.Http.dll!CoreWCF.Channels.TransportDuplexSessionChannel.StartReceivingAsync()	Unknown
 	[Resuming Async Method]	
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.AsyncStateMachineBox<CoreWCF.Channels.TransportDuplexSessionChannel.<StartReceivingAsync>d__37>.ExecutionContextCallback(object s)	Unknown
 	System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.AsyncStateMachineBox<CoreWCF.Channels.TransportDuplexSessionChannel.<StartReceivingAsync>d__37>.MoveNext(System.Threading.Thread threadPoolThread)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.AsyncStateMachineBox<CoreWCF.Channels.TransportDuplexSessionChannel.<StartReceivingAsync>d__37>.MoveNext()	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__12_0(System.Action innerContinuation, System.Threading.Tasks.Task innerTask)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task.RunContinuations(object continuationObject)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task<(CoreWCF.Channels.Message, bool)>.TrySetResult((CoreWCF.Channels.Message, bool) result)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<(CoreWCF.Channels.Message, bool)>.SetExistingTaskResult(System.Threading.Tasks.Task<(CoreWCF.Channels.Message, bool)> task, (CoreWCF.Channels.Message, bool) result)	Unknown
 	[Completed] CoreWCF.Http.dll!CoreWCF.Channels.TransportDuplexSessionChannel.TryReceiveAsync(System.Threading.CancellationToken token)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<(CoreWCF.Channels.Message, bool)>.AsyncStateMachineBox<CoreWCF.Channels.TransportDuplexSessionChannel.<TryReceiveAsync>d__39>.ExecutionContextCallback(object s)	Unknown
 	System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<(CoreWCF.Channels.Message, bool)>.AsyncStateMachineBox<CoreWCF.Channels.TransportDuplexSessionChannel.<TryReceiveAsync>d__39>.MoveNext(System.Threading.Thread threadPoolThread)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<(System.__Canon, bool)>.AsyncStateMachineBox<CoreWCF.Channels.TransportDuplexSessionChannel.<TryReceiveAsync>d__39>.MoveNext()	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__12_0(System.Action innerContinuation, System.Threading.Tasks.Task innerTask)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task.RunContinuations(object continuationObject)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task<System.__Canon>.TrySetResult(System.__Canon result)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.SetExistingTaskResult(System.Threading.Tasks.Task<System.__Canon> task, System.__Canon result)	Unknown
 	[Completed] CoreWCF.Http.dll!CoreWCF.Channels.TransportDuplexSessionChannel.ReceiveAsync(System.Threading.CancellationToken token)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<CoreWCF.Channels.Message>.AsyncStateMachineBox<CoreWCF.Channels.TransportDuplexSessionChannel.<ReceiveAsync>d__38>.ExecutionContextCallback(object s)	Unknown
 	System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<CoreWCF.Channels.Message>.AsyncStateMachineBox<CoreWCF.Channels.TransportDuplexSessionChannel.<ReceiveAsync>d__38>.MoveNext(System.Threading.Thread threadPoolThread)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.AsyncStateMachineBox<CoreWCF.Channels.TransportDuplexSessionChannel.<ReceiveAsync>d__38>.MoveNext()	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__12_0(System.Action innerContinuation, System.Threading.Tasks.Task innerTask)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task.RunContinuations(object continuationObject)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task<System.__Canon>.TrySetResult(System.__Canon result)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.SetExistingTaskResult(System.Threading.Tasks.Task<System.__Canon> task, System.__Canon result)	Unknown
 	[Completed] CoreWCF.Http.dll!CoreWCF.Channels.SynchronizedMessageSource.ReceiveAsync(System.Threading.CancellationToken token)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<CoreWCF.Channels.Message>.AsyncStateMachineBox<CoreWCF.Channels.SynchronizedMessageSource.<ReceiveAsync>d__4>.ExecutionContextCallback(object s)	Unknown
 	System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<CoreWCF.Channels.Message>.AsyncStateMachineBox<CoreWCF.Channels.SynchronizedMessageSource.<ReceiveAsync>d__4>.MoveNext(System.Threading.Thread threadPoolThread)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.AsyncStateMachineBox<CoreWCF.Channels.SynchronizedMessageSource.<ReceiveAsync>d__4>.MoveNext()	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__12_0(System.Action innerContinuation, System.Threading.Tasks.Task innerTask)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task.RunContinuations(object continuationObject)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task<System.__Canon>.TrySetResult(System.__Canon result)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.SetExistingTaskResult(System.Threading.Tasks.Task<System.__Canon> task, System.__Canon result)	Unknown
 	[Completed] CoreWCF.Http.dll!CoreWCF.Channels.WebSocketTransportDuplexSessionChannel.WebSocketMessageSource.ReceiveAsync(System.Threading.CancellationToken token)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<CoreWCF.Channels.Message>.AsyncStateMachineBox<CoreWCF.Channels.WebSocketTransportDuplexSessionChannel.WebSocketMessageSource.<ReceiveAsync>d__30>.ExecutionContextCallback(object s)	Unknown
 	System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<CoreWCF.Channels.Message>.AsyncStateMachineBox<CoreWCF.Channels.WebSocketTransportDuplexSessionChannel.WebSocketMessageSource.<ReceiveAsync>d__30>.MoveNext(System.Threading.Thread threadPoolThread)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.AsyncStateMachineBox<CoreWCF.Channels.WebSocketTransportDuplexSessionChannel.WebSocketMessageSource.<ReceiveAsync>d__30>.MoveNext()	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__12_0(System.Action innerContinuation, System.Threading.Tasks.Task innerTask)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task.RunContinuations(object continuationObject)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task<System.__Canon>.TrySetResult(System.__Canon result)	Unknown
 	CoreWCF.Http.dll!CoreWCF.Channels.WebSocketTransportDuplexSessionChannel.WebSocketMessageSource.StartNextReceiveAsync()	Unknown
 	[Resuming Async Method]	
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.AsyncStateMachineBox<CoreWCF.Channels.WebSocketTransportDuplexSessionChannel.WebSocketMessageSource.<StartNextReceiveAsync>d__36>.ExecutionContextCallback(object s)	Unknown
 	System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.AsyncStateMachineBox<CoreWCF.Channels.WebSocketTransportDuplexSessionChannel.WebSocketMessageSource.<StartNextReceiveAsync>d__36>.MoveNext(System.Threading.Thread threadPoolThread)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.AsyncStateMachineBox<CoreWCF.Channels.WebSocketTransportDuplexSessionChannel.WebSocketMessageSource.<StartNextReceiveAsync>d__36>.MoveNext()	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__12_0(System.Action innerContinuation, System.Threading.Tasks.Task innerTask)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task.RunContinuations(object continuationObject)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.VoidTaskResult>.TrySetResult(System.Threading.Tasks.VoidTaskResult result)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.SetExistingTaskResult(System.Threading.Tasks.Task<System.Threading.Tasks.VoidTaskResult> task, System.Threading.Tasks.VoidTaskResult result)	Unknown
 	[Completed] CoreWCF.Http.dll!CoreWCF.Channels.WebSocketTransportDuplexSessionChannel.WebSocketMessageSource.ReadBufferedMessageAsync()	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.AsyncStateMachineBox<CoreWCF.Channels.WebSocketTransportDuplexSessionChannel.WebSocketMessageSource.<ReadBufferedMessageAsync>d__32>.ExecutionContextCallback(object s)	Unknown
 	System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.AsyncStateMachineBox<CoreWCF.Channels.WebSocketTransportDuplexSessionChannel.WebSocketMessageSource.<ReadBufferedMessageAsync>d__32>.MoveNext(System.Threading.Thread threadPoolThread)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.AsyncStateMachineBox<CoreWCF.Channels.WebSocketTransportDuplexSessionChannel.WebSocketMessageSource.<ReadBufferedMessageAsync>d__32>.MoveNext()	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__12_0(System.Action innerContinuation, System.Threading.Tasks.Task innerTask)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task.RunContinuations(object continuationObject)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task<System.__Canon>.TrySetResult(System.__Canon result)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.SetExistingTaskResult(System.Threading.Tasks.Task<System.__Canon> task, System.__Canon result)	Unknown
 	[Completed] System.Net.WebSockets.dll!System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate<System.Net.WebSockets.ManagedWebSocket.WebSocketReceiveResultGetter, System.Net.WebSockets.WebSocketReceiveResult>(System.Memory<byte> payloadBuffer, System.Threading.CancellationToken cancellationToken, System.Net.WebSockets.ManagedWebSocket.WebSocketReceiveResultGetter resultGetter)	Unknown
 	System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Net.WebSockets.WebSocketReceiveResult>.AsyncStateMachineBox<System.Net.WebSockets.ManagedWebSocket.<ReceiveAsyncPrivate>d__66<System.Net.WebSockets.ManagedWebSocket.WebSocketReceiveResultGetter, System.Net.WebSockets.WebSocketReceiveResult>>.MoveNext(System.Threading.Thread threadPoolThread)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.AsyncStateMachineBox<System.Net.WebSockets.ManagedWebSocket.<ReceiveAsyncPrivate>d__66<System.Net.WebSockets.ManagedWebSocket.WebSocketReceiveResultGetter, System.__Canon>>.MoveNext()	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__12_0(System.Action innerContinuation, System.Threading.Tasks.Task innerTask)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.AwaitTaskContinuation.System.Threading.IThreadPoolWorkItem.Execute()	Unknown
 	System.Private.CoreLib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch()	Unknown
 	[Async Call Stack]	
 	[Async] CoreWCF.Http.dll!CoreWCF.Channels.RequestDelegateHandler.HandleRequest(Microsoft.AspNetCore.Http.HttpContext context)	Unknown
 	[Async] Microsoft.AspNetCore.Http.Abstractions.dll!Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(Microsoft.AspNetCore.Http.HttpContext context)	Unknown
 	[Async] CoreWCF.Http.dll!CoreWCF.Channels.ServiceModelHttpMiddleware.InvokeAsync(Microsoft.AspNetCore.Http.HttpContext context)	Unknown
 	[Async] Microsoft.AspNetCore.ResponseCompression.dll!Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(Microsoft.AspNetCore.Http.HttpContext context)	Unknown
 	[Async] Microsoft.AspNetCore.Authentication.dll!Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(Microsoft.AspNetCore.Http.HttpContext context)	Unknown
```

Any idea what's wrong?

My code looks like this:

```f#
       //
       type IMyService = // ...
       type MyService() =
           interface IMyService  // ...

       // ----------------------------
        services.AddSingleton<MyService>(x)
        services.AddServiceModelServices()

       // ----------------------------


        app.UseServiceModel(fun builder ->
            builder.AddService<MyService>()

            let binding = new NetHttpBinding()

            binding.SendTimeout <- TimeSpan.FromMinutes(20.);
            binding.ReceiveTimeout <- TimeSpan.FromMinutes(20.);
            binding.MaxReceivedMessageSize <- 2147483647L
            binding.MaxBufferSize <- 2147483647
            binding.ReaderQuotas.MaxArrayLength <- 2147483647
            binding.ReaderQuotas.MaxBytesPerRead <- 2147483647
            binding.ReaderQuotas.MaxDepth <- 2147483647
            binding.ReaderQuotas.MaxNameTableCharCount <- 2147483647
            binding.ReaderQuotas.MaxStringContentLength <- 2147483647

            builder.AddServiceEndpoint<MyService, IMyService>(binding, "/__wcf")
        )
```

**Comment by 0x53A** [comment]
I can see that ServiceChannelProxy was unsealed with commit https://github.com/CoreWCF/CoreWCF/commit/dd496f1c16b872f52f3737c76da34b6849f009ac#diff-6463b08857af502ffaa4756fe80b6c6a8b88d03fd37f87e209f8c03841b04299

The commit is 11 days old, the last release was 14 days ago, maybe this is already fixed?

I'd be happy to test it out if you can push a new release.

**Comment by mconnew** [comment]
@0x53A, there should be a dev build available from the azure devops nuget feed that's detailed in the readme.md of the repo. I didn't know duplex used to work!! I tracked down the change and it happened as part of some code cleanup. I think I ported the implementation again from NetFx instead of the one from the client because there was some missing implementation, and that made the class internal and sealed, which then broke duplex. We should be releasing a 0.3.0 version very soon with that change and some others.

**Comment by 0x53A** [comment]
> I didn't know duplex used to work!!

haha I've been using it in production for like a year or so now

Thank you, then I'll wait for 0.3, I don't urgently need to update right now this moment, I just didn't want to be left behind on an old version forever.
