### ISSUE TITLE
Hosting Service without providing implementation class

### ISSUE THREAD

**Issue by Danielku15** [CoreWCF/CoreWCF#467]
CoreWCF seem to require currently that we provide the class implementing the contract, but this is not always possible. It should be sufficient for CoreWCF to work on contract level, and depend on the DI system to provide the implementation. 

Our use case is that our service implementation is not existing as actual class but it is a CastleProxy instance with interceptors. 

In the old-fashioned ServiceHost this worked when you directly used the constructor where you provide the service instance. 

When you are doing this today: 
```cs
IMyService apiImplementation = MyServiceProxyFactory.CreateProxy();
var webHost = WebHost.CreateDefaultBuilder()
    .ConfigureServices(services =>
    {
        services.AddServiceModelServices();
        services.AddSingleton(apiImplementation);
    })
    .UseNetTcp(8080)
    .Configure(app =>
    {
        app.UseServiceModel(builder =>
        {
            builder.AddService<IUAMAdminServiceContract>();
            builder.AddServiceEndpoint<IMyService, IMyService>(
                new NetTcpBinding() { .. },
                new Uri($"net.tcp://localhost:8081/MyService/")
            );
        });
    })
    .Build();
webHost.Start();
```

It fails with: 
```
   at System.RuntimeTypeHandle.VerifyInterfaceIsImplemented(RuntimeTypeHandle interfaceHandle)
   at System.RuntimeType.GetInterfaceMap(Type ifaceType)
   at CoreWCF.Description.TypeLoader`1.GetIOperationAttributesFromType[TOperation](OperationDescription opDesc, Type targetIface, Type implType)
   at CoreWCF.Description.TypeLoader`1.<>c__DisplayClass20_0.<AddBehaviors>b__0(Type currentType, KeyedByTypeCollection`1 behaviors)
   at CoreWCF.Description.TypeLoader`1.AddBehaviorsAtOneScope[IBehavior,TBehaviorCollection](Type type, TBehaviorCollection descriptionBehaviors, ServiceInheritanceCallback`1 callback)
   at CoreWCF.Description.TypeLoader`1.ApplyServiceInheritance[IBehavior,TBehaviorCollection](TBehaviorCollection descriptionBehaviors, ServiceInheritanceCallback`1 callback)
   at CoreWCF.Description.TypeLoader`1.AddBehaviors(ContractDescription contractDesc, Boolean implIsCallback, ContractReflectionInfo reflectionInfo)
   at CoreWCF.Description.TypeLoader`1.LoadContractDescriptionHelper(Type contractType, Object serviceImplementation)
   at CoreWCF.Description.TypeLoader`1.LoadContractDescription(Type contractType)
   at CoreWCF.Description.ContractDescription.GetContract[TService](Type contractType)
   at CoreWCF.ServiceHostObjectModel`1.CreateDescription(IDictionary`2& implementedContracts)
   at CoreWCF.ServiceHostBase.InitializeDescription(UriSchemeKeyedCollection baseAddresses)
   at CoreWCF.ServiceHostObjectModel`1..ctor(IServiceProvider serviceProvider, ServiceBuilder serviceBuilder, ILogger`1 logger)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at CoreWCF.Description.DispatcherBuilder.BuildDispatcher[TService](ServiceConfiguration`1 serviceConfig, IServiceProvider services)
   at CoreWCF.Configuration.ServiceConfiguration`1.GetDispatchers()
   at CoreWCF.Configuration.DispatcherBuilderImpl.BuildDispatchers(Type serviceType)
   at CoreWCF.Channels.Framing.NetMessageFramingConnectionHandler.BuildAddressTable(IServiceProvider services)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at CoreWCF.Channels.Framing.NetMessageFramingConnectionHandler.OnServiceBuilderOpened(Object sender, EventArgs e)
   at CoreWCF.Channels.CommunicationObject.OnOpened()
--- End of stack trace from previous location ---
   at CoreWCF.Configuration.WrappingIServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.Start()
   at MyApp.MyService.OnStart(String[] args)
   at MyApp.MyService.Start(String[] args)
   at MyApp.Program.Main()
```

I think the problem lies here in the following code: 

https://github.com/CoreWCF/CoreWCF/blob/2d3b77ebb11619bd33ca6aa084f8502da25c53c7/src/CoreWCF.Primitives/src/CoreWCF/Description/TypeLoader.cs#L428-L441

I think we need a path here that also the "implType" is an interface and then we need to parse the operations simply from the contract definition. Maybe something like the following code flow could work already: 

```cs
var ifaceMap = default(InterfaceMapping);
bool useImplAttrs = false;
if (implType != null)
{
    if (targetIface.IsAssignableFrom(implType) && targetIface.IsInterface)
    {
        if(implType.IsInterface) 
        {
            // implType is also an interface and not a class, no need to check interface mapping
            useImplAttrs = false;
        }
        else
        {
            ifaceMap = implType.GetInterfaceMap(targetIface);
            useImplAttrs = true;
        }
    }
    else
    {
        // implType does not implement any methods from the targetIface, so there is nothing to do
        return result;
    }
}
```

**Comment by Danielku15** [comment]
Couldn't resist to write a test in the repo directly to have a closer look. Indeed my assumption was correct and with changing the mentioned code area, the usage of only interfaces seem to work.
