### ISSUE TITLE
Failed to run the NetCoreServer sample

### ISSUE THREAD

**Issue by maloo** [CoreWCF/CoreWCF#528]
I get the following error when starting the sample (dotnet run) and navigate to https://localhost:8443/EchoService/wsHttp?WSDL

Same with http, w/ or w/o ?WSDL. What is the link to WSDL description and "mex" endpoint in OpenWCF?

```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET https://localhost:8443/EchoService/wsHttp?WSDL
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMEGBSS0NOUG", Request id "0HMEGBSS0NOUG:00000001": An unhandled exception was thrown by the application.
CoreWCF.ProtocolException: There is a problem with the XML that was received from the network. See inner exception for more details.
 ---> System.Xml.XmlException: The body of the message cannot be read because it is empty.
   --- End of inner exception stack trace ---
   at CoreWCF.Channels.AspNetCoreReplyChannel.HandleRequest(HttpContext context) in C:\data\temp\CoreWCF\src\CoreWCF.Http\src\CoreWCF\Channels\AspNetCoreReplyChannel.cs:line 111 
   at CoreWCF.Channels.RequestDelegateHandler.HandleRequest(HttpContext context) in C:\data\temp\CoreWCF\src\CoreWCF.Http\src\CoreWCF\Channels\RequestDelegateHandler.cs:line 108 
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at CoreWCF.Channels.ServiceModelHttpMiddleware.InvokeAsync(HttpContext context) in C:\data\temp\CoreWCF\src\CoreWCF.Http\src\CoreWCF\Channels\ServiceModelHttpMiddleware.cs:line 49
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by mconnew** [comment]
You are requesting the wsdl, which support for hasn't been released yet. Support for this is being tracked in #270. There's details in that issue about adding tests for known scenarios. If you want to make sure your scenario works when this is released, I would suggest either giving the code a try in the feature/wsdl branch , or preferably contributing some tests if possible.
I'm closing this issue as a duplicate. If you have any more questions, please ask in issue #270.
