### ISSUE TITLE
TypeLoadException after upgrading to 1.0.0-preview1

### ISSUE THREAD

**Issue by mus65** [CoreWCF/CoreWCF#594]
After upgrading from 0.4.0 to 1.0.0-preview1, the ASP .NET Core AuthenticationMiddleware fails with the following exception. This is with .NET 6.0 .

This seems to be related to the version 6.14.1 of Microsoft.IdentitiyModel.Protocols.WsFederation . Adding a dependency to the latest Microsoft.IdentitiyModel.Protocols.WsFederation 6.17.0 to my project fixes it, so I guess CoreWCF just needs to update the dependency?

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeLoadException: Derived method 'GetBaseConfigurationAsync' in type 'Microsoft.IdentityModel.Protocols.ConfigurationManager`1' from assembly 'Microsoft.IdentityModel.Protocols, Version=6.14.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' cannot reduce access.
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerOptions..ctor()
   at System.RuntimeType.CreateInstanceOfT()
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceOfT()
   at System.Activator.CreateInstance[T]()
   at Microsoft.Extensions.Options.OptionsFactory`1.CreateInstance(String name)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsMonitor`1.<>c__DisplayClass10_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
```

**Comment by mconnew** [comment]
@birojnayak can you validate this and submit a PR?
