### ISSUE TITLE
Errors Generating WSDL in Preview2 Package in .NET 6

### ISSUE THREAD

**Issue by roend83** [CoreWCF/CoreWCF#615]
The errors are thrown in DataContractEx.GetGetOnlyCollectionDataContractStub.  The first error I got was here:

`var serializationModeParam = Expression.Constant(intModeParam, SerializationModeType); `

The message is:

`System.ArgumentException
  HResult=0x80070057
  Message=Argument types do not match
  Source=System.Linq.Expressions
  StackTrace:
   at System.Linq.Expressions.Expression.Constant(Object value, Type type)
   at CoreWCF.Runtime.Serialization.DataContractEx.GetGetOnlyCollectionDataContractStub(Int32 id, RuntimeTypeHandle typeHandle, Type type, Int32 mode) in C:\repos\inspection\apsl\Apsl\CoreWCF\src\CoreWCF.Primitives\src\CoreWCF\Runtime\Serialization\DataContractEx.cs:line 121`

I can fix this by changing it to:

`var serializationModeParam = Expression.Constant(Enum.ToObject(SerializationModeType, mode), SerializationModeType); `

However then I get an error on this line:

`Expression callExpr = Expression.Call(methodInfo, idParam, typeHandleParam, typeParam, serializationModeParam);`

The message is: 

`System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null. (Parameter 'method')
  Source=System.Linq.Expressions
  StackTrace:
   at System.Linq.Expressions.Expression.Call(MethodInfo method, Expression arg0, Expression arg1, Expression arg2, Expression arg3)
   at CoreWCF.Runtime.Serialization.DataContractEx.GetGetOnlyCollectionDataContractStub(Int32 id, RuntimeTypeHandle typeHandle, Type type, Int32 mode) in C:\repos\inspection\apsl\Apsl\CoreWCF\src\CoreWCF.Primitives\src\CoreWCF\Runtime\Serialization\DataContractEx.cs:line 124`

It appears that the `GetGetOnlyCollectionDataContract` method does not exist on the type `System.Runtime.Serialization.DataContract, System.Private.DataContractSerialization, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a`.

**Comment by roend83** [comment]
It looks like this line is missing a parameter 

`var methodInfo = DataContractType.GetMethod("GetGetOnlyCollectionDataContract", BindingFlags.Static | BindingFlags.NonPublic, null,
                new Type[] { typeof(int), typeof(RuntimeTypeHandle), typeof(Type) }, null);`

If I add `, SerializationModeType` into the parameter array it appears to work.  I'll start a PR with these updates.
