### ISSUE TITLE
Running services without contract interfaces

### ISSUE THREAD

**Issue by lscorcia** [CoreWCF/CoreWCF#642]
I'm evaluating CoreWCF to help porting some of the legacy WCF SOAP services we have in our organization.
They are currently defined as simple concrete classes without an explicit service interface. All annotated methods were automatically considered by WCF as service methods, i.e.:

```
[ServiceContract(Namespace = "http://my.namespace/MyService")]
public class MyService
{
  [OperationContract]
  public MyOutputDto MyMethod(MyInputDto request)
  {
    ...
  }
}
```

They were activated using svc-less activation more or less as follows:

```
<serviceHostingEnvironment aspNetCompatibilityEnabled="true" multipleSiteBindingsEnabled="true">
  <serviceActivations>
    <add factory="System.ServiceModel.Activation.ServiceHostFactory" relativeAddress="ws/soap/MyService.svc" service="MyService" />
  </serviceActivations>
</serviceHostingEnvironment>
```

Now, I am configuring the activation as described in the walkthrough:

```
// CoreWCF SOAP services
app.UseServiceModel(builder => {
  builder.AddService<MyService>((serviceOptions) => { })
    .AddServiceEndpoint<MyService, MyService>(new BasicHttpBinding(), "/ws/soap/MyService.svc");
});
```

But the application startup fails with the following error:

```
Unhandled exception. System.ArgumentException: Service type MyService doesn't implement interface MyService
   at CoreWCF.Description.DispatcherBuilder.BuildDispatcher[TService](ServiceConfiguration`1 serviceConfig, IServiceProvider services)
   at CoreWCF.Configuration.ServiceConfiguration`1.GetDispatchers()
   at CoreWCF.Configuration.DispatcherBuilderImpl.BuildDispatchers(Type serviceType)
   at CoreWCF.Channels.ServiceModelHttpMiddleware.BuildBranch()
   at CoreWCF.Channels.ServiceModelHttpMiddleware.EnsureBranchBuilt()
   at CoreWCF.Channels.ServiceModelHttpMiddleware.ServiceBuilderOpenedCallback(Object sender, EventArgs e)
   at CoreWCF.Channels.CommunicationObject.OnOpened()
--- End of stack trace from previous location ---
   at CoreWCF.Configuration.WrappingIServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Microsoft.AspNetCore.Builder.WebApplication.Run(String url)
```

Will you support this feature or should I write interfaces for all of the legacy services?

**Comment by lscorcia** [comment]
Nevermind, it was my fault. I forgot the ServiceContract annotations on the service class - when I added that it started listening correctly.
