### ISSUE TITLE
Error when publishing services with different namespaces

### ISSUE THREAD

**Issue by lscorcia** [CoreWCF/CoreWCF#645]
Hi, I have encountered the following error in the `?singleWsdl` endpoint when porting some WCF services to .net core using CoreWCF.

```
An ExceptionDetail, likely created by IncludeExceptionDetailInFaults=true, whose value is:
System.NotSupportedException: A single WSDL document could not be generated for this service. Multiple service contract namespaces were found (http://my.company/ws/ServiceB/, http://my.company/ws/ServiceC/, urn:WorkflowWebService). Ensure that all your service contracts have the same namespace.
   at CoreWCF.Description.WsdlHelper.VerifyContractNamespace(List`1 wsdls)
   at CoreWCF.Description.WsdlHelper.GetSingleWsdl(MetadataSet metadataSet)
   at CoreWCF.Description.ServiceMetadataExtension.EnsureSingleWsdlInitialized()
   at CoreWCF.Description.ServiceMetadataExtension.get_SingleWsdl()
   at CoreWCF.Description.ServiceMetadataExtension.HttpGetImpl.TryHandleMetadataRequestAsync(HttpContext requestContext, IQueryCollection queries)
   at CoreWCF.Description.ServiceMetadataExtension.HttpGetImpl.ProcessHttpRequest(HttpContext requestContext)
   at CoreWCF.Description.ServiceMetadataExtension.HttpGetImpl.HandleRequest(HttpContext httpContext)
```

The error shows when invoking the ?singleWsdl endpoint but also there's something weird when invoking the ?wsdl endpoint, as it shows import directives for types that are not actually needed for the specific service.
Everything works fine if I register only one of the services, but I need all of them and they should have different namespaces.

The services are registered as follows:

```
app.UseServiceModel(wcfBuilder =>
{
  wcfBuilder.AddService<MyCompany.ServiceA>((serviceOptions) => { })
    .AddServiceEndpoint<MyCompany.ServiceA, MyCompany.IServiceA>(
    new CustomBasicHttpsBinding(), "/ws/ServiceA.svc");

  wcfBuilder.AddService<MyCompany.ServiceB>((serviceOptions) => { })
    .AddServiceEndpoint<MyCompany.ServiceB, MyCompany.ServiceB>(
    new CustomBasicHttpsBinding(), "/ws/ServiceB.svc");

  wcfBuilder.AddService<MyCompany.ServiceC>((serviceOptions) => { })
    .AddServiceEndpoint<MyCompany.ServiceC, MyCompany.ServiceC>(
      new CustomBasicHttpsBinding(), "/ws/ServiceC.svc");
});
```

The services are defined as follows:

```
[ServiceContractAttribute(Namespace = "urn:WorkflowWebService")]
public interface IServiceA
{
	[OperationContract(Action = "", ReplyAction = "*")]
	[XmlSerializerFormat(Style = OperationFormatStyle.Rpc, Use = OperationFormatUse.Encoded)]
	[return: MessageParameter(Name = "avviaProcessoReturn")]
	string avviaProcesso(string in0);
}

public class ServiceA: IServiceA
{
	...
}

[ServiceContract(Namespace = "http://my.company/ws/ServiceB/")]
[ServiceBehavior(IncludeExceptionDetailInFaults = true)]
public class ServiceB
{
	[OperationContract]
	public string MyOperation(string request)
	{

	}
}

[ServiceContract(Namespace = "http://my.company/ws/ServiceC/")]
[ServiceBehavior(IncludeExceptionDetailInFaults = true)]
public class ServiceC
{
	[OperationContract]
	public string MyOperation(string request)
	{

	}
}
```

Do you have any suggestion?

**Comment by lscorcia** [comment]
Small repro is here: https://github.com/lscorcia/corewcf-repro-2/

![immagine](https://user-images.githubusercontent.com/16761934/166294601-5ff509c2-3132-48d7-9539-abf10817e832.png)

**Comment by dioptryk** [comment]
We have the same problem, is it possible to circumvent it somehow? We need different namespaces.

**Comment by lscorcia** [comment]
I still have not found a workaround :(

**Comment by mconnew** [comment]
I understand the problem and should have a fix available within a couple of weeks.
