### ISSUE TITLE
CoreWCF.ConfigurationManager does not allow alias endpoints

### ISSUE THREAD

**Issue by WenningQiu** [CoreWCF/CoreWCF#714]
CoreWCF.ConfigurationManager does not allow alias endpoints (same service, contract and binding but different address). It would blow up on the configuration below:

  <system.serviceModel>
    <services>
      <service name="CSG.ServiceRepository.ServiceRepository, CSG.ServiceRepository.Service">
        <endpoint address="WCFServiceRepository/ServiceRepository.svc" 
                  binding="basicHttpBinding" 
                  bindingConfiguration="BigStringHttp" 
                  contract="CSG.ServiceRepository.IServiceRepository, CSG.ServiceRepository.Contract" />
        <endpoint address="WCFServiceRepository/22.3.0/ServiceRepository.svc" 
                  binding="basicHttpBinding" 
                  bindingConfiguration="BigStringHttp" 
                  contract="CSG.ServiceRepository.IServiceRepository, CSG.ServiceRepository.Contract" />
      </service>
  </services>
</system.serviceModel>

Application startup exception: System.Configuration.ConfigurationErrorsException: The entry '' has already been added. (C:\work\git\infra\servicerepository\Src\WebService\ServiceRepository.Service.CoreWcfHosting\Publish\Web.config line 57)
   at System.Configuration.BaseConfigurationRecord.EvaluateOne(String[] keys, SectionInput input, Boolean isTrusted, FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult)
   at System.Configuration.BaseConfigurationRecord.Evaluate(FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult, Boolean getLkg, Boolean getRuntimeObject, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey, Boolean getLkg, Boolean checkPermission)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Configuration.ConfigurationSectionCollection.Get(String name)
   at System.Configuration.ConfigurationSectionCollection.get_Item(String name)
   at CoreWCF.Configuration.ServiceModelSectionGroup.get_Services()
   at CoreWCF.Configuration.ConfigurationManagerServiceModelOptions.ReadConfigSection(ServiceModelSectionGroup group)
   at CoreWCF.Configuration.ConfigurationManagerServiceModelOptions.Configure(ServiceModelOptions options)
   at CoreWCF.Configuration.ConfigurationManagerServiceModelOptions.Configure(String name, ServiceModelOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
   at CoreWCF.Configuration.ServiceModelApplicationBuilderExtensions.UseServiceModel(IApplicationBuilder app)
   at CoreWCF.Configuration.ServiceModelApplicationBuilderExtensions.UseServiceModel(IApplicationBuilder app, Action`1 configureServices)
   at CSG.Framework.CoreWCF.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in C:\work\git\infra\framework\src\Library\Framework.CoreWCF\Startup.cs:line 37
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
crit: Microsoft.AspNetCore.Hosting.Diagnostics[6]
      Application startup exception
      System.Configuration.ConfigurationErrorsException: The entry '' has already been added. (C:\work\git\infra\servicerepository\Src\WebService\ServiceRepository.Service.CoreWcfHosting\Publish\Web.config line 57)
         at System.Configuration.BaseConfigurationRecord.EvaluateOne(String[] keys, SectionInput input, Boolean isTrusted, FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult)
         at System.Configuration.BaseConfigurationRecord.Evaluate(FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult, Boolean getLkg, Boolean getRuntimeObject, Object& result, Object& resultRuntimeObject)
         at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
         at System.Configuration.BaseConfigurationRecord.GetSection(String configKey, Boolean getLkg, Boolean checkPermission)
         at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
         at System.Configuration.ConfigurationSectionCollection.Get(String name)
         at System.Configuration.ConfigurationSectionCollection.get_Item(String name)
         at CoreWCF.Configuration.ServiceModelSectionGroup.get_Services()
         at CoreWCF.Configuration.ConfigurationManagerServiceModelOptions.ReadConfigSection(ServiceModelSectionGroup group)
         at CoreWCF.Configuration.ConfigurationManagerServiceModelOptions.Configure(ServiceModelOptions options)
         at CoreWCF.Configuration.ConfigurationManagerServiceModelOptions.Configure(String name, ServiceModelOptions options)
         at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
         at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
         at CoreWCF.Configuration.ServiceModelApplicationBuilderExtensions.UseServiceModel(IApplicationBuilder app)
         at CoreWCF.Configuration.ServiceModelApplicationBuilderExtensions.UseServiceModel(IApplicationBuilder app, Action`1 configureServices)
         at CSG.Framework.CoreWCF.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in C:\work\git\infra\framework\src\Library\Framework.CoreWCF\Startup.cs:line 37
         at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
         at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
         at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
         at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
         at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
         at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()

**Comment by WenningQiu** [comment]
Yes it works in WCF. We typically configure a version-less endpoint as alias to the current versioned endpoint. See example below.

```
  <system.serviceModel>
    <serviceHostingEnvironment>
      <serviceActivations>
        <add relativeAddress="ServiceRepository.svc" service="CSG.ServiceRepository.ServiceRepository, CSG.ServiceRepository.Service" factory="CSG.Framework.ServiceModel.WCFServiceHostFactory, CSG.Framework" />
        <add relativeAddress="22.3.0/ServiceRepository.svc" service="CSG.ServiceRepository.ServiceRepository, CSG.ServiceRepository.Service" factory="CSG.Framework.ServiceModel.WCFServiceHostFactory, CSG.Framework" />
        <add relativeAddress="22.2.0/ServiceRepository.svc" service="CSG.ServiceRepository.Facade.ServiceRepository_Facade_22_2_0, CSG.ServiceRepository.Service.Facade-22.2.0" factory="CSG.Framework.ServiceModel.WCFServiceHostFactory, CSG.Framework" />
        <add relativeAddress="22.1.0/ServiceRepository.svc" service="CSG.ServiceRepository.Facade.ServiceRepository_Facade_22_1_0, CSG.ServiceRepository.Service.Facade-22.1.0" factory="CSG.Framework.ServiceModel.WCFServiceHostFactory, CSG.Framework" />
      </serviceActivations>
    </serviceHostingEnvironment>
    <services>
      <service name="CSG.ServiceRepository.ServiceRepository">
        <endpoint address="" binding="basicHttpBinding" bindingConfiguration="BigStringHttp" contract="CSG.ServiceRepository.IServiceRepository" />
        <endpoint address="" binding="netNamedPipeBinding" bindingConfiguration="netNamedPipeBinding" contract="CSG.ServiceRepository.IServiceRepository" />
      </service>
      <service name="CSG.ServiceRepository.Facade.ServiceRepository_Facade_22_2_0">
        <endpoint address="" binding="basicHttpBinding" bindingConfiguration="BigStringHttp" contract="CSG.ServiceRepository.Facade.IServiceRepository" />
        <endpoint address="" binding="netNamedPipeBinding" bindingConfiguration="netNamedPipeBinding" contract="CSG.ServiceRepository.Facade.IServiceRepository" />
      </service>
      <service name="CSG.ServiceRepository.Facade.ServiceRepository_Facade_22_1_0">
        <endpoint address="" binding="basicHttpBinding" bindingConfiguration="BigStringHttp" contract="CSG.ServiceRepository.Facade.IServiceRepository" />
        <endpoint address="" binding="netNamedPipeBinding" bindingConfiguration="netNamedPipeBinding" contract="CSG.ServiceRepository.Facade.IServiceRepository" />
      </service>
    </services>
  </system.serviceModel>
```

**Comment by jasoncono** [comment]
@WenningQiu I was running into this as well, and by adding a `name` attribute (and unique value) to the `<endpoint>`, I was able to get this working.

**Comment by WenningQiu** [comment]
@jasoncono That's good to know, thanks for the hint. IMO, it would be still great if it works the same way as WCF so that as much of the existing configuration can be reused when ported to CoreWCF.
