### ISSUE TITLE
Duplicate registration exception when using different ports

### ISSUE THREAD

**Issue by KnapSac** [CoreWCF/CoreWCF#716]
I'm trying to migrate an existing .NET Framework application to using CoreWCF.

There are multiple services in the application, with each service binding to a different port. This
works fine using the original WCF libraries (using a `ServiceHost` instead of ASP.NET Core), but
using CoreWCF I run into issues.

Without using `UseNetTcp`, adding multiple TCP service endpoints on different ports works fine.
However, these ports are not actually opened.

With `UseNetTcp`, adding one TCP service endpoint for one service works fine, but as soon as I try
to add another service with its own TCP service endpoint (on a different port), I get an exception
saying `a registration already exists for URI 'net.tcp://localhost:8051/MyService1/svc'`.

Creating the web host builder:
```csharp
IWebHost webHost = WebHost.CreateDefaultBuilder( ).UseStartup< Startup >( ).UseNetTcp( ).Build( );
webHost.Run( );
```

A simplified version of the `Startup` class:
```csharp
public class Startup
{
    public void ConfigureServices(
        IServiceCollection services )
    {
        services.AddServiceModelServices( ).AddServiceModelMetadata( );
    }

    public void Configure(
        IApplicationBuilder app,
        IHostingEnvironment env )
    {
        app.UseServiceModel(
            builder =>
            {
                foreach ( EServiceType serviceType in new[ ]
                                                        {
                                                            EServiceType.One,
                                                            EServiceType.Two,
                                                        } )
                {
                    string hostName = Properties.Host;
                    string servicePath = Properties.UriPath( serviceType );
                    int tcpPort = Properties.TcpPort( serviceType );
                    SecurityMode = Properties.TcpSecurityMode( serviceType );
                    int maxResponseSize = Properties.MaxResponseSize( serviceType ) );

                    Type implementation = Type.GetType( Properties.ServiceImplementation( serviceType ), false );
                    Type contractType = Type.GetType( Properties.ServiceContract( serviceType ), false );

                    Uri tcpAddress = new Uri( $"net.tcp://{hostName}:{tcpPort}/{servicePath}/svc" );

                    builder.AddService( implementation );

                    builder.AddServiceEndpoint(
                        implementation,
                        contractType,
                        new NetTcpBinding( tcpSecurityMode )
                        {
                            MaxBufferPoolSize = maxResponseSize,
                            MaxBufferSize = maxResponseSize,
                            MaxReceivedMessageSize = maxResponseSize,
                            ReaderQuotas = new XmlDictionaryReaderQuotas
                                           {
                                               MaxStringContentLength = maxResponseSize,
                                               MaxBytesPerRead = maxResponseSize,
                                               MaxArrayLength = maxResponseSize,
                                               MaxDepth = 64
                                           },
                            OpenTimeout = Properties.OpenTimeout,
                            CloseTimeout = Properties.CloseTimeout,
                            SendTimeout = Properties.SendTimeout,
                            ReceiveTimeout = Properties.ReceiveTimeout
                        },
                        tcpAddress,
                        tcpAddress );
                        } );
    }
}
```

The exception stacktrace:
```stacktrace
System.InvalidOperationException: A registration already exists for URI 'net.tcp://localhost:8051/MyService/svc'.
   at CoreWCF.Channels.UriPrefixTable`1.RegisterUri(Uri uri, HostNameComparisonMode hostNameComparisonMode, TItem item)
   at CoreWCF.Channels.Framing.NetMessageFramingConnectionHandler.BuildAddressTable(IServiceProvider services)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at CoreWCF.Channels.CommunicationObject.OnOpened()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CoreWCF.Configuration.WrappingIServer.<StartAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.<StartAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.<RunAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.<RunAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
```

**Comment by MsLilu2** [comment]
Trying to bump this issue up and raise some attention. I am facing exactly the same issue when porting from WCF to CoreWCF.
@mconnew Any idea on this?

Here is my web host.
```
var host = Host.CreateDefaultBuilder()
                    .UseWindowsService()
                    .ConfigureWebHostDefaults(webBuilder =>
                    {
                        webBuilder.UseNetTcp(IPAddress.IPv6Any, 8089)
                                  .UseNetTcp(IPAddress.IPv6Any, 8090)
                                  .UseStartup<Startup>();
                    });
```
My service
```
app.UseServiceModel(builder =>
            {
                // Add the Echo Service
                builder.AddService<EchoService>()
                           .AddServiceEndpoint<EchoService, IEchoService>(new NetTcpBinding(SecurityMode.None), $"net.tcp://localhost:8089/netTcp")
                           .AddServiceEndpoint<EchoService, IEchoService>(new NetTcpBinding(SecurityMode.Transport), $"net.tcp://localhost:8090/netTcp");
            }
```

My result:
InvalidOperationException: A registration already exists for URI 'net.tcp://localhost:8090/netTcp'.

**Comment by mconnew** [comment]
For now the fastest path to a solution is to run multiple ASP.NET Core instances in the same app, one per port. This is similar to running a separate ServiceHost instance per port. I don't know how well that will interact with UseWindowsService though. You might be able to have just one Host instance be the one that manages it being a Windows Service. I don't know anything about that feature or how it interacts with Windows, but I presume it handles shutting down of the service gracefully when the service is stopped. You could use the IApplicationLifetime hook of the "primary" service to then trigger cleanly shutting down the others.

**Comment by iyrwis** [comment]
Hi @mconnew, for now do we support the below syntax? Or we still need to create multiple ASP instances? I've have a very legacy service to migrate which contains 5 different ports.

var host = Host.CreateDefaultBuilder()
                    .UseWindowsService()
                    .ConfigureWebHostDefaults(webBuilder =>
                    {
                        webBuilder.UseNetTcp(IPAddress.IPv6Any, 8089)
                                  .UseNetTcp(IPAddress.IPv6Any, 8090)
                                  .UseStartup<Startup>();
                    });

**Comment by mconnew** [comment]
I think you can make that work with using a recent AddService overload which takes a delegate to configure the ServiceOptions. If you clear out the base addresses in the service options and add a single net.tcp base address (with port number) it will make that service instance only try to use that single net.tcp port and you'll avoid that exception. I'm on my phone right now so can't easily provide a code example. If you need more info, let me know and I'll provide some sample code when I'm at a computer next.

**Comment by mconnew** [comment]
You would do something like this:
```c#
app.UseServiceModel(builder =>
{
    // Add the Service1
    serviceBuilder.AddService<Service1>(serviceOptions =>
    {
        serviceOptions.BaseAddresses.Clear();
        serviceOptions.BaseAddresses.Add(new Uri($"net.tcp://localhost:8089/service1.svc"));
    })
    // This will expose Service1 at net.tcp://localhost:8089/service1.svc/no-security
    .AddServiceEndpoint<Service1, IService1>(new NetTcpBinding(SecurityMode.None), "no-security");
    builder.AddService<Service2>(serviceOptions =>
    {
        serviceOptions.BaseAddresses.Clear();
        serviceOptions.BaseAddresses.Add(new Uri($"net.tcp://localhost:8090/service2.svc"));
    })
    // This will expose Service2 at net.tcp://localhost:8090/service2.svc/windows-auth
    .AddServiceEndpoint<Service2, IService2>(new NetTcpBinding(SecurityMode.Transport), $"windows-auth");
}
```
Let me know if that works for you or not.

**Comment by iyrwis** [comment]
Hi @mconnew, I tried your solution but it still uccur the below exception, any suggestion for this part? Thanks so much.

![image](https://user-images.githubusercontent.com/37793755/226270918-2909f8a2-2b60-411e-936e-b79fcf70d0eb.png)

Here is my key code piece:
![image](https://user-images.githubusercontent.com/37793755/226271026-35ed6b10-6bcf-4a17-9cfc-3ad4cc08f6d7.png)
![image](https://user-images.githubusercontent.com/37793755/226271147-3e7630a2-3e0a-4a77-a428-3d892f63451e.png)
![image](https://user-images.githubusercontent.com/37793755/226271277-adb7db4e-d631-4aa6-b698-07128f442642.png)

**Comment by iyrwis** [comment]
Hi @mconnew , thanks for your suggestion. I tried it yesterday but it still failed. I have 2 test examples for only use ICalculate and not use ICalculate2 anymore:

A). Add the base address in options as below:
![image](https://user-images.githubusercontent.com/37793755/226799413-83ece7f5-e67f-4127-914b-fdfeae64cd87.png)

![image](https://user-images.githubusercontent.com/37793755/226799506-531210e4-ab58-48d2-8265-6c0fb44c7855.png)

It will occur the below exception:
![image](https://user-images.githubusercontent.com/37793755/226799336-3e2ddff7-efb7-4f06-bd9c-0befc82aab45.png)

B). Add the base address in options as below:
![image](https://user-images.githubusercontent.com/37793755/226800303-d858fe68-b6e6-4e0e-b228-169552dc52bc.png)

It will occur another exception:
![image](https://user-images.githubusercontent.com/37793755/226800359-8fc112f3-6b15-440a-acc4-621c6fa42794.png)

**Comment by iyrwis** [comment]
Hi @mconnew , any ideas about the case I sent above? Thanks so much.
I think if currently CoreWCF not support these cases, I can only create multiple ASP.NET Core instances to listen each NetTcp ports for workaround.

**Comment by oklemencic** [comment]
I also had the same problem. One other option is to set `HostNameComparisonMode ` to `HostNameComparisonMode.Exact` on the NetTcpBinding of the server. But this solution only seems to work, when the services are always accessed via the same ip/hostname, otherwise the urls don't match.

```
var netTcpBinding = new NetTcpBinding
{
	Security = new NetTcpSecurity
	{
		Mode = SecurityMode.Transport,
		Transport = new TcpTransportSecurity
		{
			ClientCredentialType = TcpClientCredentialType.Windows
		},
	},
	HostNameComparisonMode = HostNameComparisonMode.Exact
};

builder.AddServiceEndpoint<TestService1, ITestService1>(netTcpBinding, $"net.tcp://{ip}:{port}");
builder.AddServiceEndpoint<TestService2, ITestService2>(netTcpBinding, $"net.tcp://{ip}:{port+1}");
```

It looks like the reason for this issue is the following location, which creates the `UriPrefixTable` with  `includePortInComparison` set to false. 

https://github.com/CoreWCF/CoreWCF/blob/ac5453e5520db73132e2739d536078e64c90ded1/src/CoreWCF.NetFramingBase/src/CoreWCF/Channels/Framing/NetMessageFramingConnectionHandler.cs#L71C13-L71C17

Changing this to true in the CoreWCF source code works for me. But unfortunately this is not part of the public interface of CoreWCF.
