### ISSUE TITLE
Walkthrough not working

### ISSUE THREAD

**Issue by VR-Architect** [CoreWCF/CoreWCF#745]
Just tried the walkthrough and when I run the service there is an error at app.Run() of the Program.cs file. Interesting thing is there is no authentication settings in the project. I just copied everything per the instructions.

Visual Studio version:  17.3.0 Preview 3.0
C# .NET 6.0
CoreWCF.Http Version=1.1.0
CoreWCF.Primitives Version=1.1.0

Message: 
```
System.InvalidOperationException: 'Unable to resolve service for type 'Microsoft.AspNetCore.Authentication.IAuthenticationSchemeProvider' while attempting to activate 'Microsoft.AspNetCore.Authentication.AuthenticationMiddleware'.'
```

Stack trace:
```
System.InvalidOperationException
  HResult=0x80131509
  Message=Unable to resolve service for type 'Microsoft.AspNetCore.Authentication.IAuthenticationSchemeProvider' while attempting to activate 'Microsoft.AspNetCore.Authentication.AuthenticationMiddleware'.
  Source=Microsoft.AspNetCore.Http.Abstractions
  StackTrace:
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Builder.MapWhenExtensions.MapWhen(IApplicationBuilder app, Func`2 predicate, Action`1 configuration)
   at CoreWCF.Channels.ServiceModelHttpMiddleware.BuildBranch()
   at CoreWCF.Channels.ServiceModelHttpMiddleware.EnsureBranchBuilt()
   at CoreWCF.Channels.CommunicationObject.OnOpened()
--- End of stack trace from previous location ---
   at CoreWCF.Configuration.WrappingIServer.<StartAsync>d__9`1.MoveNext()
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.<StartAsync>d__37.MoveNext()
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__12.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Microsoft.AspNetCore.Builder.WebApplication.Run(String url)
   at Program.<Main>$(String[] args) in C:\Users\Brian\source\repos\Voogu_WF\Voogu_WF_Server\Program.cs:line 29
```

https://github.com/CoreWCF/CoreWCF/blob/main/Documentation/Walkthrough.md

**Comment by mconnew** [comment]
@samsp-msft, could you take a look at this? I suspect the problem might be that we recently added support for CoreWCF to call into ASP.NET Core to make it do the authentication. If the walkthrough ends up requiring authentication, previously that was a no-op and now it does something.

**Comment by FriedLychees** [comment]
@VR-Architect FYI - I had the same issue and found that the issue disappeared if I downgraded my CoreWCF packages to Version=1.0.2

**Comment by DarwinOL** [comment]
I commented out .AddServiceEndpoint<EchoService, IEchoService>(new WSHttpBinding(SecurityMode.Transport), "/EchoService/WSHttp"); in Program.cs and got it to build.

**Comment by isham-iqbal** [comment]
The error is only thrown in Kestral server not in IIS in version 1.2.0. Workaround to make this work in kestral is what @DarwinOL suggests.

**Comment by IshamMohamed** [comment]
The error is only thrown in Kestral server not in IIS in version 1.2.0. Workaround to make this work in kestral is what @DarwinOL  suggests.

**Comment by PraveenNunna** [comment]
For me, the issue is with Binding. I was using `new BasicHttpBinding(BasicHttpSecurityMode.TransportCredentialOnly)`.
After I remove `(BasicHttpSecurityMode.TransportCredentialOnly)`, the exception is gone.
