### ISSUE TITLE
NetHttpBinding not working as expected

### ISSUE THREAD

**Issue by spur19** [CoreWCF/CoreWCF#756]
Hi, I am using the NetHttpBinding with a sample application, and it gives me this error:

**Server Side Error** 
```
fail: Microsoft.AspNetCore.Server.HttpSys.MessagePump[0]
      ProcessRequestAsync
System.NullReferenceException: Object reference not set to an instance of an object.
   at CoreWCF.Channels.RequestDelegateHandler.HandleRequest(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at CoreWCF.Channels.ServiceModelHttpMiddleware.InvokeAsync(HttpContext context)
   at CoreWCF.Channels.MetadataMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Server.HttpSys.MessagePump.ProcessRequestAsync(Object requestContextObj)
   at Microsoft.AspNetCore.Server.HttpSys.MessagePump.ProcessRequestAsync(Object requestContextObj)

```
**Client Side Error**
```
Unhandled exception. System.ServiceModel.CommunicationException: The server did not provide a meaningful reply; this might be caused by a contract mismatch, a premature session shutdown or an internal server error.
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args)
   at generatedProxy_1.ReverseString(String )
   at NetCoreClient.Program.CallBasicHttpBinding(String hostAddr) in C:\Users\t-spuri\OneDrive - Microsoft\Desktop\CoreWCFEcho\EchoClient\Program.cs:line 46
   at NetCoreClient.Program.Main(String[] args) in C:\Users\t-spuri\OneDrive - Microsoft\Desktop\CoreWCFEcho\EchoClient\Program.cs:line 19
   at NetCoreClient.Program.<Main>(String[] args)
```

**Server Side Program.cs** 
```
using System.Diagnostics;
using System.Net;
using CoreWCF.Configuration;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;

namespace NetCoreServer
{
    class Program
    {
        static void Main(string[] args)
        {
            IWebHost host = CreateWebHostBuilder(args).Build();
            host.Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
            .UseHttpSys(options =>
            {
                options.AllowSynchronousIO = true;
                options.Authentication.AllowAnonymous = true;
                options.MaxConnections = 2;
                options.MaxRequestBodySize = 30000000;
                options.UrlPrefixes.Add("http://localhost:5005/First");
               
            })  
            .UseStartup<Startup>();
    }
}

```
**Server Side Startup.cs**
```

using System;
using CoreWCF;
using CoreWCF.Configuration;
using CoreWCF.Channels;
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;
using Contract;
using CoreWCF.Description;

namespace NetCoreServer
{
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddServiceModelServices()
                    .AddServiceModelMetadata()
                    .AddSingleton<IServiceBehavior, UseRequestHeadersForMetadataAddressBehavior>();
        }

        public void Configure(IApplicationBuilder app)
        {
            app.UseServiceModel(builder =>
            {
                // Add the Echo Service
                builder.AddService<EchoService>(serviceOptions =>
                {
                    serviceOptions.BaseAddresses.Add(new Uri($"http://localhost:5005/First"));
                })
                // Add a NetHttpBinding endpoint
                .AddServiceEndpoint<EchoService, IEchoService>(new NetHttpBinding(), "");
                               var serviceMetadataBehavior = app.ApplicationServices.GetRequiredService<CoreWCF.Description.ServiceMetadataBehavior>();
                serviceMetadataBehavior.HttpGetEnabled = true;
            });
        }
    }

}
```

**Client Side Program.cs**

```
using System;
using System.ServiceModel;
using System.Threading.Tasks;
using Contract;
using System.Diagnostics;

namespace NetCoreClient
{
    public class Program
    {

        static async Task Main(string[] args)
        {
            Console.Title = "WCF .Net Core Client";
            await CallNetHttpBinding();
        }

        private static async Task CallNetHttpBinding()
        {
            IClientChannel channel = null;

            var binding = new NetHttpBinding();

            var factory = new ChannelFactory<IEchoService>(binding, new EndpointAddress($"http://localhost:5005/First/"));
            factory.Open();
            try
            {


                IEchoService client = factory.CreateChannel();
                channel = client as IClientChannel;
                channel.Open();
                var result = client.ReverseString("Client");
                Console.WriteLine(result);
                channel.Close();
                
                
            }
            finally
            {
                factory.Close();
            }

        }
}
}
```

**Comment by e-i-n-s** [comment]
I encountered the same issue.
It should be possible to circumvent this issue by disabling the WebSocket for the binding on the server side:
```
httpBinding.WebSocketSettings.TransportUsage = WebSocketTransportUsage.Never; 
```

Sample:
```
var httpBinding = new CoreWCF.NetHttpBinding(CoreWCF.Channels.BasicHttpSecurityMode.TransportCredentialOnly); 
httpBinding.WebSocketSettings.TransportUsage = WebSocketTransportUsage.Never;
httpBinding.Security.Transport.ClientCredentialType = CoreWCF.HttpClientCredentialType.Windows;
```

I will prepare a PR to fix the NullReferenceException in `RequestDelegateHandler`. At the moment I face some http.sys issues in a test... 😞

**Comment by rgroenewoudt** [comment]
I'm also running into the same issue.

**Comment by rgroenewoudt** [comment]
This might be better documented: Streaming is only allowed if AllowSynchronousIO is enabled.

**Comment by rgroenewoudt** [comment]
Has anyone found a fix for NetHttpBinding with websockets?

**Comment by simonegli8** [comment]
> This might be better documented: Streaming is only allowed if AllowSynchronousIO is enabled.

And how is AllowSynchronousIO enabled? Can you give an example?

**Comment by rgroenewoudt** [comment]
`
builder.Services.Configure<IISServerOptions>(options =>
{
    options.AllowSynchronousIO = true;
});
`

**Comment by ebrowne-steris** [comment]
If `WebSocketSettings` is included with the `HttpTransportSettings` in the `RequestDelegateHandler` constructor, the `_replyChannelDispatcherTask` fails to be assigned, which causes issues in the `HandleRequest` method - it's supposed to fetch the `_replyChannelDispatcher`, but fails with a null ref exception.

I was able to get around it by excluding the `if(WebSocketOptions == null)` check in the constructor; every handler gets the reply task, so the dispatcher can be created successfully. I am not sure about the ramifications of making this change. Is there a better approach that isn't so indiscriminate? Or am I missing some setting that would bypass this issue altogether?

Any help would be appreciated. Thank you.
