### ISSUE TITLE
System.InvalidOperationException: No authentication handler is registered for the scheme 'Negotiate'. The registered schemes are: Windows. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("Negotiate",...)

### ISSUE THREAD

**Issue by dandesro71** [CoreWCF/CoreWCF#757]
We're using transport Windows authentication.

Client: 
                ((BasicHttpsBinding)binding).Security.Mode = BasicHttpsSecurityMode.Transport;
                ((BasicHttpsBinding)binding).Security.Transport.ClientCredentialType = HttpClientCredentialType.Windows;

Server:
var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddServiceModelServices();
builder.Services.AddServiceModelMetadata();

builder.Services.AddServiceModelConfigurationManagerFile("wcf.config");

builder.Services.AddAuthentication(IISDefaults.AuthenticationScheme);
builder.Services.AddAuthorization();
builder.Services.AddHttpContextAccessor();

builder.Services.AddSingleton<IServiceBehavior, UseRequestHeadersForMetadataAddressBehavior>();

Up to version 1.1.0-alpha.35, it was working without error. After alpha.35, the error we receive is:

System.InvalidOperationException: No authentication handler is registered for the scheme 'Negotiate'. The registered schemes are: Windows. Did you forget to call AddAuthentication().Add[SomeAuthHandler]("Negotiate",...)?
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at CoreWCF.Channels.RequestDelegateHandler.HandleRequest(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at CoreWCF.Channels.ServiceModelHttpMiddleware.InvokeAsync(HttpContext context)
   at CoreWCF.Channels.MetadataMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()

**Comment by mconnew** [comment]
I think you need to do the following:
```
services.AddAuthentication(IISDefaults.AuthenticationScheme)
                    .AddPolicyScheme("Negotiate", "Negotiate", options =>
                    {
                        options.ForwardDefault = IISDefaults.AuthenticationScheme;
                    });
```
A similar approach fixes this problem for HTTP.SYS and I believe (hope?) this fixes it for IIS too. Basically, it expects HttpContext.AuthenticateAsync("Windows") to be called but we're calling HttpContext.AuthenticateAsync("Negotiate"). The code above tells it to map "Negotiate" to Windows.

**Comment by mconnew** [comment]
Closing this issue on the presumption that this solves the problem for you. If it doesn't, feel free to reopen.

**Comment by dandesro71** [comment]
It solved the problem when the client is using:

            client.ChannelFactory.Credentials.Windows.AllowedImpersonationLevel = TokenImpersonationLevel.Delegation;
or
            client.ChannelFactory.Credentials.Windows.AllowedImpersonationLevel = TokenImpersonationLevel.None;

The default is TokenImpersonationLevel.Identification. The error received in the client is:

System.ServiceModel.Security.MessageSecurityException: 'The HTTP request is unauthorized with client authentication scheme 'Negotiate'. The authentication header received from the server was 'Negotiate,NTLM'.'

I cannot ask to all the clients to modify their code to use TokenImpersonationLevel.None . I'm sure this is only something missing in my service configuration. Once again, it was working properly  up to version 1.1.0-alpha.35.

**Comment by dandesro71** [comment]
> Closing this issue on the presumption that this solves the problem for you. If it doesn't, feel free to reopen.

I cannot reopen the issue. Can you do it for me based on my previous comment?

**Comment by mconnew** [comment]
It worked on an earlier version as CoreWCF wasn't enforcing authentication, that was needed to be done in application code (when configuring your middleware) before the call into CoreWCF. When you saw behavior change, it's because we added code to have CoreWCF enforce authentication, and also apply the authenticated claims principal to the ServiceSecurityContext.  
It's strange that Delegation works but Identification doesn't as Delegation requires greater permission. I presume you are using .NET Framework for your client as the WCF Core Client can't apply the ImpersonationLevel to the http client as they don't support that. It's a no-op on WCF Core client.  
According to the documentation [here](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-6.0&tabs=visual-studio#impersonation), asp.net core doesn't support any impersonation other than Authentication. We also don't set anything on the service side to configure authentication.  

Which version of .NET/asp.net core are you using? I wonder if this is an IIS setting issue as I believe IIS is the component which handles the Windows authentication. Have you tried running your .NET Framework WCF service on the same IIS server? Can you verify that you have enabled Windows auth for the relevant site/application in IIS? Are you using the default app pool user for the application? If you have are running as a specific user account, you won't be able to use the default SPN. I actually suspect that last one is the issue. If HttpWebRequest can't obtain a Kerberos token from the domain controller, it will fall back to NTLM. As the target SPN/server needs special permissions for delegation, I would expect requesting a kerberos token for delegation use to fail, so falling back to NTLM might be happening. Using Identification will result in successfully getting the kerberos ticket, but then if the server is running as a different user, it won't be able to complete the authentication handshake. I would normally expect a different error message saying you are using the wrong target identity, but I can't guarantee that would always be the case, and this is the only thing I can think of which would explain delegation working when identification doesn't.

**Comment by dandesro71** [comment]
Thank for your quick and detailed answer. The document link you provided allowed me to change something for negotiate authentication:

```
//builder.Services.AddAuthentication(IISDefaults.AuthenticationScheme)
//                .AddPolicyScheme("Negotiate", "Negotiate", options => { options.ForwardDefault = IISDefaults.AuthenticationScheme; });

builder.Services.AddAuthentication(NegotiateDefaults.AuthenticationScheme).AddNegotiate();
```
But it didn't solve the problem with TokenImpersonationLevel.Identification.

> Which version of .NET/asp.net core are you using?
ASP.NET 6

> Have you tried running your .NET Framework WCF service on the same IIS server?
I only have a CoreWCF service running in ASP.NET 6. For my tests, the client is on the same machine as the IIS Server

> Can you verify that you have enabled Windows auth for the relevant site/application in IIS?
Everything is enabled

> Are you using the default app pool user for the application? If you have are running as a specific user account, you won't be able to use the default SPN
We're using a domain account for the app pool and SPN were setup long time ago when we were still using .NET Framework WCF service

I'm sure it's a small detail in the new configuration that is failing but it can be difficult to debug. For now, I'll tell the user to use  TokenImpersonationLevel.None if they get an error. Hopefully, they won't get too many.

**Comment by mconnew** [comment]
> We're using a domain account for the app pool and SPN were setup long time ago when we were still using .NET Framework WCF service

I think this might be the cause. Are you using in-process or out-of-process hosting? IIS can use Kernel mode authentication in HTTP.SYS and I'm wondering if the way your app is hosted is subverting this. I think you can force/encourage kernel mode auth by explicitly configuring it in a web.config. Modifying slightly from the [documentation here,](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-6.0&tabs=visual-studio#iis) having a web.config which looks like this might help:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <security>
        <authentication>
          <anonymousAuthentication enabled="false" />
          <windowsAuthentication enabled="true" useKernelMode="true"/>
        </authentication>
      </security>
    </system.webServer>
  </location>
</configuration>
```
If the clients are only going to be WCF (and not WCF Core client), then you could switch the identity to be a UPN instead, but unfortunately HttpClient in .NET Core/.NET doesn't support UPN's so it would be a .NET Famework only solution.

**Comment by dandesro71** [comment]
> Are you using in-process or out-of-process hosting?

InProcess.  

userKernelMode was already true.

**Comment by mconnew** [comment]
@dandesro71, I just noticed something in your earlier reply, that the client and server are on the same machine. Is the client using the hostname in the url or localhost? If it's using localhost, it will fall back to NTLM which might have a difference in behavior.

**Comment by dandesro71** [comment]
To debug, I'm running the client and the IIS server on my computer. But we also have a test server and a production server. We get the same error if we don't change the TokenImpersonationLevel to None. For now, I've asked the developers of the client applications to modify their code and deploy new clients with TokenImpersonationLevel.None. Fortunately, the clients are internal and the error was reported only by 3 or 4 developpers so the impacts are still manageable.

**Comment by mvarblow** [comment]
I've run into the same problem. If I change my WCF clients (.NET Framework) to TokenImpersonationLevel.None or .Delegation then everything is fine. Unfortunately, I can't change all the clients.

**Comment by mvarblow** [comment]
In case it helps, here's a complete walkthrough showing how to reproduce this problem. It's fairly simple and just boils down to this: a .NET Framework WCF client app is not able to call a CoreWCF server app that requires Windows authentication -- unless the client changes the default impersonation mode from Identification to Delegate or None.

This repo includes the completed demo: https://github.com/mvarblow/CoreWcfAuthDemo

### Create the CoreWCF app which requires Windows authentication

```
dotnet new corewcf --name CoreWCFDemoServer --framework net7.0
cd CoreWCFDemoServer
dotnet add package Microsoft.AspNetCore.Authentication.Negotiate
```

Add authentication and authorization services in Program.cs:
```
builder.Services.AddAuthentication(NegotiateDefaults.AuthenticationScheme).AddNegotiate();
builder.Services.AddAuthorization();
```

Replace this line:
```
    serviceBuilder.AddServiceEndpoint<Service, IService>(new BasicHttpBinding(BasicHttpSecurityMode.Transport), "/Service.svc");
```

With these three lines:
```
    var binding = new BasicHttpBinding(BasicHttpSecurityMode.Transport);
    binding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Windows;
    serviceBuilder.AddServiceEndpoint<Service, IService>(binding, "/Service.svc");
```

Add [Authorize] attribute to Service.GetData method in IService.cs

```
        [Authorize]
        public string GetData(int value)
```

Start debugging in VS. Copy the service WSDL URL, e.g.
https://localhost:7209/service.svc?wsdl

### Create a .NET 7 Client Application

Create a new console application:
`dotnet new console --name CoreWCFDemoClient --framework net7.0
`

Right-click on the project in VS and use Add > Service Reference. Pick WCF Web Service.  Paste in the service URL for the running Core WCF service. Click through the rest of the wizard.

Add this to the CoreWCFDemoClient Program.cs:

```
var client = new ServiceReference1.ServiceClient();
client.ClientCredentials.Windows.ClientCredential = System.Net.CredentialCache.DefaultNetworkCredentials;
Console.WriteLine(await client.GetDataAsync(12));
```

Run the client. It should print:

```
Hello, World!
You entered: 12
```

### Create a .NET Framework Client Application

Now, create a .NET Framework console application from Visual Studio.
Again, right-click on the project, Add Service Reference. Paste in the service WSDL URL and complete the dialog. In Program.cs add the following to the Main method:

```
            var client = new ServiceReference1.ServiceClient();
            client.ClientCredentials.Windows.ClientCredential = System.Net.CredentialCache.DefaultNetworkCredentials;
            Console.WriteLine(client.GetData(12));
```

Run the legacy client. It should print:

`You entered: 12
`

Everything works fine as long as you run the CoreWCF service from the command line using Kestrel. 

### Host the Core WCF Server in IIS

Stop running CoreWCFDemoServer. Now let's deploy it to IIS. Publish the CoreWCFDemoServer project to a folder. In IIS, create a new site using the publish folder as the physical path. Use the same port number that was previously used for running CoreWCFDemoServer from Visual Studio.

![image](https://user-images.githubusercontent.com/1827487/226147921-9a21318e-ea94-4f0f-9ba7-ff3a7bcb21ce.png)

Change the site's app pool to "No managed code".

![image](https://user-images.githubusercontent.com/1827487/226147933-a5b5464f-92bf-4e1c-a174-e0132a44fe6e.png)

Enable Windows Authentication and disable Anonymous Authentication for the CoreWCFDemoServer site in IIS Manager.

![image](https://user-images.githubusercontent.com/1827487/226147942-0da14399-a35b-41a9-ae0c-cec2caa75666.png)

Now run the CoreWCFDemoClient. It should again run successfully and print:

```
Hello, World!
You entered: 12
```

Now run the LegacyWCFClient. It will fail.

```
Unhandled Exception: System.ServiceModel.Security.MessageSecurityException: The HTTP request is unauthorized with client authentication scheme 'Negotiate'. The authentication header received from the server was 'Negotiate,NTLM'. ---> System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.GetResponse()
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   --- End of inner exception stack trace ---

Server stack trace:
   at System.ServiceModel.Channels.HttpChannelUtilities.ValidateAuthentication(HttpWebRequest request, HttpWebResponse response, WebException responseException, HttpChannelFactory`1 factory)
   at System.ServiceModel.Channels.HttpChannelUtilities.ValidateRequestReplyResponse(HttpWebRequest request, HttpWebResponse response, HttpChannelFactory`1 factory, WebException responseException, ChannelBinding channelBinding)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at LegacyWcfClient.ServiceReference1.IService.GetData(Int32 value)
   at LegacyWcfClient.ServiceReference1.ServiceClient.GetData(Int32 value) in C:\Temp\Code\CoreWcfAuthDemo\LegacyWcfClient\Connected Services\ServiceReference1\Reference.cs:line 122
   at LegacyWcfClient.Program.Main(String[] args) in C:\Temp\Code\CoreWcfAuthDemo\LegacyWcfClient\Program.cs:line 15
```

If you change the allowed impersonation level in the LegacyWCFClient to None or Delegation before calling the service then the call succeeds, e.g.

```
            client.ClientCredentials.Windows.AllowedImpersonationLevel = System.Security.Principal.TokenImpersonationLevel.Delegation;
```
or
```
           client.ClientCredentials.Windows.AllowedImpersonationLevel = System.Security.Principal.TokenImpersonationLevel.None;
```

But with the default value it fails:

```
            client.ClientCredentials.Windows.AllowedImpersonationLevel = System.Security.Principal.TokenImpersonationLevel.Identification;
```

### Summary

With a CoreWCF service configured to require Windows authentication, .NET Core clients work fine. But .NET Framework clients fail if using the default impersonation level.

It appears that Windows authentication is working successfully in IIS. We can see the successful authentication events in the security event log. But it appears that Microsoft.AspNetCore.Authentication.Negotiate does not flow the user principle over into ASP.NET Core / CoreWCF?

This is preventing us from successfully porting our application, which has legacy callers which need to continue working with the new service. The legacy callers use the default impersonation level.

**Comment by stcpottdav** [comment]
Is this going to be fixed in 1.4? I tried the preview package from nuget.org and it still happens.

**Comment by stcpottdav** [comment]
The fix will not be done on the Microsoft side and will need to be done in CoreWcf as Asp.Net Core does not support impersonation.

Sent: Tuesday, September 3, 2024 12:14 PM
Subject: RE: [EXTERNAL] RE: AspNetCoreModuleV2: Windows ... - TrackingID#2408080040007701

Hello team,

Sorry for the delay, I had been sending emails to Fernando and didn’t notice I was not including David.
 
Thank you for bringing this issue to our attention and for your patience. After reviewing the details, it appears that this behavior is not a bug, but rather a design choice in ASP.Net Core, which does not support Impersonation. You can find more information on this in the official documentation in the link below.
Configure Windows Authentication in ASP.NET Core | Microsoft Learn
Given this limitation, the current workaround in place seems to be the appropriate solution. This appears to be more of a compatibility issue between the original implementation of the client code and CoreWCF.
 
Please let me know if you have any further questions or if there's anything else I can assist with.
 
Thank you
 
Best regards,
Emmanuel Gutierrez Calderon
Support Engineer Web Apps Developer
For Microsoft Customer Support

**Comment by mconnew** [comment]
I hadn't noticed that code snippet in the asp.net core documentation before. I think there's enough info here to make things "just work" in CoreWCF, but it's not going to be immediate as the security on this needs to be implemented correctly taking into account all the permutations. Until I have the time to get to that, I think you can do a slightly easier workaround in CoreWCF than use a custom native module. There's varying degrees of solution depending on how much code you want to have. At it's simplest, you can do the following:
```csharp
[ServiceContract]
public interface IService
{
    [OperationContract]
    public void DoWork(string data);
}

// Must be partial for DI injection code gen
public partial class Service : IService
{
    public void DoWork(string data, [CoreWCF.Injected]HttpContext httpContext)
    {
        var user = (WindowsIdentity)httpContext.User.Identity;
        await WindowsIdentity.RunImpersonatedAsync(user.AccessToken, async () =>
        {
            DoWorkImpl(data);
        });
    }

    public void DoWorkImpl(string data)
    {
        // Original implementation
    }
}
```

You could go a step further and implement this in as a full IServiceBehavior installing an IOperationInvoker which does the above:
```csharp
internal class ImpersonatingServiceBehavior : IServiceBehavior
{
    private static ImpersonatingOperationBehavior s_iob = new();
    public void AddBindingParameters(ServiceDescription serviceDescription, ServiceHostBase serviceHostBase, Collection<ServiceEndpoint> endpoints, BindingParameterCollection bindingParameters) { }
    public void Validate(ServiceDescription serviceDescription, ServiceHostBase serviceHostBase) { }

    public void ApplyDispatchBehavior(ServiceDescription serviceDescription, ServiceHostBase serviceHostBase)
    {
        foreach (ServiceEndpoint endpoint in serviceDescription.Endpoints)
        {
            foreach (OperationDescription operation in endpoint.Contract.Operations)
            {
                operation.OperationBehaviors.Add(s_iob);
            }
        }
    }
}

internal class ImpersonatingOperationBehavior : IOperationBehavior
{
    public void AddBindingParameters(OperationDescription operationDescription, BindingParameterCollection bindingParameters) { }
    public void ApplyClientBehavior(OperationDescription operationDescription, ClientOperation clientOperation) { }
    public void Validate(OperationDescription operationDescription) { }

    public void ApplyDispatchBehavior(OperationDescription operationDescription, DispatchOperation dispatchOperation)
    {
        dispatchOperation.Invoker = new ImpersonatingOperationInvoker(dispatchOperation.Invoker);
    }
}

internal class ImpersonatingOperationInvoker
{
    private readonly IOperationInvoker _innerInvoker;

    public ImpersonatingOperationInvoker(IOperationInvoker innerInvoker)
    {
        _innerInvoker = innerInvoker;
    }

    public object[] AllocateInputs() => _innerInvoker.AllocateInputs();

    public async ValueTask<(object returnValue, object[] outputs)> InvokeAsync(object instance, object[] inputs)
    {
        if (OperationContext.Current.IncomingMessageProperties
           .TryGetValue<HttpContext>("Microsoft.AspNetCore.Http.HttpContext", out HttpContext httpContext)
        {
            var user = (WindowsIdentity)httpContext.User.Identity;
            return await WindowsIdentity.RunImpersonatedAsync(user.AccessToken, () =>
            {
                return _innerInvoker.InvokeAsync(instance, inputs).AsTask();
            });
        }    
        return await _innerInvoker.InvokeAsync(instance, inputs);
    }
}
```

Then in your app, you can add `ImpersonatingServiceBehavior` as an `IServiceBehavior` to DI via `services.AddSingleton<IServiceBehavior, ImpersonatingServiceBehavior>();`. There's very little error detection here, you might want to add some such as check `user.ImpersonationLevel` to make sure it can be impersonated.
