### ISSUE TITLE
Does CoreWCF support multiple contracts at the same port?

### ISSUE THREAD

**Issue by MsLilu2** [CoreWCF/CoreWCF#782]
When porting my .net framework project to .net 6, I first got "Error while reading message framing format at position 423 of stream (state: EnvelopeEnd)" on one of my services, let's call it Service2 (registered with binding of SecurityMode.Transport), I thought maybe something wrong with the packets received on server side, then I modified the client to access the same Service2 (at different port) which is registered with binding of SecurityMode.None, but got the second error "AddressFilter mismatch".

I have no idea what is wrong with my Service2, but the client did succeed in accessing another service Service1 at both 8000 and 8002 port. The service behaviors are configured the same in all my services. To make it easier to go through, I simplify my code as below:

Service behavior
`[ServiceBehavior(InstanceContextMode = InstanceContextMode.Single, ConcurrencyMode = ConcurrencyMode.Multiple, IncludeExceptionDetailInFaults = true)]`

Program.cs
```c#
using (IHost host = CreateWebHostBuilder().Build())
using (IHost hostSecure = CreateWebHostBuilderSecure().Build())
{
    await Task.WhenAny(
                            host.RunAsync(),
                            hostSecure.RunAsync());
}

private static IHostBuilder CreateWebHostBuilder()
{
    return Host.CreateDefaultBuilder()
                      .UseWindowsService()
                      .ConfigureWebHostDefaults(webBuilder =>
                      {
                          webBuilder.UseNetTcp(IPAddress.IPv6Any, 8000).UseStartup<Startup>();
                      });
 }

private static IHostBuilder CreateWebHostBuilderSecure()
{
    return Host.CreateDefaultBuilder()
                      .ConfigureWebHostDefaults(webBuilder =>
                      {
                          webBuilder.UseNetTcp(IPAddress.IPv6Any, 8002).UseStartup<StartupSecure>();
                      });
 }
```
Startup.cs
```c#
public void ConfigureServices(IServiceCollection services)
{
    services.AddServiceModelServices()
                .AddServiceModelMetadata()
                .AddSingleton<IServiceBehavior, UseRequestHeadersForMetadataAddressBehavior>();
}

public void Configure(IApplicationBuilder app)
{
    var binding = new NetTcpBinding(SecurityMode.None);
    netTcpBinding.Security.Transport.ClientCredentialType = TcpClientCredentialType.None;

    app.UseServiceModel(builder =>
    {
            builder.AddService<Service1>()
                       .AddServiceEndpoint<Service1, IService1>(binding, new Uri("net.tcp://localhost:8000/Service1"))
                       .ConfigureServiceHostBase<Service1>(serviceHost => ...);

           builder.AddService<Service2>()
                       .AddServiceEndpoint<Service2, IService2>(binding, new Uri("net.tcp://localhost:8000/Service2"))
                       .ConfigureServiceHostBase<Service2>(serviceHost => ...);
          
           builder.AddService<Service3>()
                       .AddServiceEndpoint<Service3, IService3>(binding, new Uri("net.tcp://localhost:8000/Service3"))
                       .ConfigureServiceHostBase<Service3>(serviceHost => ...);
}
```
StartupSecure.cs
```c#
public void ConfigureServices(IServiceCollection services)
{
    services.AddServiceModelServices()
                .AddServiceModelMetadata()
                .AddSingleton<IServiceBehavior, UseRequestHeadersForMetadataAddressBehavior>();
}

public void Configure(IApplicationBuilder app)
{
    var binding = new NetTcpBinding(SecurityMode.Transport);
    netTcpBinding.Security.Transport.ClientCredentialType = TcpClientCredentialType.None;

    app.UseServiceModel(builder =>
    {
            builder.AddService<Service1>()
                       .AddServiceEndpoint<Service1, IService1>(binding, new Uri("net.tcp://localhost:8002/Service1"))
                       .ConfigureServiceHostBase<Service1>(serviceHost => ...);

           builder.AddService<Service2>()
                       .AddServiceEndpoint<Service2, IService2>(binding, new Uri("net.tcp://localhost:8002/Service2"))
                       .ConfigureServiceHostBase<Service2>(serviceHost => ...);
          
           builder.AddService<Service3>()
                       .AddServiceEndpoint<Service3, IService3>(binding, new Uri("net.tcp://localhost:8002/Service3"))
                       .ConfigureServiceHostBase<Service3>(serviceHost => ...);
}

```

First error:
```
------------------ ProtocolException: Error while reading message framing format at position 423 of stream (state: EnvelopeEnd)
------------------ InvalidDataException: More data was expected, but EOF was reached.

ProtocolException callstack:
   at System.ServiceModel.Channels.SingletonConnectionReader.SingletonInputConnectionStream.ProcessEof()
   at System.ServiceModel.Channels.SingletonConnectionReader.SingletonInputConnectionStream.ReadCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.ServiceModel.Channels.SingletonConnectionReader.SingletonInputConnectionStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.ReadByte()
   at System.ServiceModel.Channels.MaxMessageSizeStream.ReadByte()
   at System.Xml.XmlBufferReader.TryEnsureByte()
   at System.Xml.XmlBufferReader.get_EndOfFile()
   at System.Xml.XmlBinaryReader.ReadNode()
   at System.ServiceModel.Channels.Message.ReadFromBodyContentsToEnd(XmlDictionaryReader reader, EnvelopeVersion envelopeVersion)
   at System.ServiceModel.Channels.MessageFault.CreateFault(Message message, Int32 maxBufferSize)
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass6_0.<CreateTask>b__0(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   at System.Threading.Tasks.TaskFactory`1.<>c__DisplayClass44_0`3.<FromAsyncImpl>b__0(IAsyncResult iar)
   at System.Runtime.AsyncResult.Complete(Boolean completedSynchronously)
   at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.FinishSend(IAsyncResult result, Boolean completedSynchronously)
   at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.SendCallback(IAsyncResult result)
   at System.Runtime.Fx.AsyncThunk.UnhandledExceptionFrame(IAsyncResult result)
   at System.Runtime.AsyncResult.Complete(Boolean completedSynchronously)
   at System.ServiceModel.Channels.StreamedFramingRequestChannel.StreamedFramingAsyncRequest.OnReceiveReply(IAsyncResult result)
   at System.Runtime.Fx.AsyncThunk.UnhandledExceptionFrame(IAsyncResult result)
   at System.Runtime.AsyncResult.Complete(Boolean completedSynchronously)
   at System.ServiceModel.Channels.SingletonConnectionReader.ReceiveAsyncResult.OnReceiveScheduled(Object state)
   at System.Runtime.ActionItem.DefaultActionItem.TraceAndInvoke()
   at System.Runtime.ActionItem.CallbackHelper.InvokeWithoutContext(Object state)
   at System.Runtime.IOThreadScheduler.ScheduledOverlapped.IOCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Runtime.Fx.IOCompletionThunk.UnhandledExceptionFrame(UInt32 error, UInt32 bytesRead, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
```

Second error:
```
------------------ EndpointNotFoundException: The message with To 'net.tcp://<MyAddress>:8000/Service2' cannot be processed at the receiver, due to an AddressFilter mismatch at the EndpointDispatcher.  Check that the sender and receiver's EndpointAddresses agree.

 EndpointNotFoundException callstack:
    at System.ServiceModel.Channels.ServiceChannel.ThrowIfFaultUnderstood(Message reply, MessageFault fault, String action, MessageVersion version, FaultConverter faultConverter)
    at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
    at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
    at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass6_0.<CreateTask>b__0(IAsyncResult asyncResult)
    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
    at System.Threading.Tasks.TaskFactory`1.<>c__DisplayClass44_0`3.<FromAsyncImpl>b__0(IAsyncResult iar)
    at System.Runtime.AsyncResult.Complete(Boolean completedSynchronously)
    at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.FinishSend(IAsyncResult result, Boolean completedSynchronously)
    at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.SendCallback(IAsyncResult result)
    at System.Runtime.Fx.AsyncThunk.UnhandledExceptionFrame(IAsyncResult result)
    at System.Runtime.AsyncResult.Complete(Boolean completedSynchronously)
    at System.ServiceModel.Channels.StreamedFramingRequestChannel.StreamedFramingAsyncRequest.OnReceiveReply(IAsyncResult result)
    at System.Runtime.Fx.AsyncThunk.UnhandledExceptionFrame(IAsyncResult result)
    at System.Runtime.AsyncResult.Complete(Boolean completedSynchronously)
    at System.ServiceModel.Channels.SingletonConnectionReader.ReceiveAsyncResult.OnReceiveScheduled(Object state)
    at System.Runtime.ActionItem.DefaultActionItem.TraceAndInvoke()
    at System.Runtime.ActionItem.CallbackHelper.InvokeWithoutContext(Object state)
    at System.Runtime.IOThreadScheduler.ScheduledOverlapped.IOCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
    at System.Runtime.Fx.IOCompletionThunk.UnhandledExceptionFrame(UInt32 error, UInt32 bytesRead, NativeOverlapped* nativeOverlapped)
    at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
```

**Comment by MsLilu2** [comment]
Update: I was able to confirm that registering multiple contracts at the same port is feasible using a small demo.

**Comment by MsLilu2** [comment]
I was trying to narrow down the issue today, I commented all codes related to StartupSecure.cs to focus on investigating the AddressFilter mismatch issue. I captured the network packets when the client and server are running, then saw a "destination unreachable" packets before it threw "net.tcp://<MyAddress>:8000/Service2' cannot be processed at the receiver, due to an AddressFilter mismatch at the EndpointDispatcher.  Check that the sender and receiver's EndpointAddresses agree."

![image](https://user-images.githubusercontent.com/109129479/183401638-72530e51-9bce-4bb5-9f11-45657944946b.png)

I googled, and found this potential [solution ](https://stackoverflow.com/questions/9293721/addressfilter-mismatch-at-the-endpointdispatcher-the-msg-with-to), @mconnew do you have any idea if it is a correct answer, and if yes, how do I implement this into my service(I don't have any xml based configuration right now)?

![image](https://user-images.githubusercontent.com/109129479/183401877-80be79ec-16a9-4b83-bd74-c24c29a70dd4.png)

**Comment by iyrwis** [comment]
I also encountered this problem yesterday, how to associate multiple contracts with one serviceEndpoint is indeed a problem.

**Comment by MsLilu2** [comment]
> I also encountered this problem yesterday, how to associate multiple contracts with one serviceEndpoint is indeed a problem. Btw, which type of binding did you use? I use nettcpbinding.

Same netTcpBinding.

**Comment by iyrwis** [comment]
> Update: I was able to confirm that registering multiple contracts at the same port is feasible using a small demo.

Can you share your latest demo which can register multiple contracts at the same port based on Nettcpbinding? Thanks

**Comment by MsLilu2** [comment]
@iyrwis I uploaded my demo [here](https://github.com/MsLilu2/CoreWCF-Demo), you could check the startup1.cs of NetCoreServer project to see my configuration. If you run NetCoreServer locally, please kick off the NetCore version of client, you will see the communication works. What I am still suffering is the address filter mismatch error when I make the NetTcpBinding transfer modes to be Streamed in client side, you will see the error if you kick off the NetFramework version of client.

**Comment by iyrwis** [comment]
Thanks so much

**Comment by iyrwis** [comment]
I also found a phenomeno: if I not set binding.TransferMode = TransferMode.Streamed, the NetFramework WCF client can talk to the CoreWCF server which use nettcpbinding and has multiple contracts for one port. If I set this to streamed, it would occur the issue:

![image](https://user-images.githubusercontent.com/37793755/183842631-80099b5e-d1eb-485b-82b0-03000eeb05d8.png)

**Comment by MsLilu2** [comment]
> 

When you say set binding.TransferMode = TransferMode.Streamed and get "More data was expected, but EOF was reached", do you mean the client side NetTcpBinding setting? What transfer mode are you using in your the server side?

**Comment by mconnew** [comment]
@iyrwis, are you able to provide a simple repro project? This is starting to sound like an implementation bug which only manifests with some scenarios.

**Comment by iyrwis** [comment]
[Server-Client-Communication-WCF-main (2).zip](https://github.com/CoreWCF/CoreWCF/files/9305841/Server-Client-Communication-WCF-main.2.zip)

Sure. That's my demo code, when you remove the 14th line of the Program.cs of WCF-Client-Windows, you find that it can work. Anyway, after adding this line, the problem I just mentioned will appear.

![image](https://user-images.githubusercontent.com/37793755/184059353-18e15240-6e87-49d0-b587-ac68af789900.png)

**Comment by iyrwis** [comment]
[Server-Client-Communication-WCF-Demo.zip](https://github.com/CoreWCF/CoreWCF/files/9305871/Server-Client-Communication-WCF-Demo.zip)

Here is my demo. You will found when you remove the 14th line in Program.cs for WCF Client, the communication would be successfull. While if you add the 14th line, the above issue will happen.

![image](https://user-images.githubusercontent.com/37793755/184059815-71f86d6d-2f4c-4892-8039-277ff7d4b099.png)

**Comment by iyrwis** [comment]
> @iyrwis When you say set binding.TransferMode = TransferMode.Streamed and get "More data was expected, but EOF was reached", do you mean the client side NetTcpBinding setting? What transfer mode are you using in your the server side?

Indeed it's in client side setting. The server side setting is still the Stream mode for nettcpbinding.

**Comment by mconnew** [comment]
@iyrwis, I've tracked down the problem to caching of a reply channel. It's the RequestContext that knows how to reply back to the original request so we can reuse the same reply channel for all clients. The bug is because of the difference in hosting model in CoreWCF and WCF. The class where this code lives is common for a WebHost, but in WCF it's common to a ServiceHost. This means in WCF a single instance for the service type was fine, but for CoreWCF we need to differentiate between different services.

**Comment by Pavel-Ishutin** [comment]
We had the same problem. We have one service with two contracts. One contract - RequestReply, other - OneWay. 

Endpoints addresses are as follows:

http://localhost/serviceName/soapbinary
http://localhost/serviceName/soapbinary/oneway
http://localhost/serviceName/soapbinary/streamed
http://localhost/serviceName/soapbinary/streamed/oneway

Same endpoints for sending messages as text, only address _soaptext_.

When we add the endpoints in the order as specified, we get an error:
_The message with To 'http://localhost/service.svc/soapbinary/oneway' cannot be processed at the receiver, due to an AddressFilter mismatch at the EndpointDispatcher.  Check that the sender and receiver's EndpointAddresses agree._

If address /soapbinary/oneway is added first, then everything is fine. 
Address /streamed still throws an error.

If you remove the segments from the address, then everything works fine, but compatibility with the previous version is required.

**Comment by mconnew** [comment]
@Pavel-Ishutin, I think that might be an unrelated issue. I've created a fix for the issue seen here. It would be great to know if it does fix what you are seeing.

**Comment by Pavel-Ishutin** [comment]
> I think that might be an unrelated issue. I've created a fix for the issue seen here. It would be great to know if it does fix what you are seeing.

What branch is this fix in?
