### ISSUE TITLE
NetCoreServer build has errors cannot find IWebHostBuilder, IServiceCollection, IApplicationBuilder

### ISSUE THREAD

**Issue by dgxhubbard** [CoreWCF/CoreWCF#80]
I pulled down the latest source today in a zip file, extracted and tried to build I had error not finding some types: IWebHostBuilder, IServiceCollection, IApplicationBuilder. This might be related to [issue 79](https://github.com/CoreWCF/CoreWCF/issues/79)

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'IWebHostBuilder' could not be found (are you missing a using directive or an assembly reference?)	NetCoreServer	C:\Repository\CoreWCF\CoreWCF-master\src\Samples\NetCoreServer\Program.cs	17	Active
Error	CS0246	The type or namespace name 'IServiceCollection' could not be found (are you missing a using directive or an assembly reference?)	NetCoreServer	C:\Repository\CoreWCF\CoreWCF-master\src\Samples\NetCoreServer\Startup.cs	13	Active
Error	CS0246	The type or namespace name 'IApplicationBuilder' could not be found (are you missing a using directive or an assembly reference?)	NetCoreServer	C:\Repository\CoreWCF\CoreWCF-master\src\Samples\NetCoreServer\Startup.cs	18	Active

**Comment by dgxhubbard** [comment]
Forgot to add these errors:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0006	Metadata file 'C:\Repository\CoreWCF\CoreWCF-master\bin\Debug\CoreWCF.Http\netstandard2.0\CoreWCF.Http.dll' could not be found	CoreWCF.Http.Tests (netcoreapp2.1)	C:\Repository\CoreWCF\CoreWCF-master\src\CoreWCF.Http\tests\CSC	1	Active
Error	CS0006	Metadata file 'C:\Repository\CoreWCF\CoreWCF-master\bin\Debug\CoreWCF.Primitives\netstandard2.0\CoreWCF.Primitives.dll' could not be found	CoreWCF.Http.Tests (netcoreapp2.1)	C:\Repository\CoreWCF\CoreWCF-master\src\CoreWCF.Http\tests\CSC	1	Active
Error		DirectoryNotFoundException: Can't find the .git directory in 
   at GitVersion.GitPreparer.GetDotGitDirectoryInternal() in D:\a\1\s\src\GitVersionCore\GitPreparer.cs:line 73
   at GitVersion.GitPreparer.GetDotGitDirectory() in D:\a\1\s\src\GitVersionCore\GitPreparer.cs:line 25
   at GitVersion.GitVersionCalculator.CalculateVersionVariables() in D:\a\1\s\src\GitVersionCore\GitVersionCalculator.cs:line 54
   at GitVersion.MSBuildTask.GitVersionTaskExecutor.WriteVersionInfoToBuildLog(WriteVersionInfoToBuildLog task) in D:\a\1\s\src\GitVersionTask\GitVersionTaskExecutor.cs:line 65
   at GitVersion.MSBuildTask.GitVersionTasks.<>c__DisplayClass3_0.<WriteVersionInfoToBuildLog>b__0(IGitVersionTaskExecutor executor) in D:\a\1\s\src\GitVersionTask\GitVersionTasks.cs:line 20
   at GitVersion.MSBuildTask.GitVersionTasks.ExecuteGitVersionTask[T](T task, Action`1 action) in D:\a\1\s\src\GitVersionTask\GitVersionTasks.cs:line 31
	CoreWCF.NetTcp	C:\Users\dgxhubbard\.nuget\packages\gitversiontask\5.1.2\build\GitVersionTask.targets	10	
Error	CS0006	Metadata file 'C:\Repository\CoreWCF\CoreWCF-master\bin\Debug\CoreWCF.NetTcp\netstandard2.0\CoreWCF.NetTcp.dll' could not be found	CoreWCF.NetTcp.Tests (netcoreapp2.1)	C:\Repository\CoreWCF\CoreWCF-master\src\CoreWCF.NetTcp\tests\CSC	1	Active
Error	CS0006	Metadata file 'C:\Repository\CoreWCF\CoreWCF-master\bin\Debug\CoreWCF.Primitives\netstandard2.0\CoreWCF.Primitives.dll' could not be found	CoreWCF.NetTcp.Tests (netcoreapp2.1)	C:\Repository\CoreWCF\CoreWCF-master\src\CoreWCF.NetTcp\tests\CSC	1	Active
Error		DirectoryNotFoundException: Can't find the .git directory in 
   at GitVersion.GitPreparer.GetDotGitDirectoryInternal() in D:\a\1\s\src\GitVersionCore\GitPreparer.cs:line 73
   at GitVersion.GitPreparer.GetDotGitDirectory() in D:\a\1\s\src\GitVersionCore\GitPreparer.cs:line 25
   at GitVersion.GitVersionCalculator.CalculateVersionVariables() in D:\a\1\s\src\GitVersionCore\GitVersionCalculator.cs:line 54
   at GitVersion.MSBuildTask.GitVersionTaskExecutor.WriteVersionInfoToBuildLog(WriteVersionInfoToBuildLog task) in D:\a\1\s\src\GitVersionTask\GitVersionTaskExecutor.cs:line 65
   at GitVersion.MSBuildTask.GitVersionTasks.<>c__DisplayClass3_0.<WriteVersionInfoToBuildLog>b__0(IGitVersionTaskExecutor executor) in D:\a\1\s\src\GitVersionTask\GitVersionTasks.cs:line 20
   at GitVersion.MSBuildTask.GitVersionTasks.ExecuteGitVersionTask[T](T task, Action`1 action) in D:\a\1\s\src\GitVersionTask\GitVersionTasks.cs:line 31
	CoreWCF.Primitives	C:\Users\dgxhubbard\.nuget\packages\gitversiontask\5.1.2\build\GitVersionTask.targets	10	
Error	CS0006	Metadata file 'C:\Repository\CoreWCF\CoreWCF-master\bin\Debug\CoreWCF.Primitives\netstandard2.0\CoreWCF.Primitives.dll' could not be found	CoreWCF.Primitives.Tests (netcoreapp2.1)	C:\Repository\CoreWCF\CoreWCF-master\src\CoreWCF.Primitives\tests\CSC	1	Active
Error	CS0006	Metadata file 'C:\Repository\CoreWCF\CoreWCF-master\bin\Debug\CoreWCF.Http\netstandard2.0\CoreWCF.Http.dll' could not be found	NetCoreServer	C:\Repository\CoreWCF\CoreWCF-master\src\Samples\NetCoreServer\CSC	1	Active
Error	CS0006	Metadata file 'C:\Repository\CoreWCF\CoreWCF-master\bin\Debug\CoreWCF.NetTcp\netstandard2.0\CoreWCF.NetTcp.dll' could not be found	NetCoreServer	C:\Repository\CoreWCF\CoreWCF-master\src\Samples\NetCoreServer\CSC	1	Active
Error	CS0006	Metadata file 'C:\Repository\CoreWCF\CoreWCF-master\bin\Debug\CoreWCF.Primitives\netstandard2.0\CoreWCF.Primitives.dll' could not be found	NetCoreServer	C:\Repository\CoreWCF\CoreWCF-master\src\Samples\NetCoreServer\CSC	1	Active

**Comment by dgxhubbard** [comment]
Issue 79 answered the question
