### ISSUE TITLE
NetTcp service does not work in WSL or Linux Container

### ISSUE THREAD

**Issue by andymartin** [CoreWCF/CoreWCF#803]
I have a legacy NetTcp service that I have ported to CoreWcf in NET6.0. When I run it in Windows it works perfectly, including against the legacy NET 3.5 clients that haven't been touched in years. 

To simplify the test case, I am debugging the simplest interface, although all of them work when running in Windows:

```
   [ServiceContract(SessionMode = SessionMode.Required)]
    public interface IWcfTest
    {
        [OperationContract]
        int Ping(int val);
    }
```

When I run it in WSL or a WSL2 Linux container, I get the following error. I am using cert-based transport security by default, but I get this even if I turn off transport security:

```
Unhandled exception. System.ServiceModel.ProtocolException: The server at net.tcp://localhost:9089/WcfTest rejected the session-establishment request.
 ---> System.ServiceModel.ProtocolException: Error while reading message framing format at position 1 of stream (state: UpgradeResponse)
 ---> System.IO.InvalidDataException: More data was expected, but EOF was reached.
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.ServiceModel.Channels.ConnectionUpgradeHelper.ValidatePreambleResponse(Byte[] buffer, Int32 count, ClientFramingDecoder decoder, Uri via)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.SendPreambleAsync(IConnection connection, ArraySegment`1 preamble, TimeSpan timeout)
   at System.ServiceModel.Channels.ConnectionPoolHelper.EstablishConnectionAsync(TimeSpan timeout)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.OnOpenAsync(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.OnOpenAsyncInternal(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.System.ServiceModel.IAsyncCommunicationObject.OpenAsync(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.OpenAsyncInternal(TimeSpan timeout)
   at System.Runtime.TaskHelpers.WaitForCompletion(Task task)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.Runtime.TaskHelpers.CallActionAsync[TArg](Action`1 action, TArg argument)
   at System.ServiceModel.Channels.ServiceChannel.OnOpenAsync(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.OnOpenAsyncInternal(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.System.ServiceModel.IAsyncCommunicationObject.OpenAsync(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.OpenAsyncInternal(TimeSpan timeout)
   at System.Runtime.TaskHelpers.WaitForCompletion(Task task)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOpenOnce.System.ServiceModel.Channels.ServiceChannel.ICallOnce.Call(ServiceChannel channel, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOnceManager.CallOnce(TimeSpan timeout, CallOnceManager cascade)
   at System.ServiceModel.Channels.ServiceChannel.EnsureOpened(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
   at generatedProxy_1.Ping(Int32 )
   at Program.<Main>$(String[] args) in C:\Users\Developer\avalanche\corewcf-test\Olympus.CoreWcf.Test\Olymps.CoreWcf.Test.Client\Program.cs:line 65
```

**Comment by andymartin** [comment]
For reference, my Dockerfile:

```
FROM mcr.microsoft.com/dotnet/aspnet:6.0-bullseye-slim
WORKDIR /app
COPY /publish .
ENTRYPOINT ["dotnet", "Compatibility.Api.dll"]
```

**Comment by andymartin** [comment]
Discovered after reading #136 that setting `SecurityMode.None` does work in the linux container. Unfortunately this is not compatible with legacy clients.  I tried this change to my Dockerfile to see if it was an older TLS handshake that was causing the issue but it made no difference:

```
FROM mcr.microsoft.com/dotnet/aspnet:6.0-bullseye-slim
RUN sed -i 's/MinProtocol = TLSv1.2/MinProtocol = TLSv1/' /etc/ssl/openssl.cnf \
&& sed -i 's/CipherString = DEFAULT@SECLEVEL=2/CipherString = DEFAULT@SECLEVEL=1/' /etc/ssl/openssl.cnf

WORKDIR /app
COPY /publish .
ENTRYPOINT ["dotnet", "Avalanche.Compatibility.Api.dll"]
```

**Comment by andymartin** [comment]
Thanks for your reply. I'm using Transport security and setting `binding.Security.Transport.ClientCredentialType = TcpClientCredentialType.Certificate;`. Shouldn't that skip negotiation and just and use certificate validation instead?

**Comment by mconnew** [comment]
Using Certificate credential type means it will use certificates with SslStream instead. The call stack above is most likely caused by the client and the server being configured with different client credential types, or different SecurityMode values (None vs Transport for example).
