### ISSUE TITLE
GetCallbackChannel returns null

### ISSUE THREAD

**Issue by DarkPro1337** [CoreWCF/CoreWCF#818]
After migrating WCF service from .NET framework to .NET6 encountered strange issue when `OperationContext.Current?.GetCallbackChannel<INameCallback>()` returns null for some reason. This happens without any exceptions. There are no anything suspiscious inside `OperationContext`, but inside the `OperationContext` field `Channel` contains the proxy for my `INameCallback` but inside proxy there are `ChannelDispatcher` that contains `NotSupportedException` that says "`Specified method is not supported.`" and the stacktrace it's contains. Is there are any way to fix? Channel uses Duplex and NetTcpBinding. Can't find anything regard this issue, and I can't show any code because of my NDA.

_Stacktrace of ChannelDispatcher:_
```
   at CoreWCF.Channels.ServiceChannel.CoreWCF.Channels.IChannel.get_ChannelDispatcher()
   at CoreWCF.Channels.ServiceChannelProxy.CoreWCF.Channels.IChannel.get_ChannelDispatcher()
```

**Comment by DarkPro1337** [comment]
Ooops, I'm sorry about this issue, if someone endup in situation like this - check if you are not using `System.ServiceModel.OperationContext` to `GetCallbackChnannel` of your proxy, this breaking everything.
