### ISSUE TITLE
NetTcp Binding: System.InvalidOperationException: Reading is already in progress.

### ISSUE THREAD

**Issue by jesuspsalas** [CoreWCF/CoreWCF#841]
I am refactoring a set of WCF Service using Net Tcp Binding, and when the clients engages the service I am seeing the following recurrent error on logs:

System.InvalidOperationException: Reading is already in progress.
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_AlreadyReading()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
   at System.IO.Pipelines.Pipe.DefaultPipeReader.ReadAsync(CancellationToken cancellationToken)
   at CoreWCF.Channels.Framing.ExceptionConvertingDuplexPipe.ExceptionConvertingPipeReader.ReadAsync(CancellationToken cancellationToken)
   at CoreWCF.Channels.Framing.FramingConnection.SendFaultAsync(String faultString, TimeSpan sendTimeout, Int32 maxRead)
   at CoreWCF.Channels.ServerFramingDuplexSessionChannel.ServerSessionConnectionMessageSource.DecodeMessage(ReadOnlySequence`1& buffer)
   at CoreWCF.Channels.ServerFramingDuplexSessionChannel.ServerSessionConnectionMessageSource.ReceiveAsync(CancellationToken token)
   at CoreWCF.Channels.SynchronizedMessageSource.ReceiveAsync(CancellationToken token)
   at CoreWCF.Channels.TransportDuplexSessionChannel.ReceiveAsync(CancellationToken token)
   at CoreWCF.Channels.TransportDuplexSessionChannel.TryReceiveAsync(CancellationToken token)
   at CoreWCF.Channels.TransportDuplexSessionChannel.StartReceivingAsync()
   at CoreWCF.Channels.Framing.ServerSessionConnectionReaderMiddleware.OnConnectedAsync(FramingConnection connection)
   at CoreWCF.Channels.Framing.ServerFramingDuplexSessionMiddleware.OnConnectedAsync(FramingConnection connection)
   at CoreWCF.Channels.Framing.NetMessageFramingConnectionHandler.PerformServiceHandshake(IFramingConnectionHandshakeBuilder configuration, FramingConnection connection, HandshakeDelegate next)
   at CoreWCF.Channels.Framing.DuplexFramingMiddleware.OnConnectedAsync(FramingConnection connection)
   at CoreWCF.Configuration.MapMiddleware.Invoke(FramingConnection connection)
   at CoreWCF.Channels.Framing.FramingModeHandshakeMiddleware.OnConnectedCoreAsync(FramingConnection connection)
   at CoreWCF.Channels.Framing.FramingModeHandshakeMiddleware.OnConnectedAsync(FramingConnection connection)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection`1.ExecuteAsync()

Is there anything I have to change in the WebHost configuration to resolve this problem?

Thanks!

**Comment by gfaraj** [comment]
Any info on this?

**Comment by icnocop** [comment]
I'm experiencing the same issue.

`connection.ServiceDispatcher` is null.

Is this expected behavior?

![image](https://github.com/user-attachments/assets/4ff818bf-8b6d-4446-a724-bb1f6ade7730)

I'm running in a console application:
```
string configurationFile = ConfigurationManager.OpenExeConfiguration(ConfigurationUserLevel.None).FilePath;

var builder = WebApplication.CreateBuilder();

builder.WebHost.UseNetTcp(options =>
{
    options.Listen("net.tcp://localhost:4502", configure =>
    {
        configure.ConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint = int.MaxValue;
    });
});

builder.Services
    .AddLogging(configure =>
    {
        configure.SetMinimumLevel(LogLevel.Trace);
        configure.AddConsole();
    })
    .AddServiceModelServices()
    .AddServiceModelConfigurationManagerFile(configurationFile)
    .AddServiceModelMetadata()
    .AddSingleton<MyDuplexService1>()
    .AddTransient<MyService1>()
    .AddTransient<MyDuplexService2>()
    .AddTransient<MyService2>();

var webApplicationHost = builder.Build();

var webApplicationHost.StartAsync();
```

Console output:
```
dbug: CoreWCF.Configuration.NetTcpFramingOptions[0]
      Adding base address net.tcp://[::]:4502/ to ServiceBuilderOptions
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:4502
dbug: Microsoft.AspNetCore.Hosting.Diagnostics[13]
      Loaded hosting startup assembly MyWindowsServiceHost
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\dev\MySolution\MyWindowsServiceHost\bin\Debug\net8.0-windows
dbug: Microsoft.Extensions.Hosting.Internal.Host[2]
      Hosting started
dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[39]
      Connection id "0HN8KOOBRGC7V" accepted.
dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[1]
      Connection id "0HN8KOOBRGC7V" started.
trce: CoreWCF.Channels.Framing.FramingConnection[1000]
      [0HN8KOOBRGC7V] ServerModeDecoder:Start state is ReadingVersionRecord
trce: CoreWCF.Channels.Framing.FramingConnection[1001]
      [0HN8KOOBRGC7V] ServerModeDecoder:End state is ReadingMajorVersion after reading 1 bytes
trce: CoreWCF.Channels.Framing.FramingConnection[1000]
      [0HN8KOOBRGC7V] ServerModeDecoder:Start state is ReadingMajorVersion
trce: CoreWCF.Channels.Framing.FramingConnection[1001]
      [0HN8KOOBRGC7V] ServerModeDecoder:End state is ReadingMinorVersion after reading 1 bytes
trce: CoreWCF.Channels.Framing.FramingConnection[1000]
      [0HN8KOOBRGC7V] ServerModeDecoder:Start state is ReadingMinorVersion
trce: CoreWCF.Channels.Framing.FramingConnection[1001]
      [0HN8KOOBRGC7V] ServerModeDecoder:End state is ReadingModeRecord after reading 1 bytes
trce: CoreWCF.Channels.Framing.FramingConnection[1000]
      [0HN8KOOBRGC7V] ServerModeDecoder:Start state is ReadingModeRecord
trce: CoreWCF.Channels.Framing.FramingConnection[1001]
      [0HN8KOOBRGC7V] ServerModeDecoder:End state is ReadingModeValue after reading 1 bytes
trce: CoreWCF.Channels.Framing.FramingConnection[1000]
      [0HN8KOOBRGC7V] ServerModeDecoder:Start state is ReadingModeValue
trce: CoreWCF.Channels.Framing.FramingConnection[1001]
      [0HN8KOOBRGC7V] ServerModeDecoder:End state is Done after reading 1 bytes
trce: CoreWCF.Channels.Framing.FramingConnection[1002]
      [0HN8KOOBRGC7V] ServerSessionDecoder:Start state is ReadingViaRecord
trce: CoreWCF.Channels.Framing.FramingConnection[1003]
      [0HN8KOOBRGC7V] ServerSessionDecoder:End state is ReadingViaString after reading 1 bytes
trce: CoreWCF.Channels.Framing.FramingConnection[1002]
      [0HN8KOOBRGC7V] ServerSessionDecoder:Start state is ReadingViaString
trce: CoreWCF.Channels.Framing.FramingConnection[1010]
      [0HN8KOOBRGC7V] StringDecoder:Start state is ReadingSize
trce: CoreWCF.Channels.Framing.FramingConnection[1050]
      [0HN8KOOBRGC7V] IntDecoder:Decoding Int with  next 37 at index 0, with total so far 37
trce: CoreWCF.Channels.Framing.FramingConnection[1011]
      [0HN8KOOBRGC7V] StringDecoder:End state is ReadingBytes after reading 1 bytes
trce: CoreWCF.Channels.Framing.FramingConnection[1003]
      [0HN8KOOBRGC7V] ServerSessionDecoder:End state is ReadingViaString after reading 1 bytes
trce: CoreWCF.Channels.Framing.FramingConnection[1002]
      [0HN8KOOBRGC7V] ServerSessionDecoder:Start state is ReadingViaString
trce: CoreWCF.Channels.Framing.FramingConnection[1010]
      [0HN8KOOBRGC7V] StringDecoder:Start state is ReadingBytes
trce: CoreWCF.Channels.Framing.FramingConnection[1051]
      [0HN8KOOBRGC7V] StringDecoder:String decoded: "net.tcp://localhost:4502/MyDuplexService1"
trce: CoreWCF.Channels.Framing.FramingConnection[1011]
      [0HN8KOOBRGC7V] StringDecoder:End state is Done after reading 37 bytes
trce: CoreWCF.Channels.Framing.FramingConnection[1003]
      [0HN8KOOBRGC7V] ServerSessionDecoder:End state is ReadingContentTypeRecord after reading 37 bytes
trce: CoreWCF.Channels.Framing.FramingConnection[1002]
      [0HN8KOOBRGC7V] ServerSessionDecoder:Start state is ReadingContentTypeRecord
trce: CoreWCF.Channels.Framing.FramingConnection[1003]
      [0HN8KOOBRGC7V] ServerSessionDecoder:End state is ReadingContentTypeByte after reading 1 bytes
trce: CoreWCF.Channels.Framing.FramingConnection[1002]
      [0HN8KOOBRGC7V] ServerSessionDecoder:Start state is ReadingContentTypeByte
trce: CoreWCF.Channels.Framing.FramingConnection[1003]
      [0HN8KOOBRGC7V] ServerSessionDecoder:End state is PreUpgradeStart after reading 1 bytes
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[6]
      Connection id "0HN8KOOBRGC7V" received FIN.
```

**Comment by icnocop** [comment]
The code

https://github.com/CoreWCF/CoreWCF/blob/17f9b887e61c4cb76ceb0bd7e429ad82b26ab174/src/CoreWCF.NetFramingBase/src/CoreWCF/Channels/Framing/FramingModeHandshakeMiddleware.cs#L85-L91

was added in PR: https://github.com/CoreWCF/CoreWCF/pull/1335 for the issue https://github.com/CoreWCF/CoreWCF/issues/1331

**Comment by icnocop** [comment]
After explicitly calling `AddServiceEndpoint`, the exception no longer occurs.

For example:
```
var builder = WebApplication.CreateBuilder();

builder.WebHost.UseNetTcp(options =>
{
    options.Listen("net.tcp://localhost:4502", configure =>
    {
        configure.ConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint = int.MaxValue;
    });
});

builder.Services
    .AddLogging(configure =>
    {
        configure.SetMinimumLevel(LogLevel.Trace);
        configure.AddConsole();
    })
    .AddServiceModelServices()
    .AddServiceModelMetadata()
    .AddSingleton<MyDuplexService>();

var webApplicationHost = builder.Build();

((IApplicationBuilder)webApplicationHost).UseServiceModel(serviceBuilder =>
{
    serviceBuilder.AddService<MyDuplexService>((serviceOptions) =>
    {
        serviceOptions.DebugBehavior.IncludeExceptionDetailInFaults = true;
    })
    .AddServiceEndpoint<MyDuplexService, IMyDuplexService>(new NetTcpBinding(), "net.tcp://localhost:4502/MyDuplexService");
});

webApplicationHost.StartAsync();
```

**Comment by gfaraj-alkami** [comment]
I'm already using `AddServiceEndpoint` and this only happens on very rare occasions. Any ideas? Is there any way to find what's failing to set `ServiceDispatcher`?

**Comment by mconnew** [comment]
@lukasz-o, can you repro this reliably? I think I might have a simple fix and if you can reproduce this reliably, I'd like you to test it before I submit a PR with the change.

**Comment by mconnew** [comment]
@lukasz-o, how often does it happen? Is it often enough that running with a pre-release build for a few days, maybe even a week would be enough to confirm the problem is fixed? E.g. if it happens 3 or 4 times per week, and a pre-release build has no problems for an entire week, that's good evidence the problem is fixed.
