### ISSUE TITLE
NullReferenceException from FramingModeHandshakeMiddleware

### ISSUE THREAD

**Issue by andymartin** [CoreWCF/CoreWCF#878]
I am reimplementing old net framework WCF services in CoreWCF.  On one endpoint, I am using a Streamed NetTcpBinding to transfer files and the services has just finished reading the data stream and returned the response when the client logs this:

`Error while reading message framing format at position 339 of stream (state: EnvelopeEnd)`

Now weirdly, this only happens when it takes more than one read to consume the entire stream.

On the service side, nothing throws but this appears in my logs:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at CoreWCF.Channels.Framing.FramingModeHandshakeMiddleware.OnConnectedCoreAsync(FramingConnection connection)
   at CoreWCF.Channels.Framing.FramingModeHandshakeMiddleware.OnConnectedAsync(FramingConnection connection)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection`1.ExecuteAsync()
```

Specifically happens when the reuseHandler is assigned.  ServiceDispatcher is null, so it throws a non-propagating exception that kills the transaction. I pulled in the source code and symbols and this is where the exception is being thrown:

```
// connection.ServiceDispatcher is null until later middleware layers are executed.
if (reuseHandler == null)

    reuseHandler = connection.ServiceDispatcher.Binding.GetProperty<IConnectionReuseHandler>(new BindingParameterCollection());
}
```

This exception appears in the logs but also never is thrown. I have no idea if it is related.

```

[15:06:03 VRB] [0HMLGEADPLPDR] Failed to reuse connection
Microsoft.AspNetCore.Connections.ConnectionAbortedException: The connection was aborted by the application via ConnectionContext.Abort().
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
   at System.IO.Pipelines.Pipe.DefaultPipeReader.ReadAsync(CancellationToken cancellationToken)
   at CoreWCF.Channels.Framing.ExceptionConvertingDuplexPipe.ExceptionConvertingPipeReader.ReadAsync(CancellationToken cancellationToken)
   at CoreWCF.Channels.ConnectionReuseHandler.ReuseConnectionAsync(FramingConnection connection, CancellationToken cancellationToken)
```

Thanks!

**Comment by C12139** [comment]
This issue can be easily reproduced by using the samples/Scenarios/Getting-Started-with-CoreWCF/ and running up NetCoreServer and NetCoreClient. The various Http example calls complete successfully, but the tcp example fails due to this issue.

This means the tcp is unusable and therefore this issue should be fixed as a priority.

This was observed in CoreWCF v1.3.2.
