### ISSUE TITLE
NetCoreClient throws exception "type is not a ServiceContract"

### ISSUE THREAD

**Issue by dgxhubbard** [CoreWCF/CoreWCF#89]
I add a small service to NetCoreClient and NetCoreService, when the service factory is created from the NetCoreClient

'''c#
var factory = new ChannelFactory<ISchedulerService>(new BasicHttpBinding(), new EndpointAddress("http://localhost:8080/basichttp"));
'''

an exception is thrown with the message:

Attempted to get contract type for ISchedulerService, but that type is not a ServiceContract, nor does it inherit a ServiceContract.

  Source=System.Private.ServiceModel
  StackTrace:
   at System.ServiceModel.Description.ServiceReflector.GetContractTypeAndAttribute(Type interfaceType, ServiceContractAttribute& contractAttribute)
   at System.ServiceModel.Description.TypeLoader.LoadContractDescriptionHelper(Type contractType, Type serviceType, Object serviceImplementation)
   at System.ServiceModel.ChannelFactory`1.CreateDescription()
   at System.ServiceModel.ChannelFactory.InitializeEndpoint(Binding binding, EndpointAddress address)
   at System.ServiceModel.ChannelFactory`1..ctor(Binding binding, EndpointAddress remoteAddress)
   at NetCoreClient.Program.Main(String[] args) in C:\Github\CoreWCF\src\Samples\NetCoreClient\Program.cs:line 23

To do this I added a netstandard 2.0 library TaskLibrary to CoreWCFWithSamples.sln. Then I added a definition for two types:

ISchedulerService

'''c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;

using CoreWCF;

namespace TaskLibrary
{

    [ServiceContract]
    [ServiceKnownType ( typeof ( TaskTypes ) )]

    public interface ISchedulerService
    {
        #region Methods

        [OperationContract]
        List<TaskTypes> GetSupportedTaskTypes  ();

        #endregion
    }
}

'''
TaskTypes

'''c#

using System;
using System.Collections.Generic;
using System.Text;

namespace TaskLibrary
{
    public enum TaskTypes
    {
        ManualTask,
        AutoTask,
        RepetitiveTask

    }
}

'''
Next I added TaskLibrary references to NetCoreClient and NetCoreServer. 

To NetCoreServer startup.cs the Configure code was modified to:

'''c#
        public void Configure ( IApplicationBuilder app, IHostingEnvironment env )
        {
            app.UseServiceModel ( builder =>
              {
                  builder.AddService<SchedulerService> ();
                  builder.AddServiceEndpoint<SchedulerService, TaskLibrary.ISchedulerService> ( new BasicHttpBinding (), "/basichttp" );
              } );
        }

'''

To NetCoreClient program.cs the Main code was modified as shown below. After NetCoreServer is started up, then NetCoreClient is started and the exception at the start of the post is generated.

What am I doing wrong?

'''c#

        static void Main(string[] args)
        {
            /*
            var factory = new ChannelFactory<Contract.IEchoService>(new NetTcpBinding(), new EndpointAddress("net.tcp://localhost:8808/nettcp"));
            factory.Open();
            var channel = factory.CreateChannel();
            ((IClientChannel)channel).Open();
            Console.WriteLine("net.tcp Echo(\"Hello\") => " + channel.Echo("Hello"));
            ((IClientChannel)channel).Close();
            factory.Close();
            */

            
            var factory = new ChannelFactory<ISchedulerService>(new BasicHttpBinding(), new EndpointAddress("http://localhost:8080/basichttp"));
            factory.Open();
            var channel = factory.CreateChannel();
            ((IClientChannel)channel).Open();

            var taskTypes = channel.GetSupportedTaskTypes ();

            //Console.WriteLine("http Echo(\"Hello\") => " + channel.Echo("Hello"));

            ((IClientChannel)channel).Close();
            factory.Close();
            

            Console.WriteLine("Hit enter to exit");
            Console.ReadLine();
        }

**Comment by dgxhubbard** [comment]
In the IEchoService of the sample NetCoreClient and NetCoreServer there is a "using System.ServiceModel", but in ISchedulerService there is "using CoreWCF" so the two get the 
ServiceContract, OperationContract attributes from diff namespaces. Is this the problem?



IEchoService

```c#
using System.ServiceModel;

namespace Contract
{
    [ServiceContract]
    public interface IEchoService
    {
        [OperationContract]
        string Echo(string text);
    }
}

```

IScheduleService

```c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;

using CoreWCF;

namespace TaskLibrary
{

    [ServiceContract]
    [ServiceKnownType ( typeof ( TaskTypes ) )]

    public interface ISchedulerService
    {
        #region Methods

        [OperationContract]
        List<TaskTypes> GetSupportedTaskTypes  ();

        #endregion
    }
}

```

**Comment by dgxhubbard** [comment]
In the IEchoService on the server there is a "using CoreWCF", while the client has "using System.ServiceModel". Does this mean we need to contract definitions?


```c#

using CoreWCF;

namespace Contract
{
    [ServiceContract]
    public interface IEchoService
    {
        [OperationContract]
        string Echo(string text);
    }
}

```

**Comment by mconnew** [comment]
Yes, that is the problem. ChannelFactory needs to use System.ServiceModel.ServiceContractAttribute and CoreWCF needs to use CoreWCF.ServiceContractAttribute. I actually have a PR right now to allow CoreWCF to use the S.SM attributes so you can use a single common contract if you want (#87). I'm just waiting on a code review. So you can either do the juggling with the two namespaces or you can wait until someone has reviewed my changes and then pick up the latest packages which allows you to just use S.SM.ServiceContract if that's what you would prefer.

**Comment by dgxhubbard** [comment]
I volunteer for the code review!
Do you know how long it will be till the code changes are reviewed and output into the packages we can download.

**Comment by mconnew** [comment]
If you believe you understand what the code is doing, feel free to review it. Basically I'm needing a review for 
1. Stupid mistakes. Previously I've accidentally added a local .cmd file used to help with development. 2. Is test coverage sufficient. 
3. Egregiously bad code such as multiple copies of a constant strings being inline rather than a separate const.
4. Clumsy code. Anything which makes you do unnecessary mental gymnastics to follow the flow. For example having a bool named notFound then having an if (!notFound). That would be better switching the logic and having a bool called found and do if (found).
5. Clarity of code. My goal is that 95% of the code can be understood by an average dev with several years experience in .NET. While I have fun writing what I call "voodoo code", it should be the minority of the codebase.  That doesn't mean you can understand it immediately, but most of the code shouldn't be out of the reach of most devs. 

So feel free to review. It might be worth reviewing each of the commits separately. For once I broke down independent changes into separate commits. E.g. I made an unrelated bug fix I discovered while debugging this feature so put it in it's own commit.

Once reviewed and any change made, new packages are automatically built on merge.

**Comment by dgxhubbard** [comment]
Therein is the problem. I have only started looking at the code to understand it :(.

**Comment by mconnew** [comment]
Feel free to look at it and if you feel up to reviewing it, go ahead. You can post questions to the PR too if you need some help with contextualizing what's going on.

**Comment by mconnew** [comment]
But please don't feel like you have to. Although personally I sometimes learn new things from reading others code which I then can apply in my own code.

**Comment by dgxhubbard** [comment]
Ok, I will do that. I didn't want to have you assume I knew the code.

**Comment by dgxhubbard** [comment]
I checked this morning and there is no update on
[CoreWCF Private](https://pkgs.dev.azure.com/dotnet/CoreWCF/_packaging/CoreWCF/nuget/v3/index.json)
Do you know when that will be released?

**Comment by dgxhubbard** [comment]
I did a pull from latest and I have the TaskLibrary with ISchedulerService, and using CoreWCF in the NetCoreServer and NetCoreClient. Then as run NetCoreServer and it starts no problem. When I run NetCoreClient I get an InvalidOperationException that ISchedulerService is not a ServiceContract. Didn't #87 take care of this issue?

ISchedulerService

```c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;

using CoreWCF;

namespace TaskLibrary
{

    [ServiceContract]
    [ServiceKnownType ( typeof ( TaskTypes ) )]

    public interface ISchedulerService
    {
        #region Methods

        [OperationContract]
        List<TaskTypes> GetSupportedTaskTypes  ();

        #endregion
    }
}

```

**Comment by mconnew** [comment]
You are trying to use `CoreWCF.ServiceContractAttribute` with `ChannelFactory` which is the wrong way around. Issue #87 allows you to use `System.ServiceModel.ServiceContractAttribute` with CoreWCF.

**Comment by mconnew** [comment]
I checked the package index and I'm seeing the latest packages from Friday. They have the version 0.1.0-alpha.51. You can see the list of packages for CoreWCF.Primitives by following [this link](https://pkgs.dev.azure.com//dotnet/19be58e5-e66b-429a-bf79-f46cbe800a40/_packaging/7ded69a8-7af7-4f6d-8509-cfca2937eb13/nuget/v3/query2/?q=CoreWCF.Primitives&skip=0&take=15&prerelease=true&semVerLevel=2.0.0).
```json
{
    "@context": {
        "@vocab": "http://schema.nuget.org/schema#",
        "comment": "http://www.w3.org/2000/01/rdf-schema#comment",
        "label": "http://www.w3.org/2000/01/rdf-schema#label"
    },
    "data": [{
            "@id": "",
            "@type": "Package",
            "id": "CoreWCF.Primitives",
            "version": "0.1.0-alpha.51",
            "description": "Package Description",
            "versions": [{
                    "@id": "CoreWCF.Primitives",
                    "downloads": 0,
                    "version": "0.1.0-alpha.51"
                }, {
                    "@id": "CoreWCF.Primitives",
                    "downloads": 0,
                    "version": "0.1.0-alpha.46"
                }, {
                    "@id": "CoreWCF.Primitives",
                    "downloads": 0,
                    "version": "0.1.0-alpha.45"
                }, {
                    "@id": "CoreWCF.Primitives",
                    "downloads": 0,
                    "version": "0.1.0-alpha.44"
                }
            ],
            "authors": ["CoreWCF.Primitives"],
            "iconUrl": null,
            "licenseUrl": "https://licenses.nuget.org/MIT",
            "projectUrl": null,
            "registration": "",
            "summary": null,
            "tags": [],
            "title": null
        }
    ],
    "lastReopen": "2020-01-06T20:41:02.2642918Z",
    "index": "PackageIndex",
    "totalHits": "0"
}
```
The download counts aren't correct, I think they list 0 if you don't have permissions and I made an unauthenticated request.

**Comment by dgxhubbard** [comment]
Thanks @mconnew  that did the trick its working now.

**Comment by dgxhubbard** [comment]
How do I use the links for latest packages in NuGet manager in vs 2019?

**Comment by dgxhubbard** [comment]
I realize I can download the dlls but do I need to put them in the nuget store on my machine by hand?

**Comment by Kralizek** [comment]
If you have the packages (nupkg), you can place them into a folder and add the folder in the nuget.config as a source.

If you have the raw assemblies, you just need to reference the assemblies explicitly.

**Comment by dgxhubbard** [comment]
To rephrase the question are these not available through nuget?

**Comment by mconnew** [comment]
You look to be doing the right thing. It looks like the problem is your proxy server that you have configured. Here's the relevant part from your logs:
```
Failed to download package 'CoreWCF.NetTcp.0.1.0-alpha.51' from 'https://pkgs.dev.azure.com/dotnet/19be58e5-e66b-429a-bf79-f46cbe800a40/_packaging/7ded69a8-7af7-4f6d-8509-cfca2937eb13/nuget/v3/flat2/corewcf.nettcp/0.1.0-alpha.51/corewcf.nettcp.0.1.0-alpha.51.nupkg'.
An error occurred while sending the request.
The request was aborted: The request was canceled.
The ServicePointManager does not support proxies with the https scheme.
```
Basically you need to either specify http for your proxy server or have no scheme (just hostname and possible port number.) The communication to your proxy server is over http, but the proxy server still tunnels the https traffic to the remote server. The distinction is that the proxy server isn't the one doing the TLS handshake with the client, the remote host is, so the proxy server itself is only using http. [Here's](The ServicePointManager does not support proxies with the https scheme.) some documentation about it.

**Comment by dgxhubbard** [comment]
Is the proxy server your referring to this:

https://pkgs.dev.azure.com/dotnet/CoreWCF/_packaging/CoreWCF/nuget/v3/index.json

because I got that from "How do I get started". Otherwise I am not sure what your referring to as to specifying http for your proxy server.

**Comment by mconnew** [comment]
No, you have configured a proxy server somewhere on your system. You might have an `http_proxy` configured in your nuget.config. Or you might have one of HTTP_PROXY or HTTPS_PROXY environment variables set. Or you might have a system wide proxy server configured (check Windows settings).

**Comment by dgxhubbard** [comment]
I am using the global nuget.config and there is no proxy server set:

```html
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="Telerik Nuget" value="https://nuget.telerik.com/nuget" />
    <add key="Microsoft Visual Studio Offline Packages" value="C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\" />
    <add key="CoreWCF" value="https://pkgs.dev.azure.com/dotnet/CoreWCF/_packaging/CoreWCF/nuget/v3/index.json" />
  </packageSources>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <bindingRedirects>
    <add key="skip" value="False" />
  </bindingRedirects>
  <packageManagement>
    <add key="format" value="0" />
    <add key="disabled" value="False" />
  </packageManagement>
</configuration>
```

**Comment by mconnew** [comment]
You must have the proxy server configured elsewhere, e.g. at a system level or via environment variables. I can't really help you with diagnosing that correctly, but as a workaround you could try adding this section to your nuget.config:
```xml
<configuration>
    <config>
        <add key="no_proxy" value="pkgs.dev.azure.com" />
    </config>
</configuration>
```
That disables use of the proxy server only when communicating with pkgs.dev.azure.com. If your network is set up that you require a proxy to communicate to the internet, then this won't work, in which case you need to fix your proxy config.  

There is something bothering me about the error. I checked the source code of .NET to see where that error message is emitted, and it only happens in the one place, where it checks the scheme of the configured proxy server. The only condition which can cause that error is using a proxy server with https as the scheme, nothing else. What's odd is that it appears to work communicating to nuget.org and telerek using https. It also doesn't have a problem downloading the package index file over https. The only explanation I can come up with is your system admin uses a PAC auto configuration script to configure the proxy server and the script returns something different for different hosts.

One other thought I had is try adding  `protocolVersion="3"` to the CoreWCF server. I believe that the Azure devops nuget server can use protocol version 3 and it's possible (although doubtful) it might cause different behavior.

I have double checked that the packages can be downloaded completely unauthenticated from the url's in your error log so there's nothing wrong on the server side. It's something peculiar with your local machine.

**Comment by dgxhubbard** [comment]
I work remote and go directly through my ISP so there is no proxy server. I don't think my ISP is getting in the way because I was able to download the first release 0.1.0-PullRequest0078.47 no problem. I will add the no proxy and see what happens.

**Comment by dgxhubbard** [comment]
With the setting of no-proxy I try to install CoreWCF primitives and get the following error:

PM> Install-Package CoreWCF.Primitives -version 0.1.0-alpha.51
Install-Package : NU1605: Detected package downgrade: CoreWCF.Primitives from 0.1.0-PullRequest0078.47 to 0.1.0-alpha.51. Reference the package directly from the project to select a 
different version. 
 Gt -> Gt.ConnectionWizard -> Gt.Base -> CoreWCF.Primitives (>= 0.1.0-PullRequest0078.47) 
 Gt -> CoreWCF.Primitives (>= 0.1.0-alpha.51)
At line:1 char:1
+ Install-Package CoreWCF.Primitives -version 0.1.0-alpha.51
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : NU1605: Detected package downgrade: CoreWCF.Primitives from 0.1.0-PullRequest0078.47 to 0.1.0-alpha.51. Reference the package directly from the project to select a 
different version. 
 Gt -> Gt.Controls -> Gt.Base -> CoreWCF.Primitives (>= 0.1.0-PullRequest0078.47) 
 Gt -> CoreWCF.Primitives (>= 0.1.0-alpha.51)
At line:1 char:1
+ Install-Package CoreWCF.Primitives -version 0.1.0-alpha.51
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : NU1605: Detected package downgrade: CoreWCF.Primitives from 0.1.0-PullRequest0078.47 to 0.1.0-alpha.51. Reference the package directly from the project to select a 
different version. 
 Gt -> Gt.BaseDefs -> Gt.Base -> CoreWCF.Primitives (>= 0.1.0-PullRequest0078.47) 
 Gt -> CoreWCF.Primitives (>= 0.1.0-alpha.51)
At line:1 char:1
+ Install-Package CoreWCF.Primitives -version 0.1.0-alpha.51
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : NU1605: Detected package downgrade: CoreWCF.Primitives from 0.1.0-PullRequest0078.47 to 0.1.0-alpha.51. Reference the package directly from the project to select a 
different version. 
 Gt -> Gt.BaseDefs -> Gt.Model -> CoreWCF.Primitives (>= 0.1.0-PullRequest0078.47) 
 Gt -> CoreWCF.Primitives (>= 0.1.0-alpha.51)
At line:1 char:1
+ Install-Package CoreWCF.Primitives -version 0.1.0-alpha.51
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : NU1605: Detected package downgrade: CoreWCF.Primitives from 0.1.0-PullRequest0078.47 to 0.1.0-alpha.51. Reference the package directly from the project to select a 
different version. 
 Gt -> Gt.AppCommon -> Gt.Model -> CoreWCF.Primitives (>= 0.1.0-PullRequest0078.47) 
 Gt -> CoreWCF.Primitives (>= 0.1.0-alpha.51)
At line:1 char:1
+ Install-Package CoreWCF.Primitives -version 0.1.0-alpha.51
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'Gt'.
At line:1 char:1
+ Install-Package CoreWCF.Primitives -version 0.1.0-alpha.51
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:00.8121228

**Comment by dgxhubbard** [comment]
I checked my nuget store and CoreWCF primitives was downloaded, and http and nettcp were downloaded, with the downgrade error messages. Then I went into and changed the version references in the effected projects from 0.1.0-PullRequest0078.47 to 0.1.0-alpha.51. After I did that I opened nuget package mgr UI and then I could see that 0.1.0-alpha.52 is available. I upgraded through the UI no problem. So does the problem come from the name of release .1.0-PullRequest0078.47.

**Comment by mconnew** [comment]
I think you have two problems. First, a proxy server issue (could be anti-virus software acting as a proxy maybe?) as that error message only happens when a proxy server is being used. The second was the bad package I accidentally pushed by doing a manual build while testing. I delisted it as soon as I saw it but 47 people have installed it :(. Nuget is doing things alphabetical so alpha < PullRequest so it sees it as a downgrade.

**Comment by mconnew** [comment]
@dgxhubbard, is this still an issue?

**Comment by dgxhubbard** [comment]
I will have to update and find out. Is CoreWCF available on regular Nuget?

**Comment by mconnew** [comment]
Yes it is. It's a couple of builds behind the devops feed so is missing a couple of small fixes unrelated to this.

**Comment by dgxhubbard** [comment]
Thats great! Thanks for you and every contributors hard work.

**Comment by dgxhubbard** [comment]
Is there one name to use on nuget to get all packages

**Comment by mconnew** [comment]
There isn't. Do you see value in having a CoreWCF.All package? Over time we might end up with quite a few packages for various features.
