### ISSUE TITLE
IAuthorizationService is a transient type but it is being resolved from the root container and placed into a singleton

### ISSUE THREAD

**Issue by ChristopherHaws** [CoreWCF/CoreWCF#947]
After updating to 1.3.0, I am getting an error when trying to start our application (see below) about `ServiceAuthorizationBehavior` not being able to resolve `IAuthorizationService`. When looking through the CoreWCF code, it looks like `ServiceAuthorizationBehavior` is being registered as a singleton and it has a dependency on `IAuthorizationService` which is a transient type which cannot be resolved from the root service provider:
https://github.com/CoreWCF/CoreWCF/blob/bbc1a9f3c97efad629598926e11852e6d2dfefb2/src/CoreWCF.Primitives/src/CoreWCF/Configuration/ServiceModelServiceCollectionExtensions.cs#L85

```
Unhandled exception. System.InvalidOperationException: Cannot resolve 'Microsoft.AspNetCore.Authorization.IAuthorizationService' from root provider because it requires scoped service 'Microsoft.AspNetCore.Authorization.IAuthorizationHandler'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(Type serviceType, IServiceScope scope, IServiceScope rootScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at CoreWCF.Configuration.ServiceModelServiceCollectionExtensions.<>c.<AddServiceModelServices>b__1_2(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at CoreWCF.Configuration.ServiceModelServiceCollectionExtensions.<>c.<AddServiceModelServices>b__1_1(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at CoreWCF.ServiceHostObjectModel`1.CreateDescription(IDictionary`2& implementedContracts)
   at CoreWCF.ServiceHostBase.InitializeDescription(UriSchemeKeyedCollection baseAddresses)
   at CoreWCF.ServiceHostObjectModel`1..ctor(IServiceProvider serviceProvider, ServiceBuilder serviceBuilder, ILogger`1 logger)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at CoreWCF.Description.DispatcherBuilder.BuildDispatcher[TService](ServiceConfiguration`1 serviceConfig, IServiceProvider services)
   at CoreWCF.Configuration.ServiceConfiguration`1.GetDispatchers()
   at CoreWCF.Configuration.DispatcherBuilderImpl.BuildDispatchers(Type serviceType)
   at CoreWCF.Channels.ServiceModelHttpMiddleware.BuildBranch()
   at CoreWCF.Channels.ServiceModelHttpMiddleware.EnsureBranchBuilt()
   at CoreWCF.Channels.ServiceModelHttpMiddleware.ServiceBuilderOpenedCallback(Object sender, EventArgs e)
   at CoreWCF.Channels.CommunicationObject.OnOpened()
--- End of stack trace from previous location ---
   at CoreWCF.Configuration.WrappingIServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Program.<Main>$(String[] args)
   at Program.<Main>(String[] args)

```

Note:
You will only get this error if you build the service provider with `ValidateScopes` enabled which we do:
```
services.BuildServiceProvider(new ServiceProviderOptions {
    ValidateScopes = true,
    ValidateOnBuild = true
});
```

**Comment by g7ed6e** [comment]
Thanks @ChristopherHaws for reporting issue.

I tried to reproduce in unit tests and in a sample project using the below code but did not get the error mentioned.
```c#
var builder = WebApplication.CreateBuilder();
builder.WebHost.UseDefaultServiceProvider(options =>
{
    options.ValidateScopes = true;
    options.ValidateOnBuild = true;
});
```
[MSDI scope validation documentation](https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection#scope-validation) details that only scoped type resolved from the root container or injected within a singleton will trigger an error.
The exception stack trace you provided is mentioning that transient type `IAuthorizationService` cannot be resolved as it has a dependency on scoped type `IAuthorizationHandler`. 
ASP.NET Core authorization infrastructure is registering `IAuthorizationHandler` types as transient ([see there](https://github.com/dotnet/aspnetcore/blob/d2f7bd0b37b7fed379d694b3231e6c5ddd177819/src/Security/Authorization/Core/src/AuthorizationServiceCollectionExtensions.cs#L21)), thus I'm suspecting you implemented a custom `IAuthorizationHandler` and registered the type as scoped, causing the issue.
According to ASP.NET Core authorization samples i found in documentation, user provided `IAuthorizationHandler` should either be registered as singleton ([see there](https://learn.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-7.0#iauthorizationservice)) or as transient ([see there](https://learn.microsoft.com/en-us/dotnet/architecture/microservices/secure-net-microservices-web-applications/authorization-net-microservices-web-applications#implement-policy-based-authorization)).
Modifying the lifetime of the `IAuthorizationHandler` you registered in DI to singleton or transient should fix the issue. 
If your custom `IAuthorizationHandler` is taking a dependency on a scoped type you should be able to inject `IServiceScopeFactory` into your implementation and resolve the scoped dependency from within a scope as described [here](https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-guidelines#shared-instance-limited-lifetime).

**Comment by ChristopherHaws** [comment]
According to the MS docs:
> Handlers can be registered using any of the built-in service lifetimes.

https://learn.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-7.0#handler-registration

I feel like this is a bug in CoreWCF and I shouldn't have to change code on my end to fix it, otherwise 1.3.0 should have been a major version. :)

**Comment by g7ed6e** [comment]
Yes, this is a bug. Once #948 will be merged, the above workaround won't be necessary.

**Comment by mconnew** [comment]
@ChristopherHaws, what's the urgency on this issue? Are you trying to use the policy authorization feature in CoreWCF, or are you using it elsewhere (eg with MVC) and the latest CoreWCF broke your app? I'm trying to gauge release timeframe for this fix. The previous 1.2.1 release is still supported for 6 months after 1.3 was released so if you aren't needing to use auth policies with your CoreWCF service, that reduces the urgency of releasing the fix.

**Comment by ChristopherHaws** [comment]
@mconnew It is not currently blocking us since we are just staying on the old version, however we would like to update our code to use the new MVC integrations which is why I was trying to update. I wouldn't say this is super critical but a nice to have. How long are you thinking it would be before the new version would be released with the fix? It does seem like it should be hotfixed at some point because people will have invisible scoping issues (unless they have validation enabled like I do, but that is a config you have to manually set) if they have any auth handlers that are not singleton which is a supported feature of ASP.NET Core.

Thanks! :)

**Comment by mconnew** [comment]
We'll definitely ship it soon, it's just about relative priorities. Blocking someone raises the priority and might mean putting something else on hold while I deal with the release.

**Comment by ChristopherHaws** [comment]
I am fine with waiting for the normal release cycle as long as it isn't months away :)

Thanks!
